---
version: '3'

services:
  matchbox:
    image: quay.io/poseidon/matchbox:v0.11.0
    container_name: matchbox
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/lib/matchbox:ro
    command: -address=0.0.0.0:8080 -log-level=debug
