app-template:
    ingress:
        main:
            annotations:
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:77Pklvu1BMjg,iv:pZhLD2GZX3CRUoni12pdfGnbjv+ddo7FZrX4/fgazKQ=,tag:1tO1ifZa8J6zRWovbs96vQ==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:A99aEb7HxUG152DI2K0huBSz3Fb4etqCyq27lwxf3gKeRGc=,iv:EH9FCR9aZ8gY/gJ5MBadzmd2cx15+JV3zlt0SGZ+pyA=,tag:F/g0Erko7LcaRTsInkqAiw==,type:str]
                gethomepage.dev/widget.key: ENC[AES256_GCM,data:jBQTwbuaPzZEJ1TGCUXLxfwReMqko1cwi3HEfRzc0sefM9jSS0jkycJE7TE63IEoCiWBUl55TBxLUSKJCCHp1W59D+E=,iv:HV+CA6sOzD3FgRL13UIAx7XDvB6zFhCCH1Qf4X0TsWw=,tag:HuskQfe59PeKYquhtRZJIA==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaEJJMC9YN2U0UlZ4azhN
            Ui83Z0tQUlR0MzJLbE1jcXd2UG9VMXYxcTBBCldrTHRGUS9Bcm9XU2xaeGhRL1Bq
            YU9hbEtxckp4SHlRQ0tBTnhIQmx4QVUKLS0tIEZuNTZxRng0YTY2Y044bUNJSmNq
            YnVCRHloRUlla3FFVHlzNWNhSFJXcmsKlSRrT8XrQfhLBey02X+8VCHrkVag6Y1c
            ijdZPjZNtQEUHPCDCTGss3MULUi5v7teEiepCEgbUGUL8+LNxIkU+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T01:58:39Z"
    mac: ENC[AES256_GCM,data:gfwLcsPjxn+NeC1FtSbsXpbH2hUNDkGyAW0di8NsRhK9cyOcitYxqSYOy5cyEuptfcSJH7hTwaQ9ePuJVDyEhcLZ/HBRgvX0VIRv1o7kxzTFOkJ4kC/uBVV1pgrMhq6V47CJcErvNC7zQMK1VfWKC6iOoLezNNRb++IV7H0Ws1o=,iv:OCC11hnKCEpk8f05oH6NwE5mBITL53/UQime4RefFrM=,tag:vlriIU1+z2S3k8n4ZK7YKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
