app-template:
    ingress:
        main:
            annotations:
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:dRRPKFOx1dbl,iv:rAUxVbj8gteDTz10oXRwvdzRfGJ4MEUZM1Bf+3Zle+Y=,tag:oJQZqZfUAcvKdykgQejX1w==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:QiSK9Dxa0ZSYbX8seqprT3fq3jFZpRoNSsnThQS8,iv:wNcKrxyJ9t8sshqHg58hl0+bEf8Q9keOVsAcSXDkoYI=,tag:ef2nrP7Aky1MB1ovm1IQMg==,type:str]
                gethomepage.dev/widget.key: ENC[AES256_GCM,data:WoRt3pxXo+avmORz1xrLgpfXXdfESQcnQZdyxNgiz5G8k7cCizPWoEanbE2HzlzOztySAIDpXiZu25tRON1ZwdjtAok=,iv:PRaXAE1EisNoyeulp3GWYswgNWDkSiTloH2Q+hNF3TY=,tag:AhzfZMq+9PgGivMKN3IZDg==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OG5hMlo3emtaNE5sTDhx
            Y1RtMkM3eFAwM0FjVEROWVdMNnhFS1pLTm1rCitUSVdZWUFsUFBocG8zNzB1MU9p
            Tk03aWdhZTdKTnBqTUY1aVBtc21DaVEKLS0tIEkvS0tnR0d6ODBvV0I5QVlrMlBP
            ZVlHcTF4ZXF0UUJwMm8xL2JkK1RBQkUKq99/dWt5R4yz+ipRooH7pOkkoxKWUo1s
            /ph65HmWf7vaEEjjyXNH4IIjCmKmAmIjjSeOF0//hCHMkPOHFasPYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T01:20:54Z"
    mac: ENC[AES256_GCM,data:Ot0cmJw4U3otDEwyq4PfjCcJ+pU3edVyvv+EKzXt+uZTSAiJbbuwZhayIykgwC9Pkma4E4cX0sj1MG0VCRFrkjXAxoKqLhAVdTj6OvbaPswwwQPTvx4XLOxO9ZmIyNUnt2FYYqBeYTmnVK4OUsU7XpaPberdjh7OAS41+JmWfN4=,iv:uOx0iOX7FFKz0XJp4j0nmU1z//x0BLGNezUtZ1CQBLM=,tag:3dfWeY7j2X2lhTwoMhjwYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
