victoria-metrics-k8s-stack:
    grafana:
        env:
            POCKET_SECRET: ENC[AES256_GCM,data:x1sgRZyYRNV//uCM9IJf0W1qZQoAv/B3YEh9aS7XB8M=,iv:NpjSJZsrsRfVpBe0dzlXHRFDhCBy9Hy27KZLZ/2284M=,tag:UURpzRK74VLc1op4QnXE1w==,type:str]
        grafana.ini:
            security:
                #ENC[AES256_GCM,data:+vHqXlA+KTrxf0crE2b8FtGYmsI=,iv:vUl9L5jSwpCM0jLfvh8vqTmUf67tyhhiyioAOnGLhco=,tag:Q9frWhLsC3Ycd0AY92TObw==,type:comment]
                disable_initial_admin_creation: ENC[AES256_GCM,data:3S78yQ==,iv:bpnwOmghjew2c/1DfPy7GBytbgFEDdFWcFx5nXU6yIc=,tag:0k5ZHa25FaWloVod+wY9bQ==,type:bool]
            server:
                root_url: ENC[AES256_GCM,data:7w2AkZkJC98Xfxaz0p55xKH0zQ+Oczqe+txa37O8K2qYSQ==,iv:mth0fk00V6wCYdLtaf3UcMtMTMZd9oLdCvdyG8xWUo4=,tag:QleNHJyZFEd6EOJ53EaBOA==,type:str]
            auth:
                disable_login_form: ENC[AES256_GCM,data:VoHpig==,iv:S68ttMBrgH2eNPAhlOU6VOkapBDfW23RjGav9RFKYe4=,tag:GM3uHwWhNy0XrGDi0WAm5A==,type:bool]
            users:
                auto_assign_org_role: ENC[AES256_GCM,data:9bYPpZWq,iv:7NM0xviqHpovUXg0L5qycFXKLlt0qT4Ik9A/slWafTg=,tag:aVCJKPJfqQCFA68RDRC/9Q==,type:str]
                default_theme: ENC[AES256_GCM,data:hlkHLm/h,iv:WmVMQooIN3C6SW8eZG3GKrcHz1bi4X40pX7h/kHklLE=,tag:aavu+CGeK+RANwKKnFNmow==,type:str]
            auth.generic_oauth:
                enabled: ENC[AES256_GCM,data:amTq9g==,iv:vKvqSwSvFOgXmsEBUbU0wciKRjl07StdxU+G4ZB8bQE=,tag:MYg25A9pjGHiwm3RLtrS+w==,type:bool]
                allow_sign_up: ENC[AES256_GCM,data:3fgRog==,iv:j6pHLhYZhy3jXY8JWjsnfz7ErTCXwnWyc8ZAg5qqEyw=,tag:3ef4N+i+yN4gojdUfpm+Fw==,type:bool]
                auto_login: ENC[AES256_GCM,data:NRP6dgw=,iv:1BTTqtdl1RFQsZlE7kXp3+IRKg44SyN6ONX5/BZM4oM=,tag:KHJzB5AsWS4PrHudnmKteQ==,type:bool]
                name: ENC[AES256_GCM,data:sND4hgw9QPZa,iv:ApOXaqrS5wlP1dAD8xrxGUs6MFOtrwuDE+qFTEjjbaI=,tag:SRFRbJOtcG4IG1RpL/We9w==,type:str]
                client_id: ENC[AES256_GCM,data:4d0uRuw2S4/21FPA9Blykrw9t/F23tiX+QnOn605gqHJYI1z,iv:CSk0sfrDt5XhhQA05spcU6eraprhuY59cNuIrMXZMAg=,tag:qra8sv66FvB2Ptp7gQMNpQ==,type:str]
                client_secret: ENC[AES256_GCM,data:QPcUiHSSYrofSz2StwfGxQ==,iv:8R4ObulEVqavc1yuyTp/2nejYihR9Am4BoF2jeQdVmU=,tag:ioXRcVAftVfjs0tRhmNNSA==,type:str]
                scopes: ENC[AES256_GCM,data:33/QnnKTJUc8BPA5jXWVcCBXiW2vGtJQ+F+tA2eH/rbbW6E=,iv:QvX63Sd/fe6H26EBE1dIkRrY6BGG/JGNb8WVrhJWic4=,tag:Qyidl3jAgPoV9ppPO+xOSA==,type:str]
                auth_url: ENC[AES256_GCM,data:M0imwYl/Pb5+6mYt/qHRKQMlYMfFYiT03+GMX3XLE/HJSpubkjNhJGxmhw==,iv:V1Ab0k0pdERNLKuGpqLXsv8mkdy1yvKEBwPncBcck6s=,tag:L32COpRBOdl16C0TEHTeYQ==,type:str]
                token_url: ENC[AES256_GCM,data:O39zT/62MteQDCfse5B/2mkKY3h2qfrutx8TURgn2y1N6Zb+utRjC4TFybawgLDz,iv:d3FeG/iA3VlhNgORqIygBgDkdRzb1HNmsax3lYobtbQ=,tag:6aSKiFIQnEOgYM4c4yi5tQ==,type:str]
                api_url: ENC[AES256_GCM,data:+jx9stJ1dcCEERKsDwb1kzecANgwsbay/jzYsrFCZDcOGLi+wt08odERJcR91PxFUC57,iv:01VzUZf7/OLFlZr/HyW30fmUOpwMpCW/0Dln2qQ9lAg=,tag:W/fCFgEt9nHYrjGedqLXkQ==,type:str]
                use_pkce: ENC[AES256_GCM,data:t21JNg==,iv:a2+6upXBz9D6+piPcTqJUCb5Y1yWZnqVNopmFQCE2to=,tag:oJYW5B9wBxzkvoAeXwJShA==,type:bool]
                use_refresh_token: ENC[AES256_GCM,data:maDG4g==,iv:hVsfTNMzu8Vb/GfNH7xDUYGue454KDLbrpahv2QIqsc=,tag:fsoMvmdpn4peRO3ToPj5JA==,type:bool]
                email_attribute_name: ENC[AES256_GCM,data:epyT8GY=,iv:gVbPy6BT5qXjfV0a1WtV3RjMq0IonMFG2RNI/3v6mQ0=,tag:TpqjVJoVhg/blcaZDGoreA==,type:str]
                signout_redirect_url: ENC[AES256_GCM,data:xTuagep6aREjpN3z9nyMcwR0bIaMO+FMJfcipVxkXqdHcbyGUGGyr4KaRMBNksOqRpmbaMnp,iv:aSFYQwZUsdFgBeo+DByBf6F0Zsi2Zt06DFY0qlgQjd4=,tag:cCpYozovvu8QhJxRMvIwDA==,type:str]
                role_attribute_path: ENC[AES256_GCM,data:cMxe4Pe0Q5jV0CKQvrzJxEV9ZD3rYMDnzjdH+xD2eHewV83bGraqKoK1BO57JYfj5zEI3EO/Dseru1jrCiwYkjp5HptAzTuP5SZo,iv:50EUxfimSKnjoDa4h/d3YjsXteC7oKugsXFYc8ThSaU=,tag:9+oNGh5iuJs5JBFVtfs7tQ==,type:str]
                allow_assign_grafana_admin: ENC[AES256_GCM,data:+5Wh0g==,iv:XENHCCiK+kJAZ8gTHgPDQqzoqssXMLMQxgHbfVw8h/k=,tag:uZ8w7PzFpY23ex4bZ5lxCQ==,type:bool]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOUdhUThXR1l1SXZPb2x2
            ckZNeEtzUTVZaFdpcHFJTk10VmtaV29HV3c4CjhrNGtHZ1l0VTd3RDVJL1hHQnNX
            VStmV1JqTDFLL1BPLzc1b3hqTzFnK2sKLS0tIGZ5b1Q3RDZMOEVwUG9peEgrczcw
            K3k0ZG91aTBiOHduNFNwZGZ3cjAyTzAKYEHYe0KRoatsQOdcctFafzEMBl4Ycpo8
            NKBypYiWATf6R1zDQvJmrIu+2czKwZG7EBi13wpi6esmz+5hjdYkxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T22:02:13Z"
    mac: ENC[AES256_GCM,data:qxEcqZJsoRo5uFTLNnTLQ5bHXhX5byrWLzyP9ruLlXw8xHufH+pyIkbAA/feOYLi1PqLik4JzJsZx0VBRxJF01emrXhZfVGFULgDXyUoOgwufhcPy3KhtQ3BEmmkuMZq5egbdsaYMIwngLrcWDayrOdUe3Bda/BE8XjVfYbhvhI=,iv:SsCIzOG6myzViFy+3Z5E6HuXBia4Zyzbiac2/XAjklg=,tag:4VJ+Fci0n8VjIdeYkv1Kqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
