victoria-metrics-k8s-stack:
    grafana:
        env:
            POCKET_SECRET: ENC[AES256_GCM,data:Bhyk2R2x0sOOi0iN/D2WC9tfPwwVBDbPVsSUx9Debho=,iv:LTPfhoP1krQB5DeF+y51C/I+59hEdoj+3EjQ84LsRm8=,tag:F3TGf8nCzgV1pKJflA3I/Q==,type:str]
        grafana.ini:
            security:
                #ENC[AES256_GCM,data:ZbRHA7OdwmiSHfjh4Og1EUulRzk=,iv:GUHjJtYpkkCrzAQo4StLX5dH5hJyvmj+TugHydpMShs=,tag:NTbe4iqAZKkWJI4JBeWpnA==,type:comment]
                disable_initial_admin_creation: ENC[AES256_GCM,data:6yo1Jw==,iv:qatDmF4XP3wvcPCppeil274Je/rgSxwi+c0kf1dI/I8=,tag:2RXMxUB974lU8B/UBNclIQ==,type:bool]
            server:
                root_url: ENC[AES256_GCM,data:pDUtFkDEKanMomU7Q9EyjHwiQMvqc4SeCrMBrtcSN8pWtQ==,iv:AtQeQZbAuOICXvqKxousLN+yJHqWtYFuayG9ow0xFrE=,tag:KNZDQqjVJqAEKKYMHe0j2g==,type:str]
            auth:
                disable_login_form: ENC[AES256_GCM,data:SQ8WcA==,iv:QAjbcsCwnYmZ2oUyK9fxlXamWyqmTM617lwBVOoMKac=,tag:+474cknjAc1u0Z3jgmVoXQ==,type:bool]
            users:
                auto_assign_org_role: ENC[AES256_GCM,data:dk2U1vcw,iv:c8Qhg1/j5/gnq1MvV9erBXHfjFIQixK0sgK0M5OR07M=,tag:U5l/IuGbw5yOV1NakX63qg==,type:str]
                default_theme: ENC[AES256_GCM,data:S8EWNIq3,iv:984iFwEhw58nAgyzU2E4XmTPHSjSX8ok+0tppJeKc6Q=,tag:SA6IpJgWAkFvUJ/ceV98zQ==,type:str]
            auth.generic_oauth:
                enabled: ENC[AES256_GCM,data:vxa3aw==,iv:FnKY+HT4b6rwKyY/TPyw44BuSoTGaTwakYRJ/D5JkPA=,tag:4QoEmlQssrXqJ35H0aJp2A==,type:bool]
                allow_sign_up: ENC[AES256_GCM,data:yEfGwA==,iv:R4Q+F2E9WRjU/mT6OoVC4bdnHyA1YSBqUHsQMtrOL4U=,tag:gm/YprFcBnBL+91jtOGI2w==,type:bool]
                auto_login: ENC[AES256_GCM,data:qEboZ2w=,iv:3qt3R0eVMJMzUjz9q1X79nycy/cHeZKvobuSebz8qc0=,tag:8GwTHQooDv3ggtXfuN+SYw==,type:bool]
                name: ENC[AES256_GCM,data:S0pbJtdC/A18,iv:ubSEgWgEJn2pOWwSgKAIuC72CXyBJXPLGCNAPxu99Rs=,tag:5KcWu0GVZNvGibKUBUTvbg==,type:str]
                client_id: ENC[AES256_GCM,data:AdmMYptOtIcf2kmI3sqNFjQ/z/ldY7S1qASiuE1eZCwRbSgi,iv:QuKs585zMX3YCnVc7svJPJjXlJoAkMnvsUf5SVZUGFQ=,tag:4Jo7RN73MZL4HrjQPLCXvg==,type:str]
                client_secret: ENC[AES256_GCM,data:lyWei08GdaXAafp62+zMyg==,iv:DwBLz+/rr1rGSuJP5045rY4mv4HrKnAtxHLUIVOAep4=,tag:uX8KrFHgrhlTsrcjGkUQ1g==,type:str]
                scopes: ENC[AES256_GCM,data:h7VN7QARu5gh0lo9th2GbKBnWwdzrBuQXlatrhFUrdE2yKQ=,iv:JrfgSnWOwcv29b/e2znIBSRks0JVBHOUpeKtKwbtwx0=,tag:HHxFLJX7tk/14oiGX98EXQ==,type:str]
                auth_url: ENC[AES256_GCM,data:FliDWMG12DwmcbNwN2UewsnwnMvnwGn6koELLpyzp7rFok4ySNtSfpzt9g==,iv:SRA7nLd4fR9BVHc6jBULH8LoMa15T+nMij+HZ+icXVs=,tag:K4d4DhmkpNhBBtZOPmHCaw==,type:str]
                token_url: ENC[AES256_GCM,data:cOIz1UT3X9gsf3m4zpu97DOFfjZdJRcDpxqqDZiFhWqaJPId1Q6RSqshmEo5A3F3,iv:JjHE/YSb5KvHu9clMYh0/gNoFGFqmdwruB++UmYRMPQ=,tag:TzcDorIHSh0FfbQ1JMusrw==,type:str]
                api_url: ENC[AES256_GCM,data:SeR9SED+FKgVEj2rcCzL0g6xn9I37f6NeojVWiRw38/uPPa8Da/xIq7Z1ybT7/3VbTMF,iv:0C7nqQVpXCSNQGI5/QL2oLmiPMWOjMFQ8FpUWdyiQNc=,tag:J7HTd3SAScmkBC/1qfWSXg==,type:str]
                use_pkce: ENC[AES256_GCM,data:XuNYGw==,iv:uR+BnSi79/RNj49c4c8X0N8zy4CnlCeYjyQPF7GbFhQ=,tag:/D/twLrRv17q+Yb9k8TeVw==,type:bool]
                use_refresh_token: ENC[AES256_GCM,data:y8qZgw==,iv:CvUf/hVooHSiNwjbbKpmM9y8JH6nPvFt4693/EkcyDU=,tag:XqXRMjB2N6OE9WBBNkV30A==,type:bool]
                email_attribute_name: ENC[AES256_GCM,data:y+FZ5LQ=,iv:x9ZhrYhRGW2dZpMH90dQgmr/zorUl+OXpGKVLNkQeNc=,tag:IX7EKlV7yl8UEol61XCnLw==,type:str]
                signout_redirect_url: ENC[AES256_GCM,data:JeVG2QmsGSx4ytAyRbcj4RyehyVkRAOQLy3zGB69ocSGL2rR9c/dl0Z+UupRiJQnbHOCMYNl,iv:SE9q+kfv1f/XaJnNQd/ZW8luuPANsUre3nNg5+UDPHk=,tag:AWuT1l2hzXYXquw2A0ez6w==,type:str]
                role_attribute_path: ENC[AES256_GCM,data:YVfzFLYiebVSs1R8AVOiz2hxwVqBhvKiDaV8Ix08OjvLDQ4ccDVBicsMjsN5y8QI7cjKU/g3rIUGF5sBVYDJm3+ZMEo8RLh5eZS6,iv:IC5kp3eyLW0uA5KEeCPoh8LdTRaPNO5TeUfsL4fycOI=,tag:4EExmIBaUipER36Z2TbF+A==,type:str]
                allow_assign_grafana_admin: ENC[AES256_GCM,data:b7DUQg==,iv:1MzfGwUilmxbEfI9HCfKVJcsOnxDAFugEDBm1BNKTuk=,tag:G7mNXv8XxiKfVR/W19bslw==,type:bool]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSmd0VWVaZzUvVjBIZHZw
            STVqTGdFeVc3eVI3c2pBNVlndFJObzJxajFFCmdsQUovandQaDhEWmpjQkhxTnBJ
            WVRmbERzOWNZaVh0TG50eE9ZdE1TQ0UKLS0tIHdPTmJuNWJ6QnVnRzhOcmsvVnZz
            WkVVZlA0NllEUnJmNlRIYkhtRDBkb0UKctdDt2d6GGkya1oEw+7Nja1JttycnJPl
            2LBZs8TIHI3xY5AdvBtqVlwbQw0SVHnDSAPLXtDIM8VfKEJe6M+jmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T22:20:29Z"
    mac: ENC[AES256_GCM,data:HCVoXU2f+u5gHahjAqOMWzm+j/x5jQG7whjZk/5PC1zZoWqQdNymkGk7jD4DwBhK9cj+rHHxAjdp+duOTIGmZwnTvRnyZMh3AOIn2tLXWi07jhoKh82gv9l559db4vSZxr4eSHqffUfWDwxE5999/LAXl8MF6mp4sYylxwlts4k=,iv:cWL4dX7As8hHGDiLw0B52tkY1huMBuYujJjUFQkBEzI=,tag:ppFDoljBA3bj3jQUXl/CVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
