victoria-metrics-k8s-stack:
    grafana:
        env:
            POCKET_SECRET: ENC[AES256_GCM,data:hNGY43LQKkxJIUFYeJ13uB9A1b8VbgDMZMhfbWlFPQc=,iv:T/omICUxMe8u0e+PoAeBdqvm1300DzOOJBwcv00L/kI=,tag:dBdUkoywaN62rtLEgMQYSw==,type:str]
        grafana.ini:
            security:
                #ENC[AES256_GCM,data:71QO2hOw1VhE3z90QaS7PVj1GDI=,iv:XImSjAnJ0sl+uIosBJhlZZ4Vf/QigVHDwDwJrhzW7T4=,tag:kJfyf7dBxHIltr/fMswZDg==,type:comment]
                disable_initial_admin_creation: ENC[AES256_GCM,data:CGwJGQ==,iv:JqpU4ESf5cYiXRYCLfyPcBeU5+E/n82KYqHOSg06mKw=,tag:x4Vyiiu5PUdWx6Ti27G+0w==,type:bool]
            server:
                root_url: ENC[AES256_GCM,data:RkWRmsB0d710RRT5YcCVurdERDlt9nYz7PsQqJFbNx+Bxg==,iv:LhWqJ4LOqlS/hU6Ti2SgA74HCKjoArUx3QNhsbFW7Jo=,tag:pspFy2Ly+5jHCQxydN5k5A==,type:str]
            auth:
                disable_login_form: ENC[AES256_GCM,data:BbjmYw==,iv:+MRbNDM6SX0TaerwFKGapJqfxzaeP93vca6hHUnkgmg=,tag:kwrD7J+KankPQQYC4DTyUw==,type:bool]
            users:
                auto_assign_org_role: ENC[AES256_GCM,data:7kreUUWE,iv:UKD+R6Vz5O9WDvx1w4TDA4ahYb270peSKRY5G5dK8v0=,tag:JN2tzxzk9rcXrUL6ekMD5A==,type:str]
                default_theme: ENC[AES256_GCM,data:RP1wbo0j,iv:BczVFPFdRfe4e85jaS8GvkA+hJYy9gnX0wSCjfeAwoI=,tag:I6y8mQOVsN4qFoRwoWmteA==,type:str]
            auth.generic_oauth:
                enabled: ENC[AES256_GCM,data:rJOLdw==,iv:BZ575Ax0bCnO08L4kRhXGYglgkhpS0/XkuoMY6I7g5k=,tag:3SIhXMf2ITGheGeRzqE5Rw==,type:bool]
                allow_sign_up: ENC[AES256_GCM,data:pG9Clg==,iv:M7xYJgwtyZ5ppCpPKyzT6IfAQfv6LSiccBqnSj1TKko=,tag:xZtpLkx6XetDRH0Y6b1Cjw==,type:bool]
                auto_login: ENC[AES256_GCM,data:moIJi+Q=,iv:LMTvN9QyG+Y3FXml6WI+5PbMgtykLqOwaUuML4XZSiA=,tag:SoYeO4ZyOT3SExqouZNkow==,type:bool]
                name: ENC[AES256_GCM,data:6plyLFFY5ElK,iv:mf1dHWbOewOE+nRjJiFzFNdXYYId0ZPuMU879Hsh89w=,tag:bfBQ5BnulpKWYdYmhK6f2A==,type:str]
                client_id: ENC[AES256_GCM,data:mF+BuUOp0U/TOyyUH1kNv2M6x8cKg9lCjHBhl7LUHpxzfuyE,iv:ezqcfGp5bU+cMHsmOufCx1dTodkG+dyq8GErSs+T674=,tag:rZJuVVaXwzTxYSd3VX5OWA==,type:str]
                client_secret: ENC[AES256_GCM,data:r+ZF73kDCGCiPALuCg2Hqg==,iv:chZklG2MOnQ8dgas3jHyP+cGNzCPRERk4VfLdAFIDks=,tag:po53FAoboGmTmaTLeG8F4A==,type:str]
                scopes: ENC[AES256_GCM,data:tK/KfRyhgq65KCGw8308E/Jli9Kob34UFAsEBie63fgFG3g=,iv:x7yET2kUl5iWQZKvAqSWVaUYYFwZwKFpsSSL8inQy0w=,tag:dUPQS3KdALJrmv9/y1K+SQ==,type:str]
                auth_url: ENC[AES256_GCM,data:TNHfDOmh9RTAvVlQU7ygvUCBpA4scejJuw30qDbfd5VnFW0qnFwkKTd5,iv:UVBwb7spx763T7axHuQ73UXjMKIH9gp2BY9qwsTjAQs=,tag:R9v1KjZ9Mx1UbKthlZqIPw==,type:str]
                token_url: ENC[AES256_GCM,data:c9J6uI9pN1fTisJRE6DMFzdJqM7FxYwz+/QdukpH1yoXGq+L4SUuptkuau1zSa4=,iv:4Gxj4mg9ARttnSHNmWPr77Eix3XpGiGImYWXT09fzNM=,tag:kAnLhoBsIo2mMhl2RdUoww==,type:str]
                api_url: ENC[AES256_GCM,data:x+frLosM+hm+o+f9OKPVap/iVtdvYMttUBZqwEklrQwiFYPR23o4v1/kaTQn4d7CHus=,iv:hsGyuzadCtwNgGcd7NiExwC3O1HwRJ0D8104V4fUf0w=,tag:hvCQhY7vPxkgEnx06KVc5Q==,type:str]
                use_pkce: ENC[AES256_GCM,data:lK2vtg==,iv:JwZh95ZFDHQ5LhAHQ0kezCKBisVh0KXiGf8ceR91H+w=,tag:klaOLhRha3ihfZ+CMfJTew==,type:bool]
                use_refresh_token: ENC[AES256_GCM,data:Z8QbWA==,iv:TRgEBwiaD4scpuaIJTkcaR7FcGW8udfBZ6j1DSteKZs=,tag:HZUWT2o0qXp0BbIhsRz6kA==,type:bool]
                email_attribute_name: ENC[AES256_GCM,data:/ELVmjI=,iv:Rg+lsizQ/+vwkWcComIsQdrmiXYobjTrI21Y7KoNFe0=,tag:VZ5Z4QLdZDrV70C6jzKOoQ==,type:str]
                signout_redirect_url: ENC[AES256_GCM,data:La3Mpl1f5XZC+HucuFIKuicDif77RhtjYilypO+o1f0wTqSmuUBd7OtKmbTIUmK4723EDDE=,iv:xAo+yz75rELir6Cm4nhKll5PYjg/nvmX2MqgD+9/eGY=,tag:pYiKtbKPYFh6CvJ4HktxgA==,type:str]
                role_attribute_path: ENC[AES256_GCM,data:yWolQX/+MeWADpFAZxhBAqQXyDCJGdTtekRSSFQd/ACPZnysVWusoJWlbj3yQ76VAxSQ1Lg6IfOuf0bXYGKjYs+PFH3AhwRjV+Jf,iv:HhfgJB4aCV173wkxjvOBaCEvu7kivkKmvN2yfFfIFy4=,tag:rlS+O8avAKXUc9WtOX9eqg==,type:str]
                allow_assign_grafana_admin: ENC[AES256_GCM,data:aScTaw==,iv:4VIv/M7bDgONtNU8UKjvSwjPvO1zCVc/8k6Ka+Bwgwk=,tag:WrQwkN6Z8+q4QWvDvMsVRg==,type:bool]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb09lb2hyRXFEYXM3ZXly
            TmJlSkxQREo2RHNZaTRCRitsbnRUWTFUNkVRClMvQ3JFRUZ1c3ZCcUhJUFpRbFMz
            M1hRZGpGeDVuK1B0b0ZpS3VQR2RRL1UKLS0tIGxYbU56aFE5ZVhiaEdlRTAxOTFo
            SDN5M2huV0F5ZkxKMDJmcTJhckZaYzAKyq2QlWM06aV3jCqZ4sDndj0zs4pdoPYG
            EQXUjd9s72dvEiWbX1oTTQFXsxZfwLONOB622FAKt3vcE/NhOO0stg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T22:05:49Z"
    mac: ENC[AES256_GCM,data:3zA0gXyz4E4HBZpuUGf0rg+it9EnyeeB1fmFQb68Oq8PbOtLNUVvfg9VXteWW0uveZlN3f3eDm6gHhb51P/vERjhjqU/R6PVcHgL4wPLWZ59u0kOg9dPWAdcjx9TGPFSoiFXUdb5TJmBIYHGsn0zIusPCJPPV4SQ85+hf4ufVPw=,iv:UfLZGg1CZrx3IPKpfdnR/dKRfds4hvpT/88qrVFv5ME=,tag:cNY3Y85+60DZX2987OKNXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
