apiVersion: ENC[AES256_GCM,data:YuM=,iv:cOYmAMPD0SvI1Ra4zSsupPtAEBJhP0wAMFU1W0ZolrI=,tag:LfxgkwhIJxQ9GpoqOeTQ8g==,type:str]
kind: ENC[AES256_GCM,data:2JZq6DSM,iv:lt+NVamJk/tE0CUq5LFsDT/uy3s4lOp1JrzqEkPVqX8=,tag:rg0vYmabYqyZ3iXYeIvqWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LXECMFoFvGdRA4cEMlv47r1p914=,iv:4EGDRS6kMuqEp5idvYTbKBFSRFYUs2VtOMLCZDu5PYg=,tag:7ZC+4hpDj5v116zQq5z23g==,type:str]
    namespace: ENC[AES256_GCM,data:1lkV+tT133Mu4voJ,iv:097ZKkokhlsFopJnDSC89N1H4fU1O2WqjtgCwpJ8jhU=,tag:apwyJKghmwpvPMfJq8kkTQ==,type:str]
type: ENC[AES256_GCM,data:RsZpk5pV,iv:tGlgEhPJGQb8brNBS7VU4eShgi1oGgyoMecerzV0DJE=,tag:7hqRs+1X2pKuVmzlDx0zyw==,type:str]
stringData:
    api-token: null
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMWZaSGdidzFpWEk5L2VY
            RXIwNGozN3I4ZTE3cVpPSkFPQ2k0YTVyTEUwCnkrNGk0T2hzdFQ4NklJc01vY1hF
            MzgxSE1GM0pqUnVORFZwZlhWWGFMNEUKLS0tIGtWazhpekczRVpqYlB0aEZkTXcz
            c3owZ28wM0RGZDB1Z0tpb3hjTGtSQmMKGE8CA5j2b0ZR2nOl0hE4Fd8Sn96H52eT
            x0eFSx03KCnEIXnXrXIQa5d2c2as/cOczDFLFAJOg5o1sAMcI/iJ2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T13:30:02Z"
    mac: ENC[AES256_GCM,data:ypGRCzbPWTKu4KuC82ERraGtiUb1mxu25hdAdupd7YBr84nDtUUX2eT8gvAHXE3Z/mEWJA7VXs5f1rGNE4hUpUmLzc6DZPnH/OzBYq5Ctq2RUL23ZGtE+ICSvPAf4+ApkATEYS2Rdu7b2WUV/mHrHCdmGO9b188uGS9rgDhAQzE=,iv:JmA86pi/w8p8fxo5ixUmdoRGJE8EEudZvAOdXCDSax0=,tag:yUrzUWDqUcE8gt1+oHPx4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:T1U=,iv:Hbevu6rWkcSXse7wus69T0orsDkq4RUB8V2OdHxgweU=,tag:RhUzeNfHX8mySeE01X/A+g==,type:str]
kind: ENC[AES256_GCM,data:Vv8UTzNw,iv:zj/lLnBv5hr2xk7ykDQuQjNs9/NbZBm2+bvZylYJq0k=,tag:JAkk3bMy0EgdLxybWGeEsA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iNafLPQEu3o=,iv:BAUhPpyllkbv6PWIevCpR9OAGBsHvLcGyd+pjj4sGdI=,tag:Ax1VpJRiAf+eQ8u7zjHqXw==,type:str]
    namespace: ENC[AES256_GCM,data:XSLalAg1,iv:iJtiyM4Ue5svqEBBvU4erEyRPIMteBA+GPSP0nuhApw=,tag:bVN5HnEZG4Qpf/SVoZoGMw==,type:str]
type: ENC[AES256_GCM,data:dYFm1yZ3,iv:tpAYDF/MSOIdFPVM+nLygIS3QH/Do2Ap0x8vDWYK4Bc=,tag:Yq+NpCjcU2wZRAOcVOupKQ==,type:str]
stringData:
    keys.txt: ENC[AES256_GCM,data:ZtDnYAgWE0Q9iTSjsSn0QwSEkrSTXqMpqw==,iv:jN+G3Q8/pDUo4SKWv2yTGMjSsl1u9dt2TyM8EJE0kSM=,tag:GP4P+6UxPQkNWWd4tACc7w==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMWZaSGdidzFpWEk5L2VY
            RXIwNGozN3I4ZTE3cVpPSkFPQ2k0YTVyTEUwCnkrNGk0T2hzdFQ4NklJc01vY1hF
            MzgxSE1GM0pqUnVORFZwZlhWWGFMNEUKLS0tIGtWazhpekczRVpqYlB0aEZkTXcz
            c3owZ28wM0RGZDB1Z0tpb3hjTGtSQmMKGE8CA5j2b0ZR2nOl0hE4Fd8Sn96H52eT
            x0eFSx03KCnEIXnXrXIQa5d2c2as/cOczDFLFAJOg5o1sAMcI/iJ2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T13:30:02Z"
    mac: ENC[AES256_GCM,data:ypGRCzbPWTKu4KuC82ERraGtiUb1mxu25hdAdupd7YBr84nDtUUX2eT8gvAHXE3Z/mEWJA7VXs5f1rGNE4hUpUmLzc6DZPnH/OzBYq5Ctq2RUL23ZGtE+ICSvPAf4+ApkATEYS2Rdu7b2WUV/mHrHCdmGO9b188uGS9rgDhAQzE=,iv:JmA86pi/w8p8fxo5ixUmdoRGJE8EEudZvAOdXCDSax0=,tag:yUrzUWDqUcE8gt1+oHPx4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
