app-template:
    controllers:
        pocket-id:
            containers:
                pocket-id:
                    env:
                        APP_URL: ENC[AES256_GCM,data:v17YDy7OXRGIE5F8FDXkUEIJSmbF/ZXKDSUQDGnL0vuy,iv:s2ix/4HFo1e73wy5rlpsXUE2PvbG0PRQ60MbRUgqnsw=,tag:+SDd3KFI2+ScVdtJsDYSGA==,type:str]
                        TRUST_PROXY: ENC[AES256_GCM,data:aupaSw==,iv:t0iSK31bYnbe6PWod+UhxUugvy+8i7gjJfFYdFSomUw=,tag:scae5haQcz3suHH5v3BLtA==,type:str]
                        MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:3Co4e1O4tcFNC27jLIXHiACYptboT9YPRjgWMTYmW6XcyYdelk9+gA==,iv:27OEbf5eTM05Zz+kHuMvC2iJ5KonBCrmAe67MNzRAHA=,tag:p9K8Hmy91K+bz8bOqUItzQ==,type:str]
                        PUID: ENC[AES256_GCM,data:0RgCeg==,iv:sGxcgUT+PXzxvJn5H/QkM+BuvZZgyCrb+WsYLcJgR3g=,tag:jERC8cyxkEJfsrduKC3B0A==,type:str]
                        PGID: ENC[AES256_GCM,data:afP7Rg==,iv:QyLLA4MBj6fEV9tyNhHIdfrHUfJJlG7y4f9vE72f1p4=,tag:4TKZBRQk9tUYzDi2U6bD+w==,type:str]
                        DB_PROVIDER: ENC[AES256_GCM,data:1/zRSBRd/RE=,iv:7LcmAtg5DbVG5DUaRi13GxxwuyH0xuDRE3JjVbdytmc=,tag:5HwWFxUSgM6mYlkJhWZ0jw==,type:str]
                        DB_CONNECTION_STRING: ENC[AES256_GCM,data:FlzLfNQOReMYrRGgUSharQXwITTWUd+XQx8osJ1gfzdN/qsrn+1NyWpWFcqc8cF2yA92cqEw4xUe2ZnBxY/c0lvv00AT2HMZ+GasGeQwjV9E/6PGQQ==,iv:/ObNv+oC5O2Eb/D6M4fQQcXlqf213Spu/ds9Pnx6BeY=,tag:LBiYKj07B0bfuvRm6tSIWQ==,type:str]
                        ENCRYPTION_KEY: ENC[AES256_GCM,data:rOwZtPfMt5BA1ltJKb0fwwNQECBiDTAau+PdT0MqeOR1M5AKvvW66WvP7As=,iv:qEFtK76d8JX4IfwlBezYFsz8KFZ21STvNNYQ4tNvFD4=,tag:m718z2/LcvSnTNDFJ8JN4w==,type:str]
                        UI_CONFIG_DISABLED: ENC[AES256_GCM,data:kTZlwg==,iv:Vs4qE6P2zLc8FxlBX3yf0OtjaGar2SqNog9oMQrQ57g=,tag:p6vGPp1wzR5aAdqVg+0hPg==,type:str]
                        ALLOW_USER_SIGNUPS: ENC[AES256_GCM,data:q3bs56Zx/F0=,iv:htuf8gQSOccNctOfSHmYzBJLJlKRJISVl/cih0thNvg=,tag:vyKbS7BW5AIhoH3R3PK65Q==,type:str]
                        SMTP_HOST: ENC[AES256_GCM,data:B8Et/Ocnkn44HYOW0Sk=,iv:gdK3GZmRwDoWr8CpKlQYH4N/Eh1DMbIfRMeT5jXw5xc=,tag:JMMuKPka7cMRdkB0lPCjWQ==,type:str]
                        SMTP_PORT: ENC[AES256_GCM,data:bj5S,iv:e361NxaCCbI3U1jpvd39tPERPNsG2Vqs++T49mnLepU=,tag:N+fi4B3EAKLfhKDJF7367g==,type:str]
                        SMTP_FROM: ENC[AES256_GCM,data:4tDizkWQ7KuhyLj7i1hZdPU=,iv:PZ2B1zanDq2FTklVqo8V/hyhPuzXwEzpZIpbRO3S7AY=,tag:hN2/c2cTr6Q7VT3aJCrFaA==,type:str]
                        SMTP_USER: ENC[AES256_GCM,data:hHEX6sAeqpCzlK+wQHQB9osKDJFGn02VgCc=,iv:1BC8CTX8z2oHCyT4VwJQ6jPQT01JKz0hQexOy00k49c=,tag:QdCVYpddc4Cft6ql4DZIGw==,type:str]
                        SMTP_PASSWORD: ENC[AES256_GCM,data:u2bTXx2GYykwA7jsDg012w==,iv:EtTUqtOxrlrCw6bdY2ZgbFiCj2OpLx5RRWcF5W5hDNM=,tag:5c1bRWADTwRtKnoze7zDBg==,type:str]
                        SMTP_TLS: ENC[AES256_GCM,data:BRh2nac5K5Q=,iv:npS8kzoHZOq7DAc1Y5a3yyiKq0zW0QXT6jX1AMyo6yU=,tag:HRJ7s1cQnOUbV8Qh12/rxQ==,type:str]
                        EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED: ENC[AES256_GCM,data:X1nIxQ==,iv:A0jPZqMu2STXv62H+fIbeQxz8TT9DvtgCSdte0fo+bc=,tag:psmepqpu/O135aL/6lMIkw==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:UfmGN3N2H32USmxj5wS95RUZ5MhYr+nXG/CMkwAarBI=,iv:n0BaoDgeF/2Yqr8IvDMBRfHUO5mP8cvUBfTHK9tJlRU=,tag:mLXcNROAQZqp0VlfAtZeGg==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:39V51yMW4Ig=,iv:EDn5AR8rVHvv7L1CvO+t3PHUDcUr1GoMyFZ9gPfJDG4=,tag:lNOb17ww1r4veV+L0ZSAhg==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:iTB6PgF/xJY=,iv:xW/HSDfFK91g4bBzI2REGT9L0WIiRSvOWs9XuNzNj/E=,tag:FQy5joF7QO70ecRBEl8E0A==,type:str]
                        PGDATA: ENC[AES256_GCM,data:XueFbRKoasjWpLn1l4BivLmuhk5sNFVyi1iYwf9f5Ps=,iv:PC32yoXnV1Mr77KCZL0vmswgGjh4l2XRt4QyjLsjV6Y=,tag:YXm03PzDc8+nXVn5bsb4GQ==,type:str]
    ingress:
        pocket-id:
            enabled: ENC[AES256_GCM,data:Xaok3w==,iv:8seYam0HnfceQeJg7YaIfsthzE0iJt9BJTSx0H6mvkc=,tag:OVX9F3rscsnpzBQ4pYsEyw==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:V3FpLL8QFG35Y7T8sRDY3w==,iv:x+mBJ5ZrxR1hwbViXNyAgDadulvJghFRlO3EXmSoF8o=,tag:tednawI+BTkNUdqUj4abwA==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:st6+QQ==,iv:O93UV5qIsxCwNvZsF56FGF745vw6BG0zldKwpbQqByA=,tag:h9oj4/dLwf3kKqPGbEoclw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:EqJrjpO9Ec5T,iv:xjleUo/EWLfYq5V8/iUBNFFWxwUWdJZPudM47fKV5cA=,tag:hqSgCffuM3g83GTQ0G7CCw==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:e6GiJL1KQVa93tNmzQ==,iv:0hkJ2/oqXYGrUskmkhu8WVxANaERiPPSfzF+lJhK24k=,tag:yFh46OSB7G8XwDsaJ+XTaQ==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:waUCIxrq,iv:Ei6O2pbyQZDWFdKLyRGrkOYwYz3CW9MrrbPgaqfTEzs=,tag:/W4zjas1p2rsmGWfKQ6JYg==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:0C+flrAW8mPwgcZA6aixHQ==,iv:/K+piZMnXUm+YVjZ+6ua7wPSjC4tk55eoPC1ZdLd0iU=,tag:Syd/DwcwTvkkUxWaU1zVtA==,type:str]
                nginx.ingress.kubernetes.io/proxy-body-size: ENC[AES256_GCM,data:VE+g,iv:7PPEse5oXJ4kRm4/tlfGg/hQO72dRyEbNm4yDsAM9XQ=,tag:WCmDdvUWCUQodOYFK9M4Dg==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:sro1HZ54F8ADZLMu+L1ulfWiRoTZdb+MIw==,iv:nfZKa+ptT5b6cGCb9lbgVkk5ZqTbtwq4mlAihS/zojE=,tag:zOtr4F4YNc/3iUMYO/S0Ug==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:SQ==,iv:oliRbr/XjCGPKxsB1j7pCPQxm5dWRQxWT28L7LEeXmU=,tag:AyxDdEQQQdNSF+RofkEcyg==,type:str]
                      pathType: ENC[AES256_GCM,data:4JV0RaGl,iv:HPVWSrMkA+pHDhU3JR9EQQUQPK644pgMH+9T5xbuq3A=,tag:aUKzC+iaW9W3JD79YCOKZA==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:WCM5i/xRubag,iv:Wx5Nns7xqNWJbRuSfVG88qqWCGeOrmDz1DO+uALtbEU=,tag:VPByP5jRlsyNQ8YTr3vP3A==,type:str]
                        port: ENC[AES256_GCM,data:hSwHDQ==,iv:dMp1r6m4FB73xa+SwD4PUsHTlsiMQllgDCoXVPgNxoI=,tag:0nNoG8YW7ARgAE+aW3lAiw==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:vzwaElRIYyCVblziGzal9/Q5,iv:63R5zIZ9Npt3OFg+FlEMKhzo53t0SshmxFHxlknyxik=,tag:eITPPoE90cW5AU24R2DM8w==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:meBtlbA/nBc9EqPAKB5Bk0169oftVhxQxw==,iv:PvPxiEy6wSzjGqwYPHEsq1HMH179eVOFgbfp3Ruv1Nc=,tag:Bcq0b8/YWlIJ10+AL3MzQw==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqT0Rnb2pJZzlOM0F3WVVI
            dzhraWFXeTRMT3IwaDU3V2x4c09yREJXb25RCjJhaVhQWDRCSzFmUFpSQzB1dHZx
            eTlSMFREMXlqNGd3V01RY2tCMHhUaHMKLS0tIFMxbFl2TXpqZUxsalc2QW5WVFV5
            bFFDdTRzOG5uWlE0YzJzOFVFSzVqZDgKTh0b0UUKpULyU1bpHL1bj/UdlzDm+s9B
            qI7k6a2tQkSaUpeJAnqfZkfiirskdsun5GNjEtkpMcnJT0Xwg4qADA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T22:20:29Z"
    mac: ENC[AES256_GCM,data:8lnI/+FAgffhzGK29QZ2SOvUdnzHhdyjwe1lBWMrnq45oQSrtxn1ppbzx2nAEJkILlLFn6y1HbICRi4gLd5pdDLIP0Vp+AwtJPEa4EQV4RVHK3EQCCmLLa4kAnOMovoI/ziHXYUUsF9i3xyf/uSc06X91Wt+HkgTIy70AXNRplY=,iv:qOLsw0G8x0chloWbZ1MHacJ9YTLRwC9232MJHxmXX50=,tag:udTiblMMLTTzoR3eSwCeLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
