app-template:
    controllers:
        pocket-id:
            containers:
                pocket-id:
                    env:
                        APP_URL: ENC[AES256_GCM,data:nmQoprH37ut/Po6he/zAf0DoXr2KOElJeKd5U1Yv78sp,iv:zgDxUjUaT06Gp/4PtnmcLgNWgATL0/DlVX+j/JNL/a8=,tag:05octsEnSpaDM1KWPwsuCw==,type:str]
                        TRUST_PROXY: ENC[AES256_GCM,data:TPqP4A==,iv:vh7lTRAki0d3Jkue0MSyJHyim6huYRJvDXDlt/kTgaM=,tag:E5VbLkfEOWkSOB9PWmgJIw==,type:str]
                        MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:KuhJTXgnsIs9JeC4I1GmNXrtddYPJ4PZUNiF8tmMaynQcbr/r5i9iA==,iv:bso1oruWSekk4b8YrxpU9S3qWkoxRNi1ApvFNs6DKow=,tag:WwoGCdIgm6q9k9KP5RDkJA==,type:str]
                        PUID: ENC[AES256_GCM,data:m4NV6Q==,iv:k4MMRU28NqS3v8xVx7igi+ETSTEmmKuLF7GJIV5Uuv4=,tag:J1eze0Y+rpPFATMrOjqTbA==,type:str]
                        PGID: ENC[AES256_GCM,data:WEbJnQ==,iv:0XyPWqzvO+STtXWaUuLRFy5ky8yjeg4Yml8vRf8O0qs=,tag:509F5g9Rs8SNTw+cIG8Pqg==,type:str]
                        DB_PROVIDER: ENC[AES256_GCM,data:R8r7Ss8Lbqk=,iv:yvPDxozq0wjn83w1ATcbz9WMkCxIiEQPTnXJ+ory0OA=,tag:lJmNdq8IuLIQ32hB+ed6DQ==,type:str]
                        DB_CONNECTION_STRING: ENC[AES256_GCM,data:HVwbozxYckcqI9MYcD3x4jALdieeVluK0Odol2liH0nEVze83ssJXqxBcZ1Ao7u1Tp9o5tBvrBl7otKmEIKRZ5zHitq3WABnqSEX3x21DNEkS3n5ew==,iv:Ucz1NZqVlY+0DdvUW0XMyuLBNyPE7CP3ILrs4dbEXag=,tag:JcXV8DB8GdIza9E+uPayGg==,type:str]
                        ENCRYPTION_KEY: ENC[AES256_GCM,data:ch80KkkK0oakStF0M/c6h09a5kFPMYHGsppQVdlOw6x3L+pYKSzVWBibxis=,iv:FdPQhtVhpSrFR9kDYKlJ6veWVfH5motoJqoBDANPsvc=,tag:SbF6NvYcU61x3hAAyTe17Q==,type:str]
                        UI_CONFIG_DISABLED: ENC[AES256_GCM,data:elP6qA==,iv:SPjNoS2iSDMMxUIqoEVeXT2T5uF/pAqcOGGcBP9TvZI=,tag:iPWS/8gZL835dpAAPQyB6w==,type:str]
                        ALLOW_USER_SIGNUPS: ENC[AES256_GCM,data:EwAC8lKZ278=,iv:tQHHIPwjKFxS3fR3AxJu2nDx4hSMzQvpodmXQxNXm5w=,tag:JLNh6wS4CUHxJe5SHXM26w==,type:str]
                        SMTP_HOST: ENC[AES256_GCM,data:TzFoq9nZkaoa2X104Sc=,iv:tqzLhP5OdJn+Y3WlRt+6KElWI3UJiaKibTVAuZNAE5o=,tag:ZgcjNhY35omLjlmo/aB1BQ==,type:str]
                        SMTP_PORT: ENC[AES256_GCM,data:tnFv,iv:d0gFoRmY4rnUYv4/K8JLRG0c7DSOJhECGtafUq+EsN4=,tag:xVGjJTJoJc/RjmpkYm/CYQ==,type:str]
                        SMTP_FROM: ENC[AES256_GCM,data:aqgBJd4j84lcO1Zz+0RoMf4=,iv:tFkbp7zGi8fziSIZuYLScZyXt8xGFTJAmdi2ZntT3jE=,tag:XBf355xpup48CM/JiIgTxA==,type:str]
                        SMTP_USER: ENC[AES256_GCM,data:PdlsEnCiv1uf70QFmsdc33pkssvhisIrGDo=,iv:NafC0QiG0d/56M6Z05lni4wqwOccl+DiRcJPnmKMR3o=,tag:2HCFVRC/1IcgKnUZGgNp2w==,type:str]
                        SMTP_PASSWORD: ENC[AES256_GCM,data:uv+EL75O6zVt+9VqVKVZlg==,iv:QEpxnZbv+mVH2EotTp4aQQERIbM8rEfGeDrbIeEaXwM=,tag:gUT0IOFJfhIr+7h4z9M0kw==,type:str]
                        SMTP_TLS: ENC[AES256_GCM,data:682dlaj09bY=,iv:HGpaq9ZNlcUbvOFsMh06K10w2qZEimetZEx66f4PWsU=,tag:/c9n5AMrTOIf1Gf28hSlyg==,type:str]
                        EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED: ENC[AES256_GCM,data:oLyLIQ==,iv:4KV6D4bjd2ysfNgaF1oysRCy3lUsFmWgUAjyLbezl6U=,tag:bwOR88nWbcjWfgr5Wi3SJw==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:kV0WAKSMe1kBYe/VAota52/Gxd5Ec4qZ6MY9zNSEarI=,iv:GFIa8kCTHuSEsw9dRdfakrOWY2xWT1xvyVcl+GEWa3g=,tag:nDO3YVgpWTzYKZm2xRsjYQ==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:YE9kgdKE0sk=,iv:CfpKojNi+sSkU0CYgg8T7vLuxn+HmfOg0/LKXO3uILw=,tag:r9DnqaoWCw4EMuunw2Q1dw==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:BUfoSo5N7Bw=,iv:vmx2pVkLzZxM55cjEFK5omJiZQ3QSTGs9aIplkZrKSg=,tag:1Y455zO01w/5kNNmDp3b8Q==,type:str]
                        PGDATA: ENC[AES256_GCM,data:Ix0yBRVAiQTQbNSF4XGufsf2WbQzQIiPWvgNPT6CHxg=,iv:cqLqRSNHA+cTm+A1OdzfCp9BXwAhjSn/pOb18MCOXR4=,tag:7DseVB+jbeP3C5cxQYXQ3g==,type:str]
    ingress:
        pocket-id:
            enabled: ENC[AES256_GCM,data:ozXUYg==,iv:YLqlr2CpToG0oqgbYkRHYL0NvABe9/hPvmGE1nykHfA=,tag:XZ6VcTSuc4jQTzvDvB6OKw==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:Lu3U4UXAiD3brP8udz6X0w==,iv:fOy5vEy5TnOA1eXMXMCI+UQqrO2Sx7mWObRZlezaVIU=,tag:M6xYBlN97SfjDPXgGl8mCA==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:cEfpHw==,iv:JVLh5tXlK+uIuzkesuk3dl2U25SvIDsj/PDqsicnoQI=,tag:Gf+A1c8nYiC8xlAHExH2Qw==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:+tN27PKBlYQP,iv:JrGOkX7NDzytX/mUcq0kox8+XNyFh/rMR2G0KrQTTRs=,tag:oWY4V7lE7aZ3xYnFrmCNJQ==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:WhPJWlIMzjFxHo8NQA==,iv:PoFYsHqH/8DWgxAT9O7teEZ0yJbL2oMikVL86B9X+Bw=,tag:TQJfhviZtaEKQQypHeAU1A==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:vGN3jtwR,iv:4EmL4Tp3S+qmY04Kwh/49b6AYLDupNgNrdVTyYZKZxg=,tag:pbpEdDoFYmmOnjAXjIn5IA==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:4IQPNypApynmctzgLfZpvA==,iv:HSkTYRXUqg8q6HCZCb9lAakNfifVgcIk2OvOT9LBAs4=,tag:TwWM3NGlE2m3PY0iS+JE3A==,type:str]
                nginx.ingress.kubernetes.io/proxy-body-size: ENC[AES256_GCM,data:Cy/Y,iv:3VAxoidFVIz3bdUTOIILugc39/i905SL9vfCzRUokcU=,tag:PMqjkdpA0pMwO1qpJq4r8A==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:09g2cCzfWf2Tz3ppfaQdTmgK8zMTaErCmQ==,iv:7dLFhm+AqHEAJ128dnR7xO3Y9F55DzwzSHCWxCkEFNw=,tag:W99wF6S8/+vqrRA7r5Cg/A==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:yQ==,iv:v5E8imROdwCU90ec67WkOVxq+fwqbx3T1GlYJIgG2P4=,tag:RL6zi+JFv+/MlODYIWx7LA==,type:str]
                      pathType: ENC[AES256_GCM,data:u5naBWTq,iv:D01fYaCnwkf15h8/LIrpE3zO3kNGIhLm9RhjpMECYMI=,tag:NeOsBy4AKUG8D+xPPUphlw==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:ghAWFIAbg7mn,iv:dDOKQzGmakXL+YCPnTdQGjrBbUK0mIN+/gEk1mexFtY=,tag:vZVlRbDXcnSWREKJkJlLiQ==,type:str]
                        port: ENC[AES256_GCM,data:o3Tp9w==,iv:3iYxQf5tabcjW+xHLrisGePL+Aivyfyji5QA8t5KJRQ=,tag:G1D6YCPIG/DApyxrsyconA==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:zz7UW1/DCfPse1YM3Hgug5BT,iv:eb9vEOdz3RhhRXlyrtDhBKYs4Y6Gj16+W+ztegtMIqA=,tag:xZ17ltqjZyNkpqJs4La3Pw==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:ZjAwHf9mzVJpLm+wUNbXVszHjlnm0DuHgw==,iv:MvjzWfW5CcnSgSEoeK0m+rJs0K0Cl+ip83/+crGjGts=,tag:oYb54C60pCfZ8tdB5TSizA==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNUNwN0dJa1Q3WEN6eFFz
            VmQ1K0hOb3VGU2YyUVh6Rk9ZeENWczhsbEdZClBwNTBGUWJST2JKdyt1OEVKVXB3
            WVNCN1hYOTFWNit2SWVydG9zdWliVzgKLS0tIFlSbTZBVCtUMllVd2c5RmorR0FM
            QlE2RnkwbUZXajJKMHNZQm15QkJraVUKetd67+eorEmVOdxt0o17zE0fGrzm58uM
            2SqEGIUtLOniHLtLn4akZByBW1fPwFh0kZr8RL6EbXwWzpAQXxjQWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T20:25:41Z"
    mac: ENC[AES256_GCM,data:cCDQmn8ugFi7AaZWosy//AbMr6OVp33GP+tPhTT4KP2eYMfjvUwRVTjqLkJYvQ0zLh7NeegHKlOGA1GcJ3xxk97cYTrPnStFAK0YGyDGqWqZ8Z21zNJxYJe9H/Zrh+L8jIqhpJMjGLrtxFrkcXE2FOJPPWVebPcosjc4MPNOvc4=,iv:5EtAiZYKfoOxEkKWgSYI6qOm1LSUyGIFYrHUZ1AD18o=,tag:SwvGF8hats3NTo+tCXBFkw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
