app-template:
    controllers:
        pocket-id:
            containers:
                pocket-id:
                    env:
                        APP_URL: ENC[AES256_GCM,data:fX0WFXU4/f/tILEURks4st9uVe8Zpc0ONVL4MrXHXi7M,iv:om2HnuI+rdkMK7XzPBIxqVjoQgh5wXS/DOOJAfq/YiA=,tag:79qGhrhVvCphTJfREp99mA==,type:str]
                        TRUST_PROXY: ENC[AES256_GCM,data:g5fCjw==,iv:AkZflsA/p2xNdZoRqunONzM+6CYvCHyPxhDWY3As3cc=,tag:5JXtR1O9HrMxtc43SNzsUQ==,type:str]
                        MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:WKZgOnjr+EpsvZuIbR2stNkA8fWvaMZyJ2hXp61hfe3iSrl7BsgC7w==,iv:TeIOIRJ9cz1a3W/YnzHkRBRe2KVjLDmHk4zbNFWVTGQ=,tag:gt6rUV+9djYNm6q9OaXG0A==,type:str]
                        PUID: ENC[AES256_GCM,data:AFcnyQ==,iv:BoFCbBJgqrnvLs+xlLwHbn4mEuU7ONK1nUFL4Z6KBrY=,tag:gyO8DOq40PtGrJI4kVeAYA==,type:str]
                        PGID: ENC[AES256_GCM,data:Op93NA==,iv:oSJBema4KjnLijSXAPXN4pmd+B97f4mGpqayd5CaSPw=,tag:od9nRk6v1KILIMo8atL78Q==,type:str]
                        DB_PROVIDER: ENC[AES256_GCM,data:+FIHXTodvvE=,iv:cA3Hs475FgQxcX8Q+b+d68IJz8MsyBdcrB0JEZ+hi5A=,tag:qjWokrgPylBA8jYRoxjHvA==,type:str]
                        DB_CONNECTION_STRING: ENC[AES256_GCM,data:SKb8M0/5iBvlGnOgtKaPZ71+O8s73zsE9vrdNzv3r5TcIkUZbyLt95xEY0Iimjj2ol5Y7HIinzHKzQNdT0UwM51GLlCxr2qyfhXu3UA82g3j5jdAXg==,iv:f+0WzkMpDPzfppozf+c4UlgDjrkUPQkNaxLftb/HMHs=,tag:2dvNfeF1AV6wK3WSzPA6mg==,type:str]
                        ENCRYPTION_KEY: ENC[AES256_GCM,data:HlVRvUVDmIu02CxQqpjVk489K4pkPmxbkY6Js/b9TWPVlYUAxz2UMOxMF88=,iv:DOptMNLtPKvBkZ4KQG0n9jYlQEC9Qb7KArr2zNmQXiw=,tag:vj8gyqNp3xmGlzIocW271w==,type:str]
                        UI_CONFIG_DISABLED: ENC[AES256_GCM,data:2lYMNA==,iv:JxWoavr6BSg+RiTvA6Q1wqzedEfujuIQgIumP3kNEAQ=,tag:Lx0/7RHCZceSU0O40pSNEw==,type:str]
                        ALLOW_USER_SIGNUPS: ENC[AES256_GCM,data:2a8eGcqFe7w=,iv:7lX/a3JnZ71YOWvxqDFLHXxkMhmKs+uv6EtJJoakAy4=,tag:jZ7V6nrYazBLm7DjsaVUnQ==,type:str]
                        SMTP_HOST: ENC[AES256_GCM,data:9HLlS86yv8nE4dTxv5w=,iv:YFt/AVrZBtDVDKniXxjXF6tj4HA/gkSNCeHpwUWBKcI=,tag:iLP6SJ+pu+Ks2ykaO9mGqQ==,type:str]
                        SMTP_PORT: ENC[AES256_GCM,data:gL6m,iv:1IqBsMk8GxZv7PyKQt08svsQbjeGSW9sSMfE7grRyts=,tag:DEbeJxWF/angrsV72O54lw==,type:str]
                        SMTP_FROM: ENC[AES256_GCM,data:pUS2n5ox8u49CyrcEAQPj7Y=,iv:ZGwL2+OiMwnAn11EVKCbcFng/PuOBesscv9ib/g1DXw=,tag:WwJ/E0xC9XfL+KejccKWHQ==,type:str]
                        SMTP_USER: ENC[AES256_GCM,data:wZiChGyNSS/CWORo54Mn3SWe+PGUXRhiS5Y=,iv:Ck3P/a8PEYu1QZ45P7cqtarNVBgyuu9y2J0qsQXkuTg=,tag:t88rfj0D7xWlm6o9/GUqXQ==,type:str]
                        SMTP_PASSWORD: ENC[AES256_GCM,data:x/99jTFHOzPFBQJiILQ9UA==,iv:2TyKoaQO7gRC+pGEP42mh52+DAAUkIZ1evLBd7mlmCg=,tag:0GGlKRuZI7A+ixCRM7rO6g==,type:str]
                        SMTP_TLS: ENC[AES256_GCM,data:cxtYsFEiuAY=,iv:nw6jZe6milgUAmMNJL7+igyqU/IHk+652QL781diSHI=,tag:MdkDzqgXmqfbDjW2SzfA1Q==,type:str]
                        EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED: ENC[AES256_GCM,data:SpfzrQ==,iv:soXzIOXD0PRnBPyAFB7baxP7FhmH6LO6wVFkB/UpAHk=,tag:wdYGX2gEZ/UNNrdLRrEGuA==,type:str]
        postgres:
            containers:
                postgres:
                    env:
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:8vU3qZ1P3N6GtTGvJ6v6ZMFb9bOXg4bE1U+J9VsewLI=,iv:HgFVhyGVFPRwCw2cobA03NO6xlAyerUfKOXvpMfYaOE=,tag:yYq8KCxLUjl5xa8M+Rfkkg==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:J0IdjOq2hv0=,iv:PBWYoW8Jy4gRyaUdX3wKsZShHhGMSEXdS8SoMC9ojhI=,tag:KTI8q2XSQaFf1op3nIUUYQ==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:J/7qTHQ/ylw=,iv:awO3gL1Bq3GtJoQNNa1+LUnEbhKXJ+HgHlsNU9PHwvE=,tag:q03g2sw5foAeRkEptoTCjg==,type:str]
                        PGDATA: ENC[AES256_GCM,data:Ovp2ywfzr2/lIuZegL+5bHhPWSMrPK+C7j7GI3h5K+c=,iv:ZuqxHcTs2OihbgsCurN5ZMKmMqXgpJr9yY4Ycf3lX98=,tag:NrtbOCfBYu/jgxgjTkPUvQ==,type:str]
    ingress:
        pocket-id:
            enabled: ENC[AES256_GCM,data:05kZqQ==,iv:Nhgc/F8mp8ShzMuc772/b9vY/VwpLstOugZClHh48+Y=,tag:tgKZZn+JM1PCu9qMqY1vAQ==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:MGraExtWbTxtkjm0WHA/xA==,iv:vTc4qDT0Hop73peVftZZrdEsHlDazjwWqK2sAAGNwoE=,tag:qXjuTOjzfFmPWJnaQx7zEQ==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:6ZtnZw==,iv:5pboMPll4+GqelkuDBM8qY+cmUMcQT4NM+5z35r/3GI=,tag:Z4fpvDUUwpsGUkPrXZiWcA==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:tpo+OpXcyG7t,iv:PIQyi8TcmGL3EvQhiG2cgefMGXp085F9fz34yKc7rp8=,tag:IoTWS/WtaY0RV/otdW+Yww==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:mS/F3Fjf8qyDax6FgQ==,iv:hIG3SoFNAUUoF3S/lBlx8eJrGx53fCfz2ILIMaoZu2o=,tag:7VvMuns0JuyIBaitWUVsqA==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:Mi6LzCXA,iv:ceebzHJpnNznhcZhDNMtQTgziH7dPZQbYCGS6O9eZ1Y=,tag:V4Tu+N5+6FuomB2a+x23FA==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:/fIOPL3mYueXQmirOlyfhw==,iv:TL9lR9PzlQYwBV4/oD4K3avDBsf0jm2oqRDcWx9UNIc=,tag:FnAiIhK9WlmTqShMds6iQg==,type:str]
                nginx.ingress.kubernetes.io/proxy-body-size: ENC[AES256_GCM,data:taja,iv:Sg/iPRf4jAGMe2xqKqmJY8U649PS5FSceYn5pugjfiU=,tag:mfABCJpaXB2rouAv7JZkeQ==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:eKP5ZkECMz/navgr0nt4prS3j+Ou7t3z+g==,iv:fIcQ/TLw8U4hpmr30ThcYH32GVBMc6LU7hIQFbAgJ1U=,tag:AiM7NLjakx1D6BNPNMqzYA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:dg==,iv:i2bUoY2baCLGSFKKOT/k2q6mvPq/jsK+8QVTsNQbmMI=,tag:dJ/T0qfvFEHIESVUpkGxbQ==,type:str]
                      pathType: ENC[AES256_GCM,data:VlawZ/+Q,iv:j84y4ys5tjF7AHK8jvvNotB/JLpUpygWziEDY0u8kEo=,tag:dvnpFWHfqP0CsbbF1qChBg==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:GHh+oK0UH5RD,iv:+owXn8e99lhbbm53af/Dupl4xF+4gy9rIL/DnMalH7Q=,tag:OCt977W/AUIt2vCJse/kAg==,type:str]
                        port: ENC[AES256_GCM,data:2q3Ofg==,iv:q5Qnlf+jLwflhUvDvc8mFiTWO/oi1Dm4lMl0LukChHQ=,tag:5B3xtzEOCVLVC0oN/+JsRA==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:jWOhIqhOdzBcUCIAti1AFgkU,iv:9AMA/zZMIiqI9eE/by8D1k4Z1LEwKpwWmZ5R0oTXwY0=,tag:JTGKrG632QaIPSJ+4M2TEw==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:ESIPtWNCUpslxTv4azMF94Djtk96UShjwQ==,iv:AbpFBnNOstGeZ9C6awANhZWdMOSxD11MCmGIrZ0OwkY=,tag:haorTpgOdTm6Do+GZ0AGNA==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OVBoQW81c2F4b09xKzdH
            S0Q4Y2s0UkxnQWF4MGNCMXZtbjVpdG5HSDFnCnlkWVVlSUdMcWJZcnJOMUNkRzA4
            My8zNFRacVgwTE1sVTUrNjFOdTQrcm8KLS0tIHBVQlkzTGVZUXpCWGFyR1EyYnRI
            SlBKRDNnSEhDOEJleTg5ZUNhOSs0SkEKXS5yfJB4CJotz62IJ9IYVIEQiv4a22Kc
            x77gg8gi8Ucdnw/joFNP2l9WCdi9zVetlKMCLCRGpihdDfO782DtOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T21:20:41Z"
    mac: ENC[AES256_GCM,data:FnvXnOY2NTD7r8JMUzk80c3dkv/31hzI+HdUkgiHNMhgeZQTIqQypV2AWRZsdxwxupfKZfjqOLMTTEVIED10auYAiOonM9t5E5fHa6DJgcDkMeMHYeHNujw8MHGur+FbphG3a/AybSEAFiC2CFr8Pv87VZgp662+X+ws5YLvKRY=,iv:zGZ7fQbRiny36bBx7HBIyDkyzUxZYe4ytkHFE2/k3y0=,tag:nhJCRX9IY5qYBSbsMLiNHg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
