portainer:
    ingress:
        enabled: ENC[AES256_GCM,data:sWe9ww==,iv:9HTlucnAwk80b+gKTValVPoG8aE48nG6I60nvhBxHdg=,tag:z3z4blhIca8LO76CWHrxMQ==,type:bool]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:2AtBevkTShDEb5I3YGuW6g==,iv:6joMtAVXVzPYWgbyDEGUfzBs3mANmYQRXMw+faoSeHI=,tag:A+3eswHn03DwT22k+K6ylg==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:iMKWTg==,iv:9+5LsioRFwZXW0vXxex6iskjK1MZsbFoVfWIo3/SZvU=,tag:wuogArPuXGj96ipA0Czt5A==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:YjOSeW57oGgSjHe1,iv:JpuzZ0DBb9VYaM/6FgQnSVA3NTKh8XtufXuuI6BMLmE=,tag:dgKus+YJ1mWBXhipIaTT7A==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:4GqzXRNbXgWAqeESyDw=,iv:NPrmUon8V73Iamv0scoJgGrO68/Emddsj7bkJ9V9Q4s=,tag:knMtQR2P2UsiEKvFoigb9Q==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:DLgb5wvO,iv:NfcZ3NvRpVoK9QvbqZv7/R4KDPCc4bKcZ1QchY+jlms=,tag:yuAXaDpWQiIW8hXpX8PwsA==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:sENFMRuDy9kYrujXsg==,iv:b1OYj7KJv/QSP9xxL5wG+oY7zgoHV1SDXOEEC+9Ncdw=,tag:Uig7Oa2qSEVyb+3BEJmR2A==,type:str]
        hosts:
            - host: ENC[AES256_GCM,data:MgEd1KL9indTYxyTOkL/CCNeEm46OjU=,iv:PgeQIsPj+3CORPePU2Qrm44zn+aJbPQLNur+jBUmy/w=,tag:LPoPUqFPDFOx1L1WTtApyg==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:Rg==,iv:ubdvskc8pxBjDAYFApKejsM3ZTjZLifFN72yFdmETQ8=,tag:ELJlgLx6tzco2ZNCZVUo9Q==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:0mosHfjUpeXLuiav/0lPSg2q,iv:JlOWYzmrUlWGUV6Uj6xbxe2iCYBH6XdJkSUY+60kb74=,tag:UZcEK2iIXPEdaVB7fSeNdg==,type:str]
              hosts:
                - ENC[AES256_GCM,data:shnR+zkO+OF+5wXi5Brmd2JtilLdpyo=,iv:ZBXWyPrke9QOy8mohzLpTftO/J1pyAbf27gkYLYbaug=,tag:gU7fqbKQ/qYB3wSXhNpssQ==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdDZYNjExNDVHem1xb0x6
            U2dyL2Jib2ltdUx6UjZFeWZINnBjUXU1UGlVCld2T1k0TjJDWFIwck8wRi9TalZ6
            RWlJQnpOMy9MMEFPeGI2UWU0SUtiNE0KLS0tIE1JaVZyT09CeVlsZ2JoczRHMSs1
            dHFBU2taeWI4RVFVbDVHWVNzcVpIb3cKvZ8Pg6tQ8XvHnNtt35cHQSTjGZZCgjmB
            wzDJHAus3W97cSApkPRpGTK6zcgtVqCvAjWy8hCwl3H2ed4WLAtXug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T20:25:58Z"
    mac: ENC[AES256_GCM,data:3a48/zq73RI0Ryg/vJBH6PvlqX/TsqXxZoY6oj/HIQ9bQ1uGyNoO8orEdd2xSG2gjMnmMNhcIkDOlgSd9JtCkbhSPwJ8PNA9wqYPcrh//yN49LP8cFTYUAooPb0cb6jZ7gBSrxnszcrDd/2yfdQ+v1nin1kHoxgEGwa/P2xIvXo=,iv:GBoz4+7Ot1raA0zBRoNtsIoJ/hZHfDKPMPqEbwTIhTg=,tag:c6HnY5tCjU4R18LSzjQk9Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
