portainer:
    ingress:
        enabled: ENC[AES256_GCM,data:HqFGOQ==,iv:SUCNE1nToXc+lmvlq79QuTGJTiBPrdVrEAMXadtl6Ok=,tag:dJripZFuADnSKYhrKE1y/A==,type:bool]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:NqkGfbwWKWBVc95cDaexyA==,iv:cJOaJ+yMmu08SSXthmoRpOLGlQvbxvzBk+cRhJDyQtE=,tag:gA5yxXyAD+SzxK4zBpippQ==,type:str]
            gethomepage.dev/enabled: ENC[AES256_GCM,data:QAMIjA==,iv:vwNpLSwhXQf9NGB/YOGdiooU7iP0q9EnjdYQjcF+QnE=,tag:7hsOAfaiDZ2Ze5sNQUdGJg==,type:str]
            gethomepage.dev/name: ENC[AES256_GCM,data:paGSKcNFCb78A4RG,iv:Nx947aF5lEpq1HLBs6nA/45ONGNdx26bPKtheVQ826Q=,tag:C5zGnsnxLw2CRGylbsjs0A==,type:str]
            gethomepage.dev/description: ENC[AES256_GCM,data:r0J4PuFezPYubXJFIGc=,iv:lfyfBencNm/gQERSvCEk7lWCVqAV8ryZ1nVLzLJ2Tiw=,tag:+2pjrlz1cx8/lblpxHWXtg==,type:str]
            gethomepage.dev/group: ENC[AES256_GCM,data:1Mx4QYwc,iv:pKobIVbJdRh29eeZbAvq0gSKeHBaJ04K45BrKlbE4KM=,tag:Pp4+w+TvSffDjwKPvsD/Bw==,type:str]
            gethomepage.dev/icon: ENC[AES256_GCM,data:Etabjq3eG7XbbwznHg==,iv:oMHbAxye0oXsMa5TQOiTLVSm6c58i2FJmUkJ6qeu5lY=,tag:7CiL3rUpQ15zmhoHGizToQ==,type:str]
        hosts:
            - host: ENC[AES256_GCM,data:NFhNmWbr3C/WE9CiCxHvZ0HIv55s0VE=,iv:GtHNkozoqVARP+qK6DJUYqCxISptSrBH8GPAaBO5pDo=,tag:ivFpRdIHPAQ177cxsoS93g==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:QQ==,iv:6l7mTw5IecosOWjkadPj7AMKrI/UsLKXJraoVxqEXW4=,tag:LkSe+sYDJ9WYSiU9KmkeEg==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:XklJkBWtD+zXu70VDJ3DJwbL,iv:/CPXNitVNPspKi/5v8CD/ACw7QwUcj3kaWZ+sn7gJMg=,tag:QS1HIY8ImNtvCa0rdO5qtw==,type:str]
              hosts:
                - ENC[AES256_GCM,data:woG6YOJWaMJHvumJ80sffkPcGwj4YFc=,iv:n1ztc1Fpmhq6AVbKZ7C1//No3MQ9VhEkjpGmrlcMpNY=,tag:VItiRApLCvK/8lzsWTu2Yw==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RjJ0d0x4TENHU0haOEh1
            d1pzVEpNL1R6Y3FNdjI1OTFCdnF3V0Q5N25FCkREekFUamc4VWZLcHlGZWVNRVlj
            U0xoV2gwSnJ5T0NkN0U0UWtiVUFsRkEKLS0tIDhNL0JmMG56R1hGendiNkcwSFZs
            REYyMW52eFRPZUNGeC9HNUMzamNGaWsK7E7dhK8wu1n2gquYd/mMip4j+agWeSjf
            yCCP7iKpeXPr0wDUxhKDq4HyLVHOS/MQQAtun1w4W8iGsCohaWHFCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T22:20:29Z"
    mac: ENC[AES256_GCM,data:EXjkO567SpwxrDN7KeEvcojlKFTzOm2N3l09ZS8d3LUqX+rCbkj5+CBVKfuesyov+iL7ob3j89Z3o0hhmmZ41U0vnNTQ8OMrQo7cS11/vgmyQkKzsfTFfiQ4ndAM1NovaK2wy6mxv6MyQNmnA7ayUdJw7GeGsX880QcGxShSv5Q=,iv:phNsQdq+uvVIFm+XZwe9rZF68GthVprL5JTYdHq0mdY=,tag:BeBxbnlFQGoElAhQEeUPcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
