homepage:
    config:
        kubernetes:
            mode: ENC[AES256_GCM,data:0l7Ae2dQsQ==,iv:UGnO6R65uFE4hCIFqd+jOb32aHz2mK0kWBmn+46zxbM=,tag:U4ZWA2BlNm2HgsfnO/fDcg==,type:str]
        settings:
            statusStyle: ENC[AES256_GCM,data:oa5P,iv:LN9iftSVUK4Q7trdhT6Ip5vxHhKjjIyXqvMlG0ypNws=,tag:RhL2OgKJgquK70eigRDIBA==,type:str]
            quicklaunch:
                searchDescriptions: ENC[AES256_GCM,data:s4qtJw==,iv:TPr/04TJ/IfuCUsqNnGFkr4m6RaS4VODaTlrfld7osM=,tag:VWSWVnKf8TsH4YAu5RPCyg==,type:bool]
                hideInternetSearch: ENC[AES256_GCM,data:8kl6OQ==,iv:BL8yBWArkqZ5K1MATCdNaCbcP4pm7cj70sL+e3IgOmU=,tag:iloLYC5kpbaVq9Et9ZfTEg==,type:bool]
            layout:
                - Knowledge:
                    tab: ENC[AES256_GCM,data:KJVO5Q==,iv:cBCWmL9zrVmjQcUKwthRw+Gd877e4oaCYBh1QerdIkw=,tag:LI33vIDNhZ/hJgnXiYDJlA==,type:str]
                    style: ENC[AES256_GCM,data:0pB2,iv:GhRoE1zl7u5vpi+x02MO0FXq7Rs/x9yuRJkNyODyPHs=,tag:3BTSvyNNgHLy0jInaSITww==,type:str]
                    columns: ENC[AES256_GCM,data:Zg==,iv:TvdXJw38H4nrz4Y6UfcCM0cX4kuQzz0e9hxsP8sMZvI=,tag:+27swRa8kt8P3QqYsJcrVA==,type:int]
                - Documents:
                    tab: ENC[AES256_GCM,data:g5qM1A==,iv:6QzHHi91nxEbT9I70j8FmZ8FNuQBDG2we6bWIdadhvM=,tag:nbuvf1buM/zDfB31e6/tiw==,type:str]
                    style: ENC[AES256_GCM,data:E8j5,iv:UnojBFISzwI/PbOALjLFjJFptPbPdf1Z+zXalcPf9ew=,tag:hHNDSoP2qwFCHfaftJjlIw==,type:str]
                    columns: ENC[AES256_GCM,data:HA==,iv:ptZPBEIiXLAqT7PwsS6du5FImMC1TCWSSHPXJ2g5vR8=,tag:aW9QG4H7WbbajfXsVhDJZQ==,type:int]
                - Sharing:
                    tab: ENC[AES256_GCM,data:v9GnvQ==,iv:docZx+B/ffPP+gm6SNNx22zTbGPN6vA5gG4r5wjoPQU=,tag:dlJg7aP2udveCgTfMpvYvA==,type:str]
                - Smart Home:
                    tab: ENC[AES256_GCM,data:JSNBCA==,iv:J8K1O7IZcuTisaBrlpBESugE/dPirntGq8pPFROm8Kw=,tag:eeMUtxye+p7n4kC7lcrUDw==,type:str]
                - Media:
                    tab: ENC[AES256_GCM,data:fTE6E/o=,iv:KvPOBlGjGnsrUfAnqb6gZvYdrW7VZwk7aURPzeXIeME=,tag:PrHv0izXESOhjaBunl82qA==,type:str]
                    style: ENC[AES256_GCM,data:7LJ9,iv:acyo28t3cGlPNh+qA6gx9MrHh6rcf4IJF5nyWr/0uD4=,tag:r/VLASLzFOJYDy4LJVrx6g==,type:str]
                    columns: ENC[AES256_GCM,data:Aw==,iv:a04NRAtWOs3wwtmV52sXM/hXfXAw9ZUnL+L1/mSmSyQ=,tag:+Q9rJ+F1YGmhl06lxMFbog==,type:int]
                - Servarr:
                    tab: ENC[AES256_GCM,data:V0RL0yc=,iv:RXPPJuGDPhbW1rvx6yp1N1C4/9txN5lk7sARuJ2U05s=,tag:uZvCKPi7aOz+8N555Y/nOQ==,type:str]
                    style: ENC[AES256_GCM,data:O78M,iv:Zz043CClKfY86hfiIV/aExmyP/vwROoQyawhBOige1I=,tag:40my9eaeW5pIqVKQ1EMZpQ==,type:str]
                    columns: ENC[AES256_GCM,data:9g==,iv:l4BD2d4Crfl9eUWaOD/8O1OV5mEj3V0ZPhfrOzE7GnI=,tag:Bj1jORHXaN/yr1jnjWTR7Q==,type:int]
                - Unifi:
                    tab: ENC[AES256_GCM,data:q7HIVLP4+Q==,iv:eg7GQUvpqL/dsp6KFenTX3K9RoL5lTFUuWFP637hedA=,tag:6W6sVP4hAtpjLPIqGV/6PQ==,type:str]
                    style: ENC[AES256_GCM,data:v+bH,iv:q59t80ptmVbVJfK1vaKZsFsRKno5DVO8MymAG9y1/wk=,tag:CTSEeTk1WD/Y9t8ik7aeMQ==,type:str]
                    columns: ENC[AES256_GCM,data:4g==,iv:KM4QS5k2bPynoqPfe+pdCY1oOo39J3mr7o0Ius/EMU0=,tag:v4s9MOUWGEJCyeQN/R2DmQ==,type:int]
                - DNS Servers:
                    tab: ENC[AES256_GCM,data:l7Sr+A6UPA==,iv:phYxYvlKOwtWlvTa/mBpPjezpji1Y7ohE7448MWqyuY=,tag:J6yWtgBEwO1naCECJySa7Q==,type:str]
                    style: ENC[AES256_GCM,data:Tvqp,iv:TflvlCqmxlfZhxN6XjnZi8Cxhl4ILUzrfVnWVEp2/6M=,tag:cZ9bH0kOM7aGd96BEwpn4g==,type:str]
                    columns: ENC[AES256_GCM,data:Vg==,iv:alrAIM16z5sxEndipG9ASkaYM069agJoUcwPgIgbZBg=,tag:GrzNEtGBArdugLzL5cCVcg==,type:int]
                - Network Tools:
                    tab: ENC[AES256_GCM,data:jigk3Vum8Q==,iv:lsOE/fCBSwnJMaihwelmLKfU3k4aPjTPSOcpYki30GE=,tag:ZDDDXd2Q4oR9e6uEdNWIPw==,type:str]
                - System:
                    tab: ENC[AES256_GCM,data:a5Yi8LtMdg==,iv:CfIm7Lp/Dzz6LvufoYHH6n2zvAVObwdV60OBO0xVVmk=,tag:ZjUsDL2fQlV4EX06JOQbIQ==,type:str]
                    style: ENC[AES256_GCM,data:emsx,iv:X+csdwOXTH+FGxtLkVo+f/SHinBmQqRsDWnUVR1p7PE=,tag:o2awJnoAOsQ8nUDwBsqQIQ==,type:str]
                    columns: ENC[AES256_GCM,data:pA==,iv:3QV94HJ5ZhwOBaFGc5rOmovQusOWgs5Wb5oBKF8Fj2Y=,tag:Pl1dV0Uv790GKuclbD0QwQ==,type:int]
                - Observability:
                    tab: ENC[AES256_GCM,data:mZtPewTqnw==,iv:WX7T9qMnEYkPJjhuy8Nv+ihprCtORurqmNgYipeAxAo=,tag:JDL+k1zhvxB3hcNjT5TKhQ==,type:str]
                - Security:
                    tab: ENC[AES256_GCM,data:9XbDmwdEvQ==,iv:0slwDKR2pba5fFTIpfScOt2yTGV3iStDDSxFSI5rQzs=,tag:boHO+ZdfZC2ptwsZxu74yA==,type:str]
                - Synology:
                    tab: ENC[AES256_GCM,data:wuQcjGI7NA==,iv:vM2l8R30B07wONpH63VvkEk+UjX8V43c40tKRG/GDr0=,tag:G4VCTDSzm6B/K8rEQV1IMw==,type:str]
                    style: ENC[AES256_GCM,data:RFCF,iv:vn2GWATnAH9qZ8ev7i7x9qC99P08w5SMM2878a6xAck=,tag:LABT5+oC89EJrx7o3G1bIg==,type:str]
                    columns: ENC[AES256_GCM,data:gg==,iv:0YsdU7DZgWxT3+Dp+R0oW2i5epUXmXjmsRfUwE/3P6U=,tag:jo4SSSBErPFvxEl/hw+4cw==,type:int]
                - Automation:
                    tab: ENC[AES256_GCM,data:1nPf6A==,iv:QQFkP5tygmm5mexMitCq//AKZ3gBlpJ6njYkr1JWXz0=,tag:wlVHaWh722qxMcaT/YDArg==,type:str]
                    style: ENC[AES256_GCM,data:/twx,iv:8ntC+FSBbUYYEfN9qTbaXV6aCrhaG8Qvb/Z2g17dnuE=,tag:O6IOGZghthX7McRuIFke/g==,type:str]
                    columns: ENC[AES256_GCM,data:mQ==,iv:Wj51nGp+NvaZuj9nNR2m/zrXv5/CQytSBAn21ZPArlE=,tag:DmIBKB3mB8cYz8Z139ZnqQ==,type:int]
                - Database Tools:
                    tab: ENC[AES256_GCM,data:sAAgVg==,iv:WPtYCCUb510pT6jnT4g1viUH87brbJN4DYrmKAuXwDY=,tag:fa5BkvZ/EF8UhjkEv59bfw==,type:str]
        bookmarks:
            - Homelab:
                - Homelab:
                    - icon: ENC[AES256_GCM,data:jatz/h+cynYCEDT38xmIm/Dr5w==,iv:XqWFcKvT1YzvN2hs/cuMrfVGxfdyo7iVubUmEbJM3EU=,tag:Ik5dG6YPvAhvnyVr3PKqdg==,type:str]
                      href: ENC[AES256_GCM,data:HhbC3H62IT0rWSOrQxeRJIQSJbzouhVqrudV9CqOYQlH7tcP,iv:z+5ZChM47nbf07jQ0HtwBuIQrYk4/y/26SAlTCzCaSM=,tag:A4GSyfHWtpYaIdTfFY9kyA==,type:str]
            - Dev Stuff:
                - Mend Renovate:
                    - icon: ENC[AES256_GCM,data:Hsv2qoqPCR1n/oeLIkE9MBU2sfKWVUjYPa1fZZ84tc6JV+fVeIVwaXzhkz//UA==,iv:KLF4Z43koqGlOrgZF6Sm7P9kqvUTLBdncjCIkMi3K9U=,tag:ZMIfqTIGYP8JSLbNFmvGpw==,type:str]
                      href: ENC[AES256_GCM,data:kDC47+EpDjstF+WNwTxQ5OtXFbeV5H8xshk57Ji85LSTI3c40DldogtDW7WqlzDx,iv:m+ULP1IrW7vjTJz+jv1LwpxZNL6ug5kSbNZVth3hYQU=,tag:PKQ42dGTzawqhpcFqSGhlg==,type:str]
        services:
            - Unifi:
                - Unifi Network:
                    icon: ENC[AES256_GCM,data:ipVnO8EIbhZh1Tt3xK0Zxt54/2s=,iv:9Gt8iiTYhJKdt5dB4IIExVag0FFkBMuejamUVUEQxHk=,tag:9oS2kzvfCmdRs/K3M0CG+g==,type:str]
                    href: ENC[AES256_GCM,data:QOmDgVBH6F3fZjFNypXo2jFRUvgPr3ZIYhri3YmPRq0TqBA8mqqvRAi1gvTQ,iv:9S62nNF+fHHJzFvFilA6U5AVpW7YrD5sH/XIbFv3TPE=,tag:7uuA/PSGTH8XtCECv7PYOA==,type:str]
                    description: ENC[AES256_GCM,data:MTazTv8C0Hx8IVRIO9jr,iv:61yobtIiHsypOyGWscIDArdwd5GEE/hUv87vqy5TYbY=,tag:fryB55HyNF2cz2WtuNVrcQ==,type:str]
            - Synology:
                - DiskStation:
                    icon: ENC[AES256_GCM,data:nY5Mxe0XDyVyBhkT4gaMyA==,iv:8sILKQXf0gMK7ZaGMNMS9a8hbsYJH5jdYC7iR31QgRI=,tag:2sPa9OOB5qqBuFnEMBwz/A==,type:str]
                    href: ENC[AES256_GCM,data:irp7lxM0Dz70Y6KaOULkK7gUzTyEzqmb4sA=,iv:8dzK7rOS8GrrpIGuyH4pE+SsOJGUFsHrPgeXRR+K5Mw=,tag:FxNKup9CW2jGl9V+SAsdZg==,type:str]
                    description: ENC[AES256_GCM,data:2zTU,iv:IiNsNiT8OR5WM9qunDaF3YJXrE2dLV2lBqb4PnW9Ic8=,tag:6ovzpGb8QcWaIAHLtDyjuA==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:+ePY26WGxt0v1sTkX0o73gQw7F94W2ltl78=,iv:I43f4RHsX8TwHaNDLdtAA//bKd1qhfLk/dGU/iO1XNM=,tag:evcSGF8IUQYeIlgJEM/Vdw==,type:str]
                - Photos:
                    icon: ENC[AES256_GCM,data:tYvD62nXCLOnwSsMQuyMs7Nw1dwkiw==,iv:rsS4K3lSQbehs8iigEIuQ4MDf/1ZuBUXYO+MNP74ltM=,tag:BuBX9wqNdvzseOJSFhX1lg==,type:str]
                    href: ENC[AES256_GCM,data:xK+trbOhpm3m+hRl7X5i9xyGf99HF0r9QCbN9+i4RH5R,iv:dmKfxoPgZUmnOSC7axQIBaUj4GMPaCrcu31NVQUl2YE=,tag:bzJUqAb+NWAuECkXzOCb+g==,type:str]
                    description: ENC[AES256_GCM,data:GGk72ZP8rFXB62FSl9j2,iv:m87NRwaYbuOI0GKW0nbR0nkmOSBFiqX8XJXwYMr0O1Q=,tag:VswV1YNsaP+BKLdO5M033Q==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:2QrCp2KOHUs4C+8v/ue6TRxXJ8KbQW7VRFUi1NJuvgVW,iv:6evgjUtTzZPEBFZd5roFLp4actoUmWhfECsNfRylAYY=,tag:DzocoLYL0BktH8d9bqx6HQ==,type:str]
                - Drive:
                    icon: ENC[AES256_GCM,data:eodXqd+YJUwNAL9IbrkUjOTJWNPP,iv:fvnBtJbN3v/Uf6Q623/o7ZcKqROB6EYaZvSvGKAL/8g=,tag:4QQSP28GLvjHpuJIy1AHIw==,type:str]
                    href: ENC[AES256_GCM,data:ywYUWB+ikLPh1RWhHryohJdDvUjgV1KR7ktkfs6Xgo8=,iv:PHyi6stJDPi26dyarRZJcQpBwHq4QPRrf/CHsE4lI8c=,tag:Mfy6NfrVmpxISA8Oe9/Ixg==,type:str]
                    description: ENC[AES256_GCM,data:/mcxu4FhKs7/kQ==,iv:hTh4Ob3nBoTWSRN0O5Xz6+QJ1NzqJl75ObqohCl25dc=,tag:/yOSZyqwu210+hcUo0ppEw==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:frif75vgu8fuKIFteOf/8KM4gLmBwFaQmcMgJ5VOZPQ=,iv:RIgQobgYUmW132nKMucpe6dVH8y1vkqS+Y1jKx9iK4A=,tag:3rLIUOADKNUJSWY1LIDB6A==,type:str]
        widgets:
            - greeting:
                text_size: ENC[AES256_GCM,data:KBJx,iv:TnmByeDrhTcnO1I81frP9SCq3uRHbUqXpPJs4hXeYu0=,tag:DKGOZVvxujAdHkPD/OxWTA==,type:str]
                text: ENC[AES256_GCM,data:Yd5C0ypxa+Q=,iv:nsjslyeYvOwfPC7K6MFRS4xxdw5roP1JtKojMSVnFU8=,tag:eIN7tX3LEmMTg5W/jNKz7w==,type:str]
            - ENC[AES256_GCM,data:PaxsrbiAbNddJn27YY+etTurEEWPRQfO0zt0ROMv6XVt12e4eHzfupMh+I0l8Wxo+aIP7HWU4pM8Rgrj8+nZr1XjXTI3N5Hm5Fw=,iv:BNj3yDkGFcOCWxhS4+Og9au4iTKW7CVTBKj8FQjS7iM=,tag:+ztH9fhgLY31lxflPD1OFQ==,type:comment]
            - kubernetes:
                cluster:
                    show: ENC[AES256_GCM,data:tM/Tmg==,iv:6LkUCo0Tbgac5PwWW+AgAJQZEvvLjI4Jb8ulNszKjkY=,tag:CTArz4zNKgs5G5Kk9YBIXg==,type:bool]
                    cpu: ENC[AES256_GCM,data:/R/BnA==,iv:pwhMbWHm34eUu7P2+rZCw+ZclvjHunSya0XgPCNyKO8=,tag:PvAoRvSu16Xtvwl8s0DBuA==,type:bool]
                    memory: ENC[AES256_GCM,data:EZhe3w==,iv:4/Jk6uIbGCgmR62UxkVtaVOGRZsQe1kIwVnfh3v8mpM=,tag:hNUt+zqgT4sBknqSU7FUfQ==,type:bool]
                    showLabel: ENC[AES256_GCM,data:sR6QBQ==,iv:AcZs9XGuAtqfgQr3AGEO2NLLclKYOTA4uRxl1SDDOyU=,tag:aJY39BGgMMIrsyk7vn5bOg==,type:bool]
                    label: ENC[AES256_GCM,data:SUnUyhwidA==,iv:VlVqRION9TXHHeqiHcLwT00AfOnMt4HeV6GCoDJCDCA=,tag:thxYuGfK2saxJNnXKJA85w==,type:str]
                nodes:
                    show: ENC[AES256_GCM,data:rCK28Q==,iv:fFdZfisMAERlT8J0tiUCa7mjUMvHvkMZTue5/CaenBs=,tag:Qdszj5nmJeUSIeRbINrU5g==,type:bool]
                    cpu: ENC[AES256_GCM,data:eGMKdA==,iv:t3irUivxBuA9jjZvxCQzOFGgm3UZwPKQ1xMvK6OxKFY=,tag:ULk1XjlFfxySO9qPy4H33w==,type:bool]
                    memory: ENC[AES256_GCM,data:70CWtg==,iv:zMiHNg5DhTfunEPTv99EdOSIzN1tuS09v05OxKqSh0w=,tag:oemXw8JdPU5wFlLV4/eEIg==,type:bool]
                    showLabel: ENC[AES256_GCM,data:r48m8w==,iv:bbxNiE2f/IREJBB/Ge9b15em90PZETQME+Lob3z3JeQ=,tag:V1cihzr+PRp9sNiqNsq7Mw==,type:bool]
            - datetime:
                text_size: ENC[AES256_GCM,data:lM8=,iv:J4rfUSXo60joO6sUzOWE5NzlzX8/bkHCRy4LtV/HoFE=,tag:UwlHb6Y3KJ+PQyyEWTd9wA==,type:str]
                format:
                    timeStyle: ENC[AES256_GCM,data:lsnt8kY=,iv:va0hrqNP3AHZikKrwjPIaEv9jGaD7m8H/rSevvQdksQ=,tag:Nnx0APl663VSI/djeUXywA==,type:str]
                    hour12: ENC[AES256_GCM,data:OBL8vA==,iv:f8+YMx+C3xvMeOwes3W6cy8mA3I3wtDGoXHyG3FBXUw=,tag:bx3m5SOzaQqW9XDQm2PJmA==,type:bool]
            - openmeteo:
                label: ENC[AES256_GCM,data:RT/EAGbq,iv:jJ+hBk32zFi8o2tWifNQBhXTjRJHZe9gSfRVWQ93NSk=,tag:J4j7ZwWUkjLWnF54eWqI5Q==,type:str]
                units: ENC[AES256_GCM,data:50Y2P0vj,iv:7vZM5Hw2/cvpB8ovwm9u9/1pitTueLjQokI9pqSacXQ=,tag:3UxOCTBJNY81op8Fm9WoQg==,type:str]
                cache: ENC[AES256_GCM,data:dMI=,iv:dOGp4wxpXSQqsdWdgu0VoVLTyuUUPz/elGD3LG6ssC0=,tag:AUg3X0YDn2bLmvzI2EPBtQ==,type:int]
                latitude: ENC[AES256_GCM,data:ZtkM9cS18Ue+,iv:QzCzn2GICxloeeHR368jvltSzDVGTzV2l0Iws05LOgI=,tag:G5C+fYupjd62Z3VbhN8M0Q==,type:float]
                longitude: ENC[AES256_GCM,data:i7bOCOLP+VYNVA==,iv:+Pcn/0X5nEiTx2hEn9L+L6qdzT+87JnX8QBcyM6DX/E=,tag:KxpMYbInXzMsgarCsAVwdg==,type:float]
                timezone: ENC[AES256_GCM,data:2NxWPZUzM+CfGco=,iv:Kz0L1wvUmZw+slCkE135JfClyA6awMW+W9hk5qLqHTk=,tag:D8NdvUM3wTLkaTs5E3FunA==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWS9scldmaVhGR2VnTHdL
            QnhLZ3hDalRtYXA0bXE5d2ZoVkQyWnNrZzNzCk45aUZIb0xpaTBaREticWpwMm9N
            VHI1MkJqNVRMcHNWTDkyYitUTEdSKzgKLS0tIGNxaTdCcTlkR1JCZkRrQXovZ1Ey
            clZ5WU0wSzZiVCtGZGV0cG1RTW05Z1EK1DJ+zn1dmRdTf/gmKuNxYWR0sZotNeV2
            PZIVGJuJNTww/sS6nOYMePYDhJeDnXRbWjHR3WdUadnoFfQmGCH6+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T21:53:23Z"
    mac: ENC[AES256_GCM,data:01jkg4XiONqEK19upInKG2+cFzPM3FkjPrCRrhaGOggdo/b1h4FyW/1ZD3ls9jlVA+cG6WvkJ+EpWKLNWA0qqE4Z4NkBmAwQJNP2mjnJXKu2qqZMnU+Hnv7V17eIpS3ajWEdqoE6KYq05mvl1NizvIjcwuaDM1Avdm5PiDuwvNA=,iv:JEVXvgDKFB+Mh8hIWDHSxVGH62xvtvWfrx/2hpMU8zk=,tag:mGhf460RGedBpyuUZOihcA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
