homepage:
    config:
        kubernetes:
            mode: ENC[AES256_GCM,data:f6nQpRekhg==,iv:8+0L3vqaIRgKBSHv9KWpNay2VmhL6JZ058nzyNtAH24=,tag:KO7fy0N3cj/wBnKJhgOhEg==,type:str]
        settings:
            statusStyle: ENC[AES256_GCM,data:SVEl,iv:E0agFJEZrqMQ7lhA+GVX6mSZ9XN023WUF3jXaTR5Qxc=,tag:lwLdhj4QIjm979idXg5iYQ==,type:str]
            quicklaunch:
                searchDescriptions: ENC[AES256_GCM,data:geWaWg==,iv:HKjzjK9u9cBGr65Mzuv4DnDoG0JCCK5Yzag6p6NV//A=,tag:JAvJMSVpBI67mFJa8wfUoA==,type:bool]
                hideInternetSearch: ENC[AES256_GCM,data:XTKMSg==,iv:BH7kIRyziCQXbqBSPJ0eRidHzpzm259MHmzakU6IM8o=,tag:qe2rFTIpJJzou5DeKD6Mfg==,type:bool]
            layout:
                - Knowledge:
                    tab: ENC[AES256_GCM,data:JUxRdw==,iv:ud8+3Lg2l9kDdK2nhIpJ/ecoDDSmrHE4IrI4oW4dmAE=,tag:Kwd5p87v4NMhhOym7Bsd0Q==,type:str]
                    style: ENC[AES256_GCM,data:kQwy,iv:0T65UT7ePqhUAKAuedll/jDWSBypIU1K4l5o4VsUfNU=,tag:Kp/10pP5s3iBejUG3zEvLg==,type:str]
                    columns: ENC[AES256_GCM,data:UQ==,iv:kN2bCdSKa+8oZn/G4UKyHwLr9xsr1MsbfGCUT2AKAWI=,tag:eE63tXKOMXGddTJqaXp3ew==,type:int]
                - Documents:
                    tab: ENC[AES256_GCM,data:pgaAQg==,iv:rmvmMehL8rrIRT/XyCjg8mv8ic4UjB1g8rMfiU6ZKAg=,tag:ll7PFmM26Sf5N4vgTLjNBw==,type:str]
                    style: ENC[AES256_GCM,data:nbTz,iv:7RtcKjf+K9V7+UJmq7i+k+FMrsLSvF1CHSG0IP4XeKw=,tag:gRvCkccvUyI/ctwouGY/mw==,type:str]
                    columns: ENC[AES256_GCM,data:eQ==,iv:z4yNQZ1PElXClP/BBHr2Tu2uglMRf4JjoYYTMUmIPp4=,tag:xw6QdG835hnYqgGg2zpUbg==,type:int]
                - Sharing:
                    tab: ENC[AES256_GCM,data:1Vloog==,iv:/UYCLMb51KqJuHdipTVE9WehkJQt74NmlArz1/wmI2w=,tag:znZPcXBBtTwA7iKg0nqEHw==,type:str]
                - Smart Home:
                    tab: ENC[AES256_GCM,data:jWgwiw==,iv:2Qkqs0ifbeoP+PI0gsXq0NQylW+aAA8/6VDzkH1rT8U=,tag:Ybv2E3E3u1//qsCQqYO0aw==,type:str]
                - Media:
                    tab: ENC[AES256_GCM,data:2FDGntU=,iv:eDKgZDjAsupqY3YEiYDSZRdwQFe32es8a1F+YGXP0Ss=,tag:BwCzc4dV4MbhfIvrtAVQJw==,type:str]
                    style: ENC[AES256_GCM,data:RQkO,iv:ziVdTtpq6sJnos4cw9Z+G7jL6IaHu4hMKIpCVOJpGvA=,tag:jKzv6sHdJz7MxD1AzUIiBw==,type:str]
                    columns: ENC[AES256_GCM,data:WA==,iv:ZntDpFJCTR42af/Ocvo8WFajHDqeMfc3LpS34U356Zs=,tag:iUmj0d96iJdpAtUCbNBKnQ==,type:int]
                - Servarr:
                    tab: ENC[AES256_GCM,data:rcLCdfs=,iv:Q+fCwQVVCphpgEj2A8sXtUsjt75ha2hGO2MAhSgjU0E=,tag:v1AtCaAotmBAKoraobfl6g==,type:str]
                    style: ENC[AES256_GCM,data:DuxZ,iv:BZzfpLfjV+evminvCU1DrZDJnvedLWwf9AiycFA7toY=,tag:6BykrojytPOOavfVsOvlmA==,type:str]
                    columns: ENC[AES256_GCM,data:7w==,iv:jHxxX+e6Wc3r5hHMgLivc6kRzIVl7QktG4jV0s+nWJ0=,tag:8/Zk/yrGmVW0+9v4Pfl6pg==,type:int]
                - Unifi:
                    tab: ENC[AES256_GCM,data:qtjXNQl5VA==,iv:VXjp58fRKGzW8LRu7mPjAr/c6VGqtVHvTL5C8plwNd8=,tag:FOK2u5brKzfKfSD4S734JA==,type:str]
                    style: ENC[AES256_GCM,data:HmT6,iv:qg45UHWmhr2B1TwZ35SYNbisYub9zwa9QdehEyBbdGI=,tag:Ck1J0+59lFl5O7k03q+7yw==,type:str]
                    columns: ENC[AES256_GCM,data:mg==,iv:5ltmYZsVsQl3/c2iC8zrTSS0R27HWI/lUf6KrR4ns58=,tag:jYZuzxSClj/9Sl67EX/77A==,type:int]
                - DNS Servers:
                    tab: ENC[AES256_GCM,data:fcV4HnnTBQ==,iv:huS8BO1BGofnu5omlyCXOh47mq6Xw+2OPEiFc37iR6U=,tag:dlu5Vpt7BXGyh9QOzeZAVg==,type:str]
                    style: ENC[AES256_GCM,data:BDcB,iv:pQiYIWbSmEMiJOAjEf9/pBsZj+bcXu/3bXp/ZZLGNGg=,tag:jbceZTUMKf+Rg2+wHYOIRQ==,type:str]
                    columns: ENC[AES256_GCM,data:FA==,iv:Y+3NK/inr/rM4s0QMs0VbDmhLfApXtDimRus1MPtdow=,tag:uRyT70YuHz/po2ejIljyNg==,type:int]
                - Network Tools:
                    tab: ENC[AES256_GCM,data:2EZq9jJ2aQ==,iv:P+bVcDzOdp9qLyNQ3D+Mb+YCgX7n5fC/EmPvfMmAgcA=,tag:uG+sFvgjkSxYmUyzNYWbsQ==,type:str]
                - System:
                    tab: ENC[AES256_GCM,data:KAxiclqrQw==,iv:dZBCQg0tGvhgG6ZeHh21X1li0295MqFIT8RrFxfbDD0=,tag:mjXIVn42+3QxYzgQyBpo5Q==,type:str]
                    style: ENC[AES256_GCM,data:nPwH,iv:NW5Hi9gO8rkZ4lZ7CGWglVBoJz4RjLel9WM/N+Q/PnM=,tag:Da7HzGHN8bVCL/b07qxztA==,type:str]
                    columns: ENC[AES256_GCM,data:qQ==,iv:R8oP5pPYrnv97cW4EP+gSUj4gBpaOxyNrmMgbh64VbM=,tag:aQDBaYIvngchP5nxdTbhgQ==,type:int]
                - Observability:
                    tab: ENC[AES256_GCM,data:LH6JaCpltQ==,iv:DtmcTr9Ys5QyI9RlIVGJ+Wdv3qdNRwX/IeC4o4dL1jo=,tag:B7HvXMPwIgEpiwfSBrg44Q==,type:str]
                - Security:
                    tab: ENC[AES256_GCM,data:r5auJIyaRA==,iv:v73sKFlyJBSrF29u/cFtb1Bw6Md01IXHvoZJYKEdwuw=,tag:ul7NT1HgUi/4/wjFOmKcPQ==,type:str]
                - Synology:
                    tab: ENC[AES256_GCM,data:x+fk9kvf4A==,iv:L7ZwGrCZSQ5z7vD1rManAGuMuqlyCkHtwjxqSsqtjUw=,tag:6hhzIVRU819tCm6Qi5x7TA==,type:str]
                    style: ENC[AES256_GCM,data:K6uN,iv:Iva5hLQRuYTv8BfLokLo+HI4ozvdEQho0uq52+fpafc=,tag:ryPWqGB8mvHbTshqf/u8aA==,type:str]
                    columns: ENC[AES256_GCM,data:qQ==,iv:QdUKBx/sErSfXUJWVulQwyRIX/CeqxKbmGzsnFSskAw=,tag:ruE/cP5bi+ns38N/3CGMtQ==,type:int]
                - Automation:
                    tab: ENC[AES256_GCM,data:cpzNig==,iv:HBZbkDKQO0Ujr2MC/TfwUZKvosyxhJ9ozCqRKvVYWQg=,tag:mv/ngu1rqaDYvtXc7yTKfA==,type:str]
                    style: ENC[AES256_GCM,data:gTSr,iv:CtXxZtJS2lwD2tje7es+/5BjrQxG2eVhPZ3hT1fqo1k=,tag:1rvIzH89ZzY4NRPg0jEisQ==,type:str]
                    columns: ENC[AES256_GCM,data:Qw==,iv:m8ptSg81DEnMVdpGyf5etN74fSotVdhPM7AphkUh2CA=,tag:IsT8Y5Ef/dL6MJ1ZjIx7Rg==,type:int]
                - Database Tools:
                    tab: ENC[AES256_GCM,data:J9Dosg==,iv:oN9cGysLvw4ZSw6yk+3Sds4d8sNU1DE4DZ7MCJGW7cw=,tag:B7J+9IGTguT0DsuuX7wGuA==,type:str]
        bookmarks:
            - Homelab:
                - Homelab:
                    - icon: ENC[AES256_GCM,data:AcAOsRY/DGj5/szysKjckxYmbw==,iv:vczwk25BfnR7g64rUf6+2yx9INP99EEymfyw9JGqmjc=,tag:kT4D9Il7QnYYBNi8mvaAeA==,type:str]
                      href: ENC[AES256_GCM,data:vccb5009zdl01/X0/z0kO1JRN2bj1DRhoJMPl2gBwlPwEQ==,iv:NFM8p7BTlyrOS8wXmYzk0E8CjNpjqpX0Ye5VHvhYRrY=,tag:KzjkS3vsaixyycH7U9wVlA==,type:str]
            - Dev Stuff:
                - Mend Renovate:
                    - icon: ENC[AES256_GCM,data:QZo1ALStM+XYKeSQxg3bj5N0lHwGMnR9CSWPklp8phkrfkAQp7LgG9W7sqL/9g==,iv:xAzE6HA7EqL6CykyMVWvHA0UYHRTbpSvo0CizHC/AZw=,tag:ZRTw/c9Q7hTsNvzB4svDNw==,type:str]
                      href: ENC[AES256_GCM,data:Hhia0K6Lc/vlIl3KQUzqZ6QlCpFKSQAZU8j2hCmkOyehZmZiDQry0WmlUdSoivpo,iv:kSNFn7bgfVd3i1jMwdw6olgTyZP8ugLXz41B6WX2KbU=,tag:qmSId7YccjR52rLaioNCYQ==,type:str]
        services:
            - Unifi:
                - Unifi Network:
                    icon: ENC[AES256_GCM,data:Z711SKN4iEEohogUzO55lBSeETo=,iv:Sk2S+nngi29OputryEQ1NaKgfZTEORIT8cAr0Hq0hg4=,tag:Xeo8sSygVyfv7kKpxF9iGA==,type:str]
                    href: ENC[AES256_GCM,data:U6ZXmj2crSM6Lw2jW9njTnkh0oBL8Jm6pep/0+T1U9JT4Do93WbK/lJP+j4=,iv:Y4rPf0Nkmlbb/SZLv1vX6owBz7rbWuLUzJ23uEBgdXY=,tag:GriRM8yWTsuS7qYrX5Uj2g==,type:str]
                    description: ENC[AES256_GCM,data:5irJYMDhe7AO9TBhLdGv,iv:FDBDnNewCO3ThMmJ7goP/dfwHlOdgzbezN1STDZi1n8=,tag:u56hEGxL4AIyVNdQq3duSw==,type:str]
            - Synology:
                - DiskStation:
                    icon: ENC[AES256_GCM,data:UWvIREhjMtxUeN6C4pRfCg==,iv:zBaC33kKN9QPOvt1Pja5qHcJTulToF6SnBaQ8wH7n0c=,tag:mx/oGRwmUk+z6KgCnJG2Ow==,type:str]
                    href: ENC[AES256_GCM,data:AyU9kMCBpRz/iH0evua72qmoZtzse6c5hg==,iv:i9UQoav31Fo9iTw+/8tX6e1UfonwP4xg8vDFKz6mngo=,tag:nxqtqTOES+DHqIXI5orkjg==,type:str]
                    description: ENC[AES256_GCM,data:/4Ym,iv:W4v6O7BxMuOhsW+w5m8s9LJ68VfSFHTCRFBEN067CIQ=,tag:amRC5CsgvqCcNqv+CxSNTg==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:Jzt0IOfyxsPKKdRh7e8A1g4lHZIT2DYPeQ==,iv:TCiLch3ergULUqGktsR1kcl/GlP85KLpgZkFI8VnkJ8=,tag:zYEdkQrAYeICHtynpT2+sw==,type:str]
                - Photos:
                    icon: ENC[AES256_GCM,data:kk+8VHxdsJId1vH0mu7eN5ls3yVhUw==,iv:Wn/CHl0PouEnWasG3kXotYcRGFLro/mEczN7zbYOQas=,tag:VFsQfrzoxq6kQ6F+k5Q1pA==,type:str]
                    href: ENC[AES256_GCM,data:w+xzjNwnxo3tDvlwjxsvgWWnAAeAJxnn7eY/OvYOhy4=,iv:D/R3zr3OmT+MVMfGjEl4avN1t085A0bhdVNuwD6Z8eY=,tag:VmL6yp9k+/3W2nLhDc8mZQ==,type:str]
                    description: ENC[AES256_GCM,data:2r576h35qySSUkZyfJ0Q,iv:O0ECeQhYJSqKvkDIGr0J+hLc9fLTdiSeV5gOZVuyaDI=,tag:EWjd4XDVc5rDMZ7KfYUfVQ==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:te9rlQF6LU1M2yxG5dINDLPp+xF+xYNsbCkVPhj7zc0=,iv:uff4RSL8y7B8Ug9vRa3IQ0K6HxhyVaqZvh3H2FCJjmM=,tag:P/8kjzeuDpNVvRWFHnQEfg==,type:str]
                - Drive:
                    icon: ENC[AES256_GCM,data:uVA7FarwuNQ64pMNXt0aGjKFqOsw,iv:GgBnGJZ6W7BZRDDcmEnYh05bbaDZujwQ00bQsPTKwb0=,tag:gHKASlLtTgDiT/wn7+uQIQ==,type:str]
                    href: ENC[AES256_GCM,data:EmB8NFI4E2yx/pW+0z49MhSZA7rvic7zbbgIfmdgBA==,iv:dQYSRnDM+AqdDDYXti6l2zBZNl1y0T+Mh9x+gakSDjA=,tag:T/mFkeDV5AC69/nrSIq6ag==,type:str]
                    description: ENC[AES256_GCM,data:sF2S6EDGzYT5lA==,iv:IlNrRKVOYVB1VygO92Q2RJxV/2eUjcj9hJDCkDYtoF4=,tag:kyDeDKw47+OmdO16RoO1XA==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:AtvSfEt4hlInOsRLAWEIeTK4wXqIgWqy4qlpO1GXUg==,iv:8YcZpVm7BOexo78yy+Wj7tKwiMUg397n+ydpkDQH5/c=,tag:10fsNspZZH3fkSpjUhKOgA==,type:str]
        widgets:
            - greeting:
                text_size: ENC[AES256_GCM,data:bM1g,iv:v9+98/rCCIMwyOvNAED+8DHiFUVZN5gDaMC4fwDe2K4=,tag:DesZa54qna1IQe0PTwF2Eg==,type:str]
                text: ENC[AES256_GCM,data:PbS0HpwPn0A=,iv:v2ycJURX6EPHz8B8Y+YZOt5cfXRWMPTxVFeVHJio3kw=,tag:moIOw080pznRbf9bDwwNnQ==,type:str]
            - ENC[AES256_GCM,data:eE9+y3HdWwwqy0nP9/4DfAxfyl/oi7xtlJvId65NVjKs9VBR703b/FV+6eNR9ab7ssBBq6YRBsQI1gbsXQTHHfLbv5CIf+RGR1s=,iv:hcaBukIoDkjLhDE6y85LB+RH8LyjLvE8KhYux1NgK/o=,tag:tGUAG9DwY6fO0Hzl//BzZw==,type:comment]
            - kubernetes:
                cluster:
                    show: ENC[AES256_GCM,data:shZWaQ==,iv:pV0XibsPbBA+O5jDnWz0nFtuJ9cwmF8/QTWqt2tAVEQ=,tag:9Glbr1B7CP9k7yq9tJzB4Q==,type:bool]
                    cpu: ENC[AES256_GCM,data:cAzYsQ==,iv:s313eARvdSUp0TB1pjHasFszuFaE0EtdzG+6TawiPcY=,tag:jsNeDHImm9UBCom1fLMrxw==,type:bool]
                    memory: ENC[AES256_GCM,data:p/PIRA==,iv:9g83J9UJkB/sYqA1cil5wJA7G9G9NUA3weBAQBL4cRU=,tag:4zwhauvX4pa2EHEzkAOZgw==,type:bool]
                    showLabel: ENC[AES256_GCM,data:Nj76gg==,iv:p7VsO5WhdswV9QgksGWRlX0qeEZ6LRGY2vni0gX+sp0=,tag:qAyKkc90mSulxMMaADg2Fg==,type:bool]
                    label: ENC[AES256_GCM,data:GeY1IUkrKQ==,iv:ubE9hq33gQAvJrFZh/w/tdJfOXv8WVQVsEV1KMoS19U=,tag:1d5YQ/t8ShacqFZZjDz77Q==,type:str]
                nodes:
                    show: ENC[AES256_GCM,data:ktJF4A==,iv:HKkBt0HBdk1VWpYN2vEv/c0qH0Yo3JQ71f1nD0FW0do=,tag:wpPZCAJwD8488E2qe2FcQQ==,type:bool]
                    cpu: ENC[AES256_GCM,data:XkuLYw==,iv:NCrGr3WXABGBn7Wz9R9fAqQteaPiNehFUjeFifV1xVM=,tag:YaUo0HGDu9vZtuxupd9IBA==,type:bool]
                    memory: ENC[AES256_GCM,data:EnnwSQ==,iv:fyWx/PW26DzVoM7J3dzlnM5njy+tTfj5W4gF3a7YCGs=,tag:n8R3MhmNCzwOpQkePEVZzQ==,type:bool]
                    showLabel: ENC[AES256_GCM,data:ORaQaw==,iv:4pXCdrLvGjRUff77EZ71pWwjrkBczFktuBJCyGYQJAM=,tag:g3ZCR35U/IcHwinR4cjYoQ==,type:bool]
            - datetime:
                text_size: ENC[AES256_GCM,data:XW4=,iv:aRNRRAmj2dqAmco7OPJeEIxZ22S6srAnlYpRfgwp+rQ=,tag:X+qiY3UZhA2of7JWsfT+1w==,type:str]
                format:
                    timeStyle: ENC[AES256_GCM,data:T9x77bg=,iv:faMa7ymbltLxEM85HjHTjmsxmsplOxdH7IEluitagCc=,tag:jnvg08r5e4cmbqx/kGq0og==,type:str]
                    hour12: ENC[AES256_GCM,data:37B3ng==,iv:OLXokMTGAC8WbZ44OKVkaeL/yEjTPn7mclFQr3la2jU=,tag:qaE5jJe12Hk0g2nrgL/SIg==,type:bool]
            - openmeteo:
                label: ENC[AES256_GCM,data:Zko=,iv:fPrPK2T09+MRwoUlGPhipyVme3prqQaaTWtltBKemdI=,tag:ciNfZxZPU9CjyCrL0TYgOg==,type:str]
                units: ENC[AES256_GCM,data:bN13caWtdIo=,iv:WgX79+Wm00SK4BHhLuo4iGEV55lJVEUYwJ9BpeJFB8c=,tag:xvP01T88SvVzQEy0t2bjew==,type:str]
                cache: ENC[AES256_GCM,data:H0o=,iv:q+GqvlgwJnUXR50JQ9SYugTKx1MIIfsop7F5CqhjGmk=,tag:LRo/NHtfHX62gzLB9VSGsg==,type:int]
                latitude: ENC[AES256_GCM,data:Xm/SoqxPj/pd,iv:bAxsdVgMk6O9nO/LQGyzDYIjmE+tS7emUY8LjyEaiYw=,tag:ruRHcD8Lv0eSM7C/+bYw8g==,type:float]
                longitude: ENC[AES256_GCM,data:OQiyPPPsScIQ0g==,iv:23s9kccVxp4lbXw7IoDk1wKbulWDMXYhrw9xh4VAaL0=,tag:qDmyOlBMHY2uTlwlwxC2ZQ==,type:float]
                timezone: ENC[AES256_GCM,data:vn86wh2Tlub0vH8=,iv:OT9pdGsCGMhsTEIBkv/rwZXPghycphk+oIgS6W7IaMw=,tag:hIgDh3XyUXpiBK3LHAGFFQ==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNlFDeklabzFLZ1d5Uk9X
            Z1BLdVd2Z0xPbjE0ZG94aWZLTVNFZzNXazFVCnYwMWJrUEJ4bGtSclAzaGNiY29D
            aWFsdkNZZXpFMWV6WVQ0bklmamFDU0EKLS0tIEZYSEtwTGZ6b3ZxVTJKaCtGM1p4
            cVVaU2FOT09MR1NaakVsTlpBajlxOHMKp3X8PtFqk33z11SUAiyYOsuB9GVjN5bl
            HNBhWpIQwct3xZeOQbCh195yJmW17HF1bEy/7qIOXwDPzTyV1gHPJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T20:24:43Z"
    mac: ENC[AES256_GCM,data:ucfHYXbkJayZcL6i294H4nQoNtVSv2VX4/DX7hpLZiIUEBxn3yaf1e3WHwPs9gQAId0D0Jiz/CJj8A/raqi/j1MzkMpALTeRTtgcpJZM10KR4xKNVA3f08rXChi1HkdmlSH+MyY/H2E0h+ZrkBVecDYNT8mMQIR2SYwfYvyxJEk=,iv:rJ78MgfKH04Ii7JDeMrbInojVzTiC3/+VFoeCuJsIs8=,tag:XyEYwQBRUmHhRgHZ7er+iQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
