homepage:
    config:
        kubernetes:
            mode: ENC[AES256_GCM,data:WjHzcR+16g==,iv:6HE1S3ait/uZZO0nYDuwn3z3b2rYcB4ndLMfEPlnToM=,tag:PS/qlf/v2bPVjpYxiHjG0g==,type:str]
        settings:
            statusStyle: ENC[AES256_GCM,data:nKVf,iv:i6fPdnyXtBiqujhRBwp4WhybO3t6OxrH6e41oWbncEM=,tag:tfty4CFIaPvwOFWvPB3SNw==,type:str]
            quicklaunch:
                searchDescriptions: ENC[AES256_GCM,data:y1N/1w==,iv:p8Fxfw4ANQ/TCWD/RsCs2C8KXMYBhLogcdzlXJZW3Zs=,tag:CktGJCggEmsezeqhQMdlvQ==,type:bool]
                hideInternetSearch: ENC[AES256_GCM,data:QUvvog==,iv:9CWUa/Tck48qhO2BthvHUYUyXJ8MoNICWtSb2GgYQVY=,tag:gxOD5hjKE78IA2mkFGP7sA==,type:bool]
            layout:
                - Knowledge:
                    tab: ENC[AES256_GCM,data:+pWaKQ==,iv:tWYuAbyqZfNjH3r/ZtYRpjOzATqns3uwgyuCIRZiVOM=,tag:2nRga3Od2353bL7mRaLvVQ==,type:str]
                    style: ENC[AES256_GCM,data:4ycV,iv:xfoivUosGTFeGg8i5A7GBaEZXNSnXCcRUxU6TdN17QA=,tag:FAKGPVCBy/HRcC6WZXjiyQ==,type:str]
                    columns: ENC[AES256_GCM,data:kw==,iv:S8JyhS0t68MYekW7SVTWj6GeaK/hLQ1/+swfSeFp63w=,tag:KaWa3p6S7g/oAllcWkem8Q==,type:int]
                - Documents:
                    tab: ENC[AES256_GCM,data:jNX+PA==,iv:VJYKDXjk9F3wqfcn4PiEk9v+fQPzPnKv+zEJtNSzoD8=,tag:5nhKydD4unVXb05XN+QOxQ==,type:str]
                    style: ENC[AES256_GCM,data:T+t2,iv:kzVx4TzmnJPCU3xGSw0bimo64ikMnv5DJoB1WHbD3Bo=,tag:URScDSK0v5gbM9TeMOUzMQ==,type:str]
                    columns: ENC[AES256_GCM,data:pQ==,iv:VJtEH7I93DE7HJPa+61zE1IHhHc6+RsfTIOJxyLg1uU=,tag:R+lneiUTTBnhbgoZYqC5Ww==,type:int]
                - Sharing:
                    tab: ENC[AES256_GCM,data:8eOJ+g==,iv:as5/IvJIUkszRIm/DgD5Tr3bbzbdIYkAfJk1T9TwYOM=,tag:WkrI6/716kqJTSYKERFNkA==,type:str]
                - Smart Home:
                    tab: ENC[AES256_GCM,data:MzR+UA==,iv:SqF5heSSRBsBJpm9Qz5Cyg/V3F9kigZngG0tRxsz46c=,tag:+OvhTdoqJDzAWya/mdunmw==,type:str]
                - Media:
                    tab: ENC[AES256_GCM,data:fOhNOLI=,iv:x3uyUcGv28QxdN527QwiSd+/HvDMH4YsuAZkrxw+IAc=,tag:v8A71ZHx22bW7/Nymz8AWA==,type:str]
                    style: ENC[AES256_GCM,data:3EGC,iv:kvSATzQnf0iLPXbqH5rSzllcSiORJn8BcGHLTfkxmAU=,tag:9xlgWFepFZ1+e2oM6h1Mbw==,type:str]
                    columns: ENC[AES256_GCM,data:WA==,iv:7yJWuPgOLwPvGMgv2SAdv6cg+7DhfLyWpjKCmAFj+Yw=,tag:A4bFdvJPS6MQdehX3bJtBw==,type:int]
                - Servarr:
                    tab: ENC[AES256_GCM,data:n90HIkA=,iv:wWR+b5TOUa+bJWZVT6Rn0zDYlBxLJ/qcACTYL/ujR2Q=,tag:K2kqzm2dC2rwZg9SbVGuPA==,type:str]
                    style: ENC[AES256_GCM,data:7HWD,iv:36nkhbfsv6dSJzcFz8/+lQ4AqJgRo/IF8dJ44qbLFU8=,tag:C1ylQb21I/5JkZW5wPgujw==,type:str]
                    columns: ENC[AES256_GCM,data:8Q==,iv:K0o9TldoR4Jwx2/WW0ItEaq86dnE0JjOWukIAQAXb6s=,tag:rmxuk7EEKaHbjulppxgwdQ==,type:int]
                - Unifi:
                    tab: ENC[AES256_GCM,data:Ui8BdSRHlQ==,iv:QwWjjcDH3kFj5g7D+jtnQl2snqgajLNO7+e6HvkJfow=,tag:XDI/Hf7ivyxkF88d/SgRNg==,type:str]
                    style: ENC[AES256_GCM,data:3Uap,iv:8jOrae4Sgc09ZH96udMGGOAji1TSzpuOdNBuZ7L6rGQ=,tag:thRg0JeeukZQIUKgfKk0Wg==,type:str]
                    columns: ENC[AES256_GCM,data:lg==,iv:SoV0czEybxe4evlgbV/vaNhXGp2UihxT5evJFvhHNbo=,tag:5EFjUBwzCF6CKvrzOfFXfA==,type:int]
                - DNS Servers:
                    tab: ENC[AES256_GCM,data:xsi1zJaU9w==,iv:tcjHMkCVPkKujmOrd75CnQHDIAuzqdmENCyvq6NShCI=,tag:4FagNqNxW2LGllHEJQd9XA==,type:str]
                    style: ENC[AES256_GCM,data:hfgw,iv:1AEFlYXUr1SqhBPCLvwX1wvbj9/XvZYfAsXCvxlGxvQ=,tag:zpsMmHeke+REf7Fwm5kQaw==,type:str]
                    columns: ENC[AES256_GCM,data:8g==,iv:Ro2RWDkod+CVF63YTt+gCfF9e7BF2AE1bML4oRu28Vs=,tag:DeLJJxzKK/O59JvR+1mOsg==,type:int]
                - Network Tools:
                    tab: ENC[AES256_GCM,data:aRoCkugU6A==,iv:iRakWkgokYIZ2w10jI7XEGwcMfxFNlDdOQvjD5+sx+Y=,tag:Jbnxs+aYOCKGIjiGp33f4g==,type:str]
                - System:
                    tab: ENC[AES256_GCM,data:FQb4iZbmBw==,iv:klVjMuUMu0/Dco5FQfHGYbSMfHc2YoVb8XsGHx57aeA=,tag:CyfvLZUTUJgnYuI8KJeMSA==,type:str]
                    style: ENC[AES256_GCM,data:Y6d8,iv:iRNj8cnVtJAQPyrrNHgCHLmyIWKOIp0yx71DAzetN9s=,tag:Cz2OFDCC8NaHRSIysspWKw==,type:str]
                    columns: ENC[AES256_GCM,data:1g==,iv:5biuWaPtxIOPmV0gdQ9P6z1Rkxwt358dGKU5NCU046w=,tag:u2FV2JXTaAMolMUT3V3pqA==,type:int]
                - Observability:
                    tab: ENC[AES256_GCM,data:AkxpBRE9iA==,iv:2ZmdAiZPFXCOUPWIfOM0wDV1Jms/XLTb9vaAr6cN5aA=,tag:N2gMuvrTif/KsOlFrNUVrQ==,type:str]
                - Security:
                    tab: ENC[AES256_GCM,data:pL9S/CkZ9w==,iv:G5mzTQT1/LcC/T0oob/+G7bvNHLWfVUk2glrZ56FgaE=,tag:BRcpYiB1IYqv6dNYoL7W2g==,type:str]
                - Synology:
                    tab: ENC[AES256_GCM,data:Idl9TRUMkg==,iv:hb9ESXy6zyKpD4lv9BLGZS7987/yXIMRgVkEl5cdeRs=,tag:xQBqLY4/xZ8pCYeh4ByGtA==,type:str]
                    style: ENC[AES256_GCM,data:mFvT,iv:AP3i6E1AAJxOGvBOZf1XKhUf5nH/C/cpijSglcN1AI0=,tag:beN32tnwr01tB4CZMNoSBw==,type:str]
                    columns: ENC[AES256_GCM,data:gg==,iv:r+58w7xKefaHrGRP7IS2hRS+EWLtIBZAfqb1tCfBHd8=,tag:6KtTS5x4nzf4+4R2AEjrSA==,type:int]
        bookmarks:
            - Homelab:
                - Homelab:
                    - icon: ENC[AES256_GCM,data:J9zJGpoEtibLddT2y9KSZ/RrDg==,iv:6dr4m14dqsBRNULyj7V6QFadgLrW7mSdxGsj9C4VsHI=,tag:2ZvH1FORiBKG+SWGV0C2ug==,type:str]
                      href: ENC[AES256_GCM,data:AopWyhdM0TyKdpE9l8Y4515DaC88DNNyvD2M4hZG+0yJBHJX,iv:R1zQhJ3auIAoXfW5CDpReiy5RilhGBI3Em4CoGqBmQw=,tag:LNU7NjDnb3qxKz51DAw5iw==,type:str]
            - Dev Stuff:
                - Mend Renovate:
                    - icon: ENC[AES256_GCM,data:RLBsJcsySWvdwTgiuEe6yX/xA2WZ9qbkw5CRaXlHK0Wm0LQVtGHg0gmOfUoVlQ==,iv:LZeawdxppuQPvm/6xhM3kHgtmvBVSA/+ZATnnTYkMTY=,tag:JgcArBU5w43qZZ5bwaUL5g==,type:str]
                      href: ENC[AES256_GCM,data:L9tIkRB3BygPx94ex/8+0WaCJy1ArBF0OG6opc5wXyR8W5UrnOxycpSfiTUZlzmb,iv:WsAT3GEnBru3VjYkyS6GbC1ApTZ1E04wBTbBZgflLMY=,tag:WMuzYgeAQ3fsWwDWgirFCg==,type:str]
        services:
            - Unifi:
                - Unifi Network:
                    icon: ENC[AES256_GCM,data:/LDESnjNCs2iW6TFACjgC/5N22A=,iv:UOoQXgMqrKNggLs/NyeqfaAh31EJbOXxeyjrNkpX3ew=,tag:/HW5Jq7uQpM2sobrFcS8WQ==,type:str]
                    href: ENC[AES256_GCM,data:iXMGT/jzqqNEBtXncIawfdkFEvU0+cNwZwKxM6Nc43Yl8qFpjcPl8+RK4ykS,iv:tCvHZPy1UjJzfMnbxIIEIwFZWiaM3UjDNEba8LQqa78=,tag:B6AvJQ3d0NOJd8o/NPWMsA==,type:str]
                    description: ENC[AES256_GCM,data:BK+SKL1b/JcL5bnkVtBs,iv:nMFtDDFvoa1XixdFV8VGWACrTnBk4KFAky8+aeyRIes=,tag:dQTGLHHyL20gDNvqYWAaEQ==,type:str]
            - Synology:
                - DiskStation:
                    icon: ENC[AES256_GCM,data:1zSfw49thJw/uCvpaAigPg==,iv:0PCdHgnDxMt3RM2qsoaLYUIRQhYehMg04OPVVlT61Pw=,tag:W9BlOKf6bF1p1YU1SG4CVg==,type:str]
                    href: ENC[AES256_GCM,data:euhUNzNvIAvFM9wgEdfnOorPPfJVHBRk1A==,iv:1GhO+oJVQLUBOmteTxm8IFzs+s4LPUanZrEeRq3jA20=,tag:c23QsMbCx3NUeIS8ArwK6g==,type:str]
                    description: ENC[AES256_GCM,data:Dzjs,iv:RtdE7j1O1VZfwvNjAq3AUynqIVnXA7ERwvw4ExYGXPw=,tag:UiMfKcnZ+fnxeZqBVMe4MQ==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:AZDBHMZhzzfSjjvoIHsEGalsgkrjsJN1aQ==,iv:clytbC239jhZ1RCT0+b1Vnpgp1ngidgRIpi813dUI2I=,tag:SM3LVB6z1o75ysOAgNG6Vw==,type:str]
                - Photos:
                    icon: ENC[AES256_GCM,data:zgHeUvqKkPhVxtVxTQ7RZzO7eryt3g==,iv:rjCbfjzOjsdipjpnclQn0MtgcVSWbzKDIsQTbFUKKRI=,tag:KuhiUXKZcj72SLDcW9c5/w==,type:str]
                    href: ENC[AES256_GCM,data:9Y42GF/YRG0TMbfVBroYp9Hu1badhqp5KGE6KiSJ+u8=,iv:fXsE9WUG3FIEytlKuU97FwGSSLNn49GRjgECDyZpuhU=,tag:cDQJ/qSNhADL4rl6/uIrVg==,type:str]
                    description: ENC[AES256_GCM,data:WMA3DUz9Y5jvuM8EGopl,iv:KK4KQJWNFXOBGbDbFGq7JOE0Gb6mI+DptOa0pYDAins=,tag:0O0z6RkQ7wRyTM6OdE99WA==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:yA0PFKEKq48XvHoU5DHKTMmho03rzNdLU3wQu4468E0=,iv:qwTHNsPOeLLKrc0ZPwGbRFz3gO70g443NkBcrLH7qC4=,tag:rszwTTqlCd0WUBH2EDVhhA==,type:str]
                - Drive:
                    icon: ENC[AES256_GCM,data:LlkYI45SQ0pmnaPvW/limENjm6EU,iv:OtkYzYRlDgA3ISW4t6OT3+H3h8CBa08kyEWBs4nuv3g=,tag:R/XqTe41HJiH78BBlq5Y3w==,type:str]
                    href: ENC[AES256_GCM,data:CLnp4t4f2Kdz+ORJJ3uVtqdZEMWTyWSJLqT12IyIQw==,iv:47U7KV06mzGP5XKU2FWli0W0mWu3L8mpNppCI+Qp+8U=,tag:rjBFavjrzLKsbJ+VV90oug==,type:str]
                    description: ENC[AES256_GCM,data:vaKTsy+T4v/4Rw==,iv:mI+5lduO3IjiPOVCynRmPqxZuyOnzIOaf5ucMTd0WVo=,tag:8vFTGpWRcdD5TGz8tSSMcg==,type:str]
                    siteMonitor: ENC[AES256_GCM,data:htCnS/S1NCb7QRFwmxCv5Z3DIc5cIu01cDY14fk8HQ==,iv:5C30Fc0pBIUMADzTNj4aKpoanJ0JU6EHqMNoBJyQPZg=,tag:+cP8g61vti73VjBabUx12w==,type:str]
        widgets:
            - greeting:
                text_size: ENC[AES256_GCM,data:dn8H,iv:Pt5DDvQ2P5kfd9c4mLWP6DfXeWhKsXkeoGcwX3Mmlxg=,tag:eAIjCgFfcCqzyUNRGuQobw==,type:str]
                text: ENC[AES256_GCM,data:gkicEGa/43g=,iv:UFhjrbrvJY+PPB2IbcWxAZM4knqL6YS06wbgkGnEqoI=,tag:SaiJhoMZsO+TOQHMJvwRew==,type:str]
            - ENC[AES256_GCM,data:dbvC6Tvvd5cN8kYAoF8/nr1PQUM5gcqWr4hh/Wi1dch5XQkZX5Fpsq2KpRjaCmiVQ5i51s8sLfSfcJp4wjm/3q/dshsfejFN3Rg=,iv:lGeYcZPTE9oXm5owa910tk6oulygfx+u9SIxuAipRm8=,tag:FokUGlckD/wjWVKsVYiuJQ==,type:comment]
            - kubernetes:
                cluster:
                    show: ENC[AES256_GCM,data:zu7xtQ==,iv:iLJH8OLEhlP/BRkIQrxk9auAAoTn1vO8pYrVk9fUYtc=,tag:0kwzm3gvxHWUMQkfrF9JXg==,type:bool]
                    cpu: ENC[AES256_GCM,data:jMLdhw==,iv:cL5ruskHjiR513URqQInokSh85goztoNngjW4jDWCK8=,tag:nbnXjICc4OQUqPQQw34pnw==,type:bool]
                    memory: ENC[AES256_GCM,data:12brqg==,iv:V2mhiTQPCFrQJdvtmdzdjGAs3i7M3cbCWs7/thkECCM=,tag:dx3jECpcYQrIpK9uajv6cw==,type:bool]
                    showLabel: ENC[AES256_GCM,data:QD2ewg==,iv:yR4inV6Iy/E7x8ISWqWjRNNLDwkTPEaFUFqA74/vjt8=,tag:nchn71+HXLwEmO5SKo6WQw==,type:bool]
                    label: ENC[AES256_GCM,data:uwfTO+Eylg==,iv:M7Z+R9NQvvfseAheiYNB5O+id6uc3MUlpPSWiEHktoU=,tag:fKBX9MmRghTQsEZDzczvFg==,type:str]
                nodes:
                    show: ENC[AES256_GCM,data:dO/7AQ==,iv:z5LdP1rCefYuzqrKSriWgSlblAJPWlHpGS7goWK3CcY=,tag:VOV0H/vkQE4Wouqc3KXJyA==,type:bool]
                    cpu: ENC[AES256_GCM,data:GnoxxA==,iv:U99RA2IsQV8OwzxBcAjmgRbVzp9BUvNoVtesTwPlrks=,tag:7bdUydqDb6cZwpCj5zcJXQ==,type:bool]
                    memory: ENC[AES256_GCM,data:TNMnug==,iv:2ZV+GbxmvdIGIOulYDVALTP+SjeTorroC36P1YKQXFk=,tag:cFMYWF/qyStuCTuwiUOaNA==,type:bool]
                    showLabel: ENC[AES256_GCM,data:81zMPA==,iv:jU2SD4lZHTs+spXwe0r9HYAK0zRneB0eIvTX6Qhwp0Y=,tag:oCKOn9mBFoKGnL4GfJ0uNA==,type:bool]
            - datetime:
                text_size: ENC[AES256_GCM,data:tjk=,iv:4ry8V1XpUsZMb2AfjFPh05P/VdDZFZfcXkmwMAtZoKE=,tag:t1Wq8LydOGSn5saaQzGNqA==,type:str]
                format:
                    timeStyle: ENC[AES256_GCM,data:glLMPLg=,iv:aW1SScyNMOHMz+MBW0zFomKhUJPdINhTakVOLpYWyq0=,tag:qjnJFL6JFxCbSBVVFgXF0w==,type:str]
                    hour12: ENC[AES256_GCM,data:GUpfaA==,iv:gXabAyJIegGDfXHrmztdNp7Ju7Ch4AxCtybpeLw+7HE=,tag:nco+ahiJxnX/Bca+/KF8Uw==,type:bool]
            - openmeteo:
                label: ENC[AES256_GCM,data:iUh7iQyL,iv:co7Uj71q2q7sR7SqRahU2K4sVIMWev6xO+f/wWTOxo0=,tag:23EgQG/sJwvzktZOz1dkkA==,type:str]
                units: ENC[AES256_GCM,data:/oGEJCr+,iv:W9wZGSRTRQAuHrQ5J2dloeivdXUP3vjeWlM3w+36eIc=,tag:4ear8uerRF/gC2dQagFdcA==,type:str]
                cache: ENC[AES256_GCM,data:Ruw=,iv:Gh0+63/cn9D7aEx9tJJf6EKIC1dk2H9PYj5oVnyH824=,tag:4Qe5VxGE7Mv7osAcJLMw9w==,type:int]
                latitude: ENC[AES256_GCM,data:0Qcsubiq96mq,iv:KN7o1ur3cHIVX5QmvpIyZq4c6oXBWx+njAqOtelMHl0=,tag:S1miwahLUX+BPphEZ5G7iw==,type:float]
                longitude: ENC[AES256_GCM,data:gu43ZNThL9Fkjg==,iv:IC5LMn/F2cjpBEn7L8hWXW6gAnO5Yj85PGaJXBvFLe4=,tag:DAyqvniv/nVwKMGdV+IS1g==,type:float]
                timezone: ENC[AES256_GCM,data:1fAKGrbPNkVO+h8=,iv:fvE1kVxVK4ffsyu2NNQDJv2o7X6Pr2msWxl8rW8Hwvk=,tag:sOMuq81WnbWQVcIFueN1wQ==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MkF3cFNUeDlsR1dxRDhl
            Y1JkbkRPaTJ2dlp2TTZCOWRQQVlObHhMMkhBCjdUTXl6SmI1UkRnbjhOcjFhQjI4
            NGs3SE5ZNG9FWUoxNng5N1BJZ0VONVUKLS0tIENXOHE4MDVJK3VqV09jSjZOaFRP
            UXJhV0VOWk5EdWRMRnhsSjBBdHo1Mk0KDaMuuvJv6hMWCnjxRq6bO2GUY0bADARV
            Ui7di0vkKJ9GCK1Ou58IR1DmcJSAF8x1HabfJgrfo/18DJv8rHBVzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T02:58:10Z"
    mac: ENC[AES256_GCM,data:L0lEXuM5XP3gbx96++C1qpMM7giktvxaGZS/yLf1aET4JKP4G77ar0PweFFCGfwlWgiTw0AcmTPNF1vwFLuGsBahRnlHFI7nUMphXSh79IKsncaat7BkJ5Q0nEei3ugIRWDx2aj7og28Il71gjYRNco5kh1jM5cCGSwBESStXCs=,iv:KmI8xfAt4UTzlPPRdmm/dEPkWTz0NLoa/F1uqR4cWHs=,tag:iwXvd+P1ZUW78RCeQ2LDhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
