---
app-template:
  defaultPodOptions:
    enableServiceLinks: true
  controllers:
    filebrowser:
      replicas: 1
      strategy: Recreate
      containers:
        filebrowser:
          image:
            repository: ghcr.io/gtsteffaniak/filebrowser
            tag: 1.3.3-beta-slim
    servarr:
      replicas: 1
      strategy: Recreate
      containers:
        sonarr:
          image:
            repository: lscr.io/linuxserver/sonarr
            tag: 4.0.17
          env:
            TZ: "Asia/Manila"
            PUID: "1000"
            PGID: "1000"
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: 6.1.1
          env:
            TZ: "Asia/Manila"
            PUID: "1000"
            PGID: "1000"
        lidarr:
          image:
            repository: lscr.io/linuxserver/lidarr
            tag: 2.14.5
          env:
            TZ: "Asia/Manila"
            PUID: "1000"
            PGID: "1000"
        prowlarr:
          image:
            repository: lscr.io/linuxserver/prowlarr
            tag: 2.3.0
          env:
            TZ: "Asia/Manila"
            PUID: "1000"
            PGID: "1000"
        sabnzbd:
          image:
            repository: lscr.io/linuxserver/sabnzbd
            tag: 4.5.5
          env:
            PUID: "1000"
            PGID: "1000"
            TZ: "Asia/Manila"

  service:
    filebrowser:
      controller: filebrowser
      ports:
        http:
          port: 80
    servarr:
      controller: servarr
      ports:
        http:
          port: 8989
        http-radarr:
          port: 7878
        http-lidarr:
          port: 8686
        http-prowlarr:
          port: 9696
        http-sabnzbd:
          port: 8080

  persistence:
    fb-config:
      enabled: true
      type: configMap
      name: servarr
      advancedMounts:
        filebrowser:
          filebrowser:
            - path: /home/filebrowser/data/config.yaml
              subPath: config.yaml
              readOnly: false
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 4Gi
      retain: false
      advancedMounts:
        servarr:
          sonarr:
            - path: /config
              subPath: sonarr
          radarr:
            - path: /config
              subPath: radarr
          lidarr:
            - path: /config
              subPath: lidarr
          prowlarr:
            - path: /config
              subPath: prowlarr
          sabnzbd:
            - path: /config
              subPath: sabnzbd

    media-incomplete:
      enabled: true
      type: emptyDir
      advancedMounts:
        servarr:
          sabnzbd:
            - path: incomplete-downloads
        filebrowser:
          filebrowser:
            - path: incomplete-downloads

    # media-nfs:
    #   enabled: true
    #   type: nfs
    #   server: 192.168.26.200
    #   path: /volume1/media/

    media-downloads:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 300Gi
      globalMounts:
        - path: /downloads
