velero:
    credentials:
        useSecret: ENC[AES256_GCM,data:w09Wmg==,iv:P+Cl87ge0qrfvrBbsP+k0/Qfj3RZ5Er/jnHFnmV/1KI=,tag:RDLseGOPlQnoBPxyQ/4ZXQ==,type:bool]
        existingSecret: ""
        secretContents:
            r2: ENC[AES256_GCM,data:GeAPU8kvSCJA6CPs5hyIXjwTabsfw7sdaI87YPf4W6nk6eDw5CERNZE6v25gbKjaIJ0N+JSfzH0x7yubStTWwMys5vsEMWLc0trYwLg+FqbIBXs0A5aruSWMQA9Rbuca9niGjXUPdpHr4vaPDPgJouq834gNlTKj3NutaOeW5gPYiqzLDNXQng8razeTZa0rB93huA==,iv:IVvqphuLFD2+m9k/iR8rB9z79uWyro1YbT8G6ikiScg=,tag:x2x45wi5Ci7ww0WEA9mswg==,type:str]
    configuration:
        backupStorageLocation:
            - name: ENC[AES256_GCM,data:hYPV21xtyg==,iv:+qgmZ1w16uNdthf9EYU4aVobJnre6kp3I+OxC2tImJo=,tag:AcK/KKbTdhCpor10fUjdSw==,type:str]
              provider: ENC[AES256_GCM,data:M1Fq,iv:1BEQ5AAhoGkzCIKQm5D2WVuH5Yb3ZIvKYRJYPnEeTgw=,tag:BODOCUBe2LmF/GqT6P3Ceg==,type:str]
              bucket: ENC[AES256_GCM,data:56f+uf8l/Jk4S99UUzhw0+w=,iv:HPbLzSitRCdTWADm6O/aC5h572q84j4qaoYpuEtekzg=,tag:Gbv60X+2DpteBmkUzUppkg==,type:str]
              config:
                region: ENC[AES256_GCM,data:76pK8Q==,iv:3RreJ2AfyQI/joeKKLAUFHNN4TNbGH+Hs4wRJFf+bjg=,tag:DkTBMzDKIG2Gb2VyA8LmBg==,type:str]
                s3ForcePathStyle: ENC[AES256_GCM,data:X2qSig==,iv:7CZI+MdM78O8PiSgipMTZ0LHL+ur3vDrUNfVA3TOV7M=,tag:AetLiBV2+VUHKSZJVonLNg==,type:bool]
                s3Url: ENC[AES256_GCM,data:++b3HBhuX+BVbTSI02kJgfmaw93kyxt+RoB04tFCxyCnLG/vENWT7jLKaf3qiQPFJkPHYnzFnvwg0MtvrvWKAfY=,iv:WdvsJdllBrhNG6W8JwwOR/44xyFAJ1wiMNHHLMXSv3E=,tag:l9CMsGEALbDu5LKs85uqUg==,type:str]
              credential:
                name: ENC[AES256_GCM,data:p6cDzbO/,iv:K6KrRzTTfnKkSoGbvwMcdzuKbcOIxqXoTh32nFwdksM=,tag:RGP5QhgcpfpU+2epHBkUCQ==,type:str]
                key: ENC[AES256_GCM,data:m14=,iv:yphIViFXx/Ms6WmIgzBZcJmW9szh/+GZW1b0IduR+a4=,tag:JqV573O6s7MVvnAtIXqttg==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnanFwNlFickNJd2xWWnNO
            Szc2Tys3VDNlUU1ZbUhTRjhjQVhhbmFqcHdZCjRKbHUwYTQ5b2NzRWhjNVorM1hi
            Wnl0QlJ3RjZwZzQrWFY2NHFQYW80clUKLS0tIHI5YU41RnE5S0Y3K3I5VEZWbktP
            K0dPcWRVcHlFc3gzbUZFTzhGbVlkN1UKSQesD+NyVPcVxz8QTj7NgpAcm+EY0dC0
            M+fvPg4kLben63yWyZYRIpMIOnqpT3v7ZAzDylhbhtVn2WSLHnxBow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-29T08:25:10Z"
    mac: ENC[AES256_GCM,data:Avri9CGJa9A94a9Qe91/HyMGI5R/4zD6i8ugLQYD27oaAswKUAmK3hE/PvLAWRLNWjP0HOyvWlcg+VDev30TOhCJI8vNjREt9fZqDyEqnShXiLon8uiRuE+TIoxGWCJ81b7pdah251Jfs5LQxuEdH4ljRa/NhugjAbbQOC/rGK0=,iv:cUnnSPlC8TUTTlLHQQg6cZSbdqBfeaUvoAagvEzGQP0=,tag:/eA9ZTNhThOr0ohRHOghbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
