velero:
    credentials:
        useSecret: ENC[AES256_GCM,data:5Y1j0Q==,iv:LjJARlf/s4c0cVtY25koZsLVFa2R1biukLmVMNx+Vp4=,tag:RzCKpl+uaIXEsDoy2DNoQw==,type:bool]
        existingSecret: ""
        secretContents:
            r2: ENC[AES256_GCM,data:YzDz2xgNziwgJwMUh9jMhRYCt5b8ag/jympyjZnryU9y5MXcs9HReqnoejBR5ueBPhAtfmcpn1khmcXdDiAOojneZw2zm/zoqAJy9EDrFjiVkD3L7o+//oc0S9kRq1rkAQgmEknHzy57DUrZ55SmVGzUjandnAmAeN6ZAQ8fDDvJ7ed+hQiWnmfYTLNlpItkMX75JA==,iv:XKmOk6m5AQxe9svxizYsTK3/NIMLC+4x00xVXzemCQ4=,tag:N6Z7XnWry5H/pILE+nznMw==,type:str]
    configuration:
        backupStorageLocation:
            - name: ENC[AES256_GCM,data:rZL3GplAPw==,iv:N2TPwOAhgzEi0xvZqFmqOZVJchH/9CsV+DJgRnN3u4o=,tag:qUor8Kd11NKpEiXozjWbLQ==,type:str]
              provider: ENC[AES256_GCM,data:gHAO,iv:H1ssxm2xrn+PRbbaoKngCWirE8Uk6zUiVWzgwXXMBgc=,tag:T4p/A9ZtM9Oz5VLiWW6j1w==,type:str]
              bucket: ENC[AES256_GCM,data:hgLWWhDeC2cg8zNXceIG5BM=,iv:4SsUnEO485x/40p83x136XAD/bE1YkGzjDpLc7UwIII=,tag:hbs7C62oF2wMAfS3JP3f3g==,type:str]
              config:
                region: ENC[AES256_GCM,data:z3dbQw==,iv:dKvX37J57z1+bgCFivkUNJozslNAmk8JRpZvnaxjMq8=,tag:ySu7LmWxYDElh/IvMvy2SQ==,type:str]
                s3ForcePathStyle: ENC[AES256_GCM,data:d0Xijg==,iv:mwiwAVjmAZcg0+h4JaipVngGWer9wpPws18Quh64y1A=,tag:Grsuk/YuOeAcWai8uZ8rrQ==,type:bool]
                s3Url: ENC[AES256_GCM,data:FYCTS7d2+NZXK05n/pwLwTNegSfqbYXQnmjSNdkF4IsBMsHbKK3IsmWvkLNkHAJLjbqIYquYxhlxGXkzL8HfoJ0=,iv:/BIz8cZv/vaQ3Y0b9dYnrXE38Ov6aLt0AXbnFZ23bTk=,tag:hsXLLx7aSASvSQWAQfseOQ==,type:str]
              credential:
                name: ENC[AES256_GCM,data:QPGJBny0,iv:wtvbYfzOH1Lp7jLK28yuf+yaUVjrnyMQcRAzGGT4CeE=,tag:IvTM9WbzRu7WE1yM0+3v9g==,type:str]
                key: ENC[AES256_GCM,data:Nh4=,iv:UYUAKN3+lVVKYMlLOVA0AII/fgOWd0TyIBdwxSFd7Qk=,tag:VHJdGIv46Y0WORTaTn6KLg==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL3F0N2dMbTduRlhOSVZQ
            R1pzcjVsNEpZcHhkdmtkYW1HQkQvZWt2NGdrCkFLOTc4c2NVSlp2NFEyL2dwK1hK
            dHBrMm5OZjBoK1YwNkVUZmIxNUM1NTgKLS0tIFkzaWtWV0FTZ3I3UHJuU1hVd2Mv
            M2NsTXhydWUySVd3MUJIckZ2YkVIQzQKWtWCD/p7+MltZTLWtMEaHp3f7YpaAy4U
            CHOvI7smTskp5zse6R2QKvlnssSktkzh1N/+m9R1GXEXfZDKgr0r5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T07:31:22Z"
    mac: ENC[AES256_GCM,data:bE+WIJL8B8UtbSrK4ASIQBvyeppYvw4A8t4tjgmJCdRHE5DXtxUK5hHY/5MiKfg35dP9Mp2UmLaio3d6FOFCh9OhmCZ3g0o8b/XDbPl5F94op/+h4vWjwC3SRwz3VF6djLS5NRIVxXDEa6rWnHEKyYOPVxTdECWEkOYjo/mt4GA=,iv:i0/uIc+fpYZ076u8Sr16Jv96i/X6wWTuqscvZubAiv4=,tag:Hr+jk6oxMhr8mct6JSImNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
