apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-root
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/mjrealm/robin-lab.git
      revision: HEAD
      directories:
      - path: k8s/system/*
      - path: k8s/platform/*
      - path: k8s/apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mjrealm/robin-lab.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm:
          valueFiles:
            - values.yaml
            - secrets://secrets.yaml
          ignoreMissingValueFiles: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
