app-template:
    controllers:
        main:
            containers:
                main:
                    command:
                        - ENC[AES256_GCM,data:0FJ8EuS+31/+Qc8=,iv:gCk/xO/PNwqaVXRhVr1uyuQ6/pKxkQrhjWc8vLuA/Kw=,tag:q9+jsjYy30mVOk7x0Pep+w==,type:str]
                        - ENC[AES256_GCM,data:peOk+9RM,iv:3qg1ApNqpWHny7htxip+AXMclRVykMyGg5BUwLvgjUQ=,tag:iPlFobAp3X6E5mHuEQEsAA==,type:str]
                        - ENC[AES256_GCM,data:2U+5MLOyy6x/,iv:XaxYJBSrg/xB6jvo3pmvQBqpcSBtWYD5avB62dSJfGw=,tag:5es3ViqB4kC3UW3nfJo2Xw==,type:str]
                        - ENC[AES256_GCM,data:VUbsmr4U9MGWqnqa,iv:R2BuyzcGDlxj59RAEXwLyQX3ebHApxBbR6ITS5TzPwc=,tag:uzSigjHl8FQJtqkjngjTnA==,type:str]
                        - ENC[AES256_GCM,data:Jldk3BozG5XwnxAjxLxa,iv:iA/1BX/lwXOIpV8Glhhvr50+M7p/v7OEUYqw8ZB677c=,tag:QfIcnluJcuCOvtiTo8vEGA==,type:str]
                        - ENC[AES256_GCM,data:6ZOR,iv:V5JYWDN80NZjZOVcTj8gZX46vOYskC4ssgh1fD62JLU=,tag:R6g1tu8jQwF3TuEDOqmBPg==,type:str]
                    args:
                        - ENC[AES256_GCM,data:g2WfUmq6fA==,iv:ycD/c/JVOGrbyoDwSsSBqxzBGdWCMU9htXBTgei/Dhw=,tag:Q71L90+n/bPMG8pRTd5yBQ==,type:str]
                        - ENC[AES256_GCM,data:vJfLhQqRwnOTjaQjk5+pRxRwyjw68b8AD1MpE9mf+1TzpS7JWPZV4nwcd/n8z3bS5n8C6JI0fOC5dc4QghYDH/7dFXybHKmUEzRqGW6Gj/NDgbWpuHxWvX+6OUsx70DDmWc/7c83ZdeENGI9Z2/fPxytmcPrA0SReuBsLbAJD3Q/gKD3vvWZzGLSiNn1TIIjk1Tfs0O4rGaf6I1U9/rCUJdWL2epxfPLhBjtiCTr165TsVC8qFQY5g==,iv:zh3nfUCKuyHDsiZjDxMnOV+tJk2WERNREbTAkM+qhO8=,tag:gZho2U51j88DrdoBpwKbaw==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaelBtV1VpSXhJQVo2S0tD
            ZEVrTmRTMW11TmNGblZuNzlLcVdNRUx6VjBVCk5wZUZFeWRidWFSS1hmNlY2Tmll
            aDgxeHFhUUhpYXM0KzFUOUpoaUVXZ3MKLS0tIHN5WitKVHh5cHU4TS9FcXI3R2V4
            MkhMUXpMNXUvSXdjNUhJeG1LYnBJVUEK2zZ1Kb/voofhAtEXNCnLd+iqshey4XlR
            G0NFBsU6J0YIkLANtRD9G16MVCkIKiqxWs0AOPqYfjhjiGuLtxf9+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T22:05:49Z"
    mac: ENC[AES256_GCM,data:dQzAmeuWxYkF2VKE6n85jwcjkdrrjrV7Wu2o3Jn9fxARb9Sfsd2mloSHLH5visQUJj+sGwl3gSzL+2Gbl6PjL6FRothLAg4U6g6gSW/gnZR3jJMAyG7UkUX2i630AeLV/Cpn1tFdVz7RBUxtcTVS+4VVThTDQ9sI7Bzt9sIQuC8=,iv:fEX1B9EDqq+uL7XIxW1O5kPa1sIxKZPwLageDarTMyw=,tag:P1tc5tC7e/oojSdv7TO3Jg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
