app-template:
    controllers:
        main:
            containers:
                main:
                    command:
                        - ENC[AES256_GCM,data:5znkP5TQkSh/HpA=,iv:QZP0seadbtAEI0iEXK3t/FUL7e9hsMDKj9Wz2EChEd0=,tag:2G8NHg/q7YsKpeES5XD70A==,type:str]
                        - ENC[AES256_GCM,data:+VY3dPjt,iv:eaOqE3tuUp8OQ9BSuZmrsF/nhNbBkmpBiC1l7+xbloQ=,tag:m+Gs6/WjN4T7nUaTsLunrA==,type:str]
                        - ENC[AES256_GCM,data:Xf9lHKPULe/K,iv:BZT1yDHm1nlPds8annVprTVcqdC4QWQSe7osdC1tB2Q=,tag:9l6GEdJ16eVi/83JTB97kw==,type:str]
                        - ENC[AES256_GCM,data:R8itI8LKf7IlyBTj,iv:N1HDnJ+UaMQg66dZUzBGJ5iJElGTNq9VkBCnZLX8k4M=,tag:QpSt/QLxu9pPQLWBgtvibw==,type:str]
                        - ENC[AES256_GCM,data:NbawUe+0mB8A9h76kwkF,iv:o87IsCxP7cvXRx85cMRvOJL5ufYcPcjFMiwNA9L6D6s=,tag:yrhSPPoUC7zWPFnoS6Nm7A==,type:str]
                        - ENC[AES256_GCM,data:OHOX,iv:7KRnrngdP/zQ6cog/fn9x2RLlfM8OiFQ0ePAP3KotDM=,tag:biwQG9aZNjdMHDmlcrMavQ==,type:str]
                    args:
                        - ENC[AES256_GCM,data:e5THzGaTdA==,iv:WCpSvfKoNr2MhDHH0Hil8LTIH7jKvejic36SBGdg4QY=,tag:N5KyddXEgturmz4mpVxhTA==,type:str]
                        - ENC[AES256_GCM,data:NSrlqVdKW6Myiipm68q2vmmfKEw0lJFRr0SPwzOJQH+jX/+Iki8V5a9YSW4/I8+3QW6XLAp/2p9g0DGVb5jyM6b1neZmPtZtG++6gAaDXSCtKBIV9brI0Dvz601I6EgZKlb1uXzUbfNm5NDUYkhX9hoEREhbmtORS1PoIzYPjupKvt3F/eWhb42ovLhiFq7MLVoW7jPnkYhA/mAxFjyR5eqS6tQuNrx//AuvKbFu4BaqW4EgpBNXoQ==,iv:mCwouj3ZYN2p4VivvctCIFP3ixz/CmbGyZv1+1iYnwE=,tag:jbuv/4/5NkedsXKVVCHW3A==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXS0FlRkM0ck4wblFvak05
            OTNzQThaMkhQMkl1R0R4WXJWUXRWbTR6Mm5jCmsxZkpZREJNU1BwOU5jdGpkL01T
            RWxxTTdJQit2TGt3ak1XZHd4d3Jad28KLS0tIHY1VDJmNXA3RmJUZFJvWnVML1ZC
            UlgzWjUrNE5zY1lVTVUwVGFsam1yWDgKnn8U80/f0u5Td4iN+RjdP8xEgaHDUlhG
            Zqg0IVr9jnhDSOecP1RJFIefhD1IFNN48TMU5sjnU2njcsRO+SV0LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T22:20:29Z"
    mac: ENC[AES256_GCM,data:zngQupkEa6YztQW31Jlp/uXILdajvKz1oGlssk4kwnDSHS/KIH14SlpC9PuAIbp7Sx1TkPvPJuWtdDJtT3U/92BfHHxjK/Dw1b1vDehoyxPK/2hpN2rLB2cX1ypQ7UyAHNQnWRp0jCVa3aQAdFBO4hej8hW7OsXr8bLHg02+0xE=,iv:NTUQRLlIGMGvl95DmMemzM8STXYqAFp1LFjeh6SvkZ4=,tag:qdLbEJQQwhCxFDQEW5wzdg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
