app-template:
    controllers:
        main:
            containers:
                main:
                    command:
                        - ENC[AES256_GCM,data:dipL/GiuTQIMKmE=,iv:Aav3XF6xrupenaKWy3+/YJF5dhnBB2YI0b39DgPY4JE=,tag:cmXCwEaNKVhiHjAQcB7JtQ==,type:str]
                        - ENC[AES256_GCM,data:GsUoIsx6,iv:KvYsb06RCkpGSdHTIHle8oW9zzya933PuRmaQyYWg8A=,tag:PRwu+kDfYXRsUk8WczPQ/A==,type:str]
                        - ENC[AES256_GCM,data:/O2cuumAgsMy,iv:DExoBQ35V9we8ba7114okec9Gc20IDrKWBZ9zE8lSm4=,tag:BWnlvK/39T6qB7DJ2kzvBQ==,type:str]
                        - ENC[AES256_GCM,data:9IG9ZMdLNfk1yWNc,iv:IPfYeXmRqdFL06lX9zLXUCFoQoY3KdWHeXR17o710F8=,tag:CFDy0cZBGSifPqmIhRXAaw==,type:str]
                        - ENC[AES256_GCM,data:TuiGb1Z4MNOuzrjQYbwl,iv:aQ4q8e4JvMqlYhXLdxEN0j0s/9NqA7A/gPQOwef3Drw=,tag:VR4DpIqFJEHkkuaUNQMA0g==,type:str]
                        - ENC[AES256_GCM,data:h1TU,iv:kINiuieaYl1CtcACEVF0X+O33oUoeuJVHhqlMA+FerA=,tag:NewdwEt7MELlP9EINEhxnw==,type:str]
                    args:
                        - ENC[AES256_GCM,data:2GRJxzjoag==,iv:L68l2cKOjaZuIWdLLgapYWTpzrv4P4ALqYjdKAGjRhg=,tag:FpdeZ5hrCjvRvgcPPQByyA==,type:str]
                        - ENC[AES256_GCM,data:JIRpOiPx7rKXoPE7by+VJuI4xxel0b1v9zRAV5IbJVmnS4bn2b1kFhF3G7j56ZxshNfd+MDIehUqh+P/AuHvwd4PZ7RUEI/sVLFRPD6i2J/jI5OwfRNv/waS72mMEjz0IJ8meyTnjJMSdNQdwjLqruN44h5OEHTlKUqLOgtWbzKo6lK6b71w/BNgOSN5SCK32kPCNb+BMsQhTYkNpq+/yFP5pAUhJiv7TRsxak6JOiAWmu6dkwyoOg==,iv:IX1AWBwnraCmBXzOkGq2FzrrMumQoQlrEFZrOTRzvnE=,tag:kah2O7ZCRb0KRijt2hAkJg==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2S3BGenVLN2NoTzU3RDZO
            LzdTNTNWeHJVb2UxTERXZWRVT1pMNzhLN21jClBZSFJXdnc4ZTNYTE1FejR0V3Mz
            SGhaZGRDQTBRZjJuMjlmZVpGZjd6REUKLS0tIFJ1ZFZmdG1KWFRaYm5CWlY0aGdq
            UXhZZDc5OUo2ajg0Vm55Y1JjemJYQ2MK+6Q9340eA/R5rSQycn4Lkim8zv8XtA/9
            lExIaSpz89EuIHMnpi0FjLMlTj/11Ti2BalQDOkMaoTAP6LxY/TzSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T21:30:28Z"
    mac: ENC[AES256_GCM,data:C2jRMy1+xII9x/iykazqGZ4Ml4S98r4QMS+kzbrAPGE0BPzNRHWgn1uWZprYDx6ZSZzNfNbu9ZQdodBGVppdpWxaMMK8YSXK8ZuKpOI/jC1Crdv1IJPbvDpRaPjEz/RZTruCvSm6PDviWedDCXDhSbbEbKG8ciknNv3iJWx4wWI=,iv:H7pMY9hz7azces9kMWDCNzEAUpRzUcY3y/3WL4Wq9iw=,tag:rWRt9Fo8Zsk2SF9pfbrkFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
