app-template:
    ingress:
        mealie:
            annotations:
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:UkGEPlaV,iv:2nJe42IvtATDGrLZk7nwqGbDY2xgLgiSltYxuUQ/4fQ=,tag:EH65feYY5FS79GCOMNT+YQ==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:09jAG8iiVbP52/J7C9IA22dPsqtCj40dUCobwwWZkYb7,iv:ip1BygpE1CoSczJndM1jP9EpPBDXPJvp50qyTOkLs2o=,tag:nN7w6PGYCx8lnWntTg8qGA==,type:str]
                gethomepage.dev/widget.key: ENC[AES256_GCM,data:4/H3an+K6V2LijKxQk3IfLcj9WLpZNh1pdouBPaSLheyz36XpCKr0gRqYf5HpasWooTTcV6KulXilyeQn21wLopidCFBjZWE+edsT6JqXn7ywR8iIjYtT5YpXHoAcnNOOC7OCqbovLMYIQRdBlkbmZxq3Prbf24j2zux+FMto13CK1BcqQxxHUGmdTrJXgI5ZFVTtOrlcD1xZFfrngtdTvk/iXd/FwXtuNktKInk5nkrp7XQC7DawA8C2Otmt7eE94ciSlDg++bPf0ng0/NDT/jPBoCDxyyC6uf3WmMksfUHxf3LOsjKDlmyyWImpZyGBD0bLRB5nMI=,iv:WkpxhHR5adX3jO/n0UdFLBakACjuaPpMSND9srsmfJQ=,tag:SGOXC7eGFvy8Ic5NyASERA==,type:str]
                gethomepage.dev/widget.version: ENC[AES256_GCM,data:fQ==,iv:6XeF6/qJh/8e/1A9/pBctyWm2bzYkiwOM1Z/ieCH9Uc=,tag:iTWDQ3paIrX6CUS0ttpu7A==,type:str]
    controllers:
        main:
            containers:
                main:
                    env:
                        DB_ENGINE: ENC[AES256_GCM,data:noLf1vG4fAY=,iv:nObnuEsDSC4ZXUryx6IsklAeMIrtswW4vCSO8MyK3rM=,tag:61KKej8TbuMrfGCYPhRKnA==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:3UmdYJ5G,iv:hvJa3TZoCYqskty5GBLUCMUHTilEgf9xphTcmkGOWFE=,tag:HD8SRnIFnkL8eseqI+CiPA==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:lJLELbRGcRgbT5dGptydLRPiKzyXaGM9t7N59TTUAkc=,iv:7O2bOlzLemuU4pXVREe47FTB2uWXGL6ARswJ/ngnfMU=,tag:oyYnXb94mQSKbJl+UIB21g==,type:str]
                        POSTGRES_SERVER: ENC[AES256_GCM,data:cMY12bQ1hrGUSXzoajEQ,iv:pu1RwJaxtcpa8HWL3qYAjPg8w2zOjXaWy3+n0Taic3Q=,tag:7jfkm2rVPiruFroTpHZCsw==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:6/UnTqZT,iv:Sp90NJhMQYSDnNDEqEn9xzTS0xNiGYLd/Jht4cefA5I=,tag:BhvXxGSbOOIAetjjGJ1BcQ==,type:str]
                        OIDC_AUTH_ENABLED: ENC[AES256_GCM,data:zmojaUA=,iv:Gn9aqlS4xqUBnzc4DMhi5sYA8/F/vY9re8OAn2aglBQ=,tag:Nsqceec14ZFxB/OuArytAw==,type:str]
                        OIDC_SIGNUP_ENABLED: ENC[AES256_GCM,data:uB6fBN0=,iv:KjPJ6WD5kL+rNfqGPOS5Tw4VY7WDS8PNjAAVmHJ2OEM=,tag:OPJpE06/dQuBRV79fhhnLQ==,type:str]
                        #ENC[AES256_GCM,data:X8tm7Giqd2pNRAKr4oyeTmsaogZmVDhrFKN23ocVMr1+0ix5bc9IKrMN7S26sF3oOy+tSJ1W59UA77NSd7sPnew3j3maK50vdVJkzcdxU9OdK0B5bZYgXg==,iv:9Sq6SxAvvEqrNJgRfkjBQ1Hbqtv7qRgepSj1QrKWroY=,tag:Kck+CplYZDzMRrGh9P/bcg==,type:comment]
                        #ENC[AES256_GCM,data:3JzdMETRzQCAMvPSPyLByazhw4CsD8qcKImiFYtZaO0aEPPmiPXtAcijoShO/4qDAfdJ,iv:41n9vezLfFDC5Bjnei14FYVIW+HSgSFFr/ltcRegeDw=,tag:o65uXOH+jGc+iOrZY9gJ2w==,type:comment]
                        #ENC[AES256_GCM,data:wlW4lL9/P5mpP6DM645EDKYp5Oiiokq8TdVBfBu9kY0PQkQ5kbDd4nDdHvIU7PQzVK1/+uMi1Tfl/kVnEXsprHWLu8x6BSIEd7bKuSRz+IY8DSwlC5oW,iv:urKwIG1w/8ZEmqS34e9JpFNxriS12aHBdH5W0mfdqJM=,tag:bxLTipGsK7UlG90TuP30Rg==,type:comment]
                        OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:fo0TwL0ZzArVtqjSG8WqOqee6yu5o6J93e7cpiUEaJpF0CtDiuSwvcLx1uXCGK4C43rA0Yls08vDJU5YLVlsgi+Q,iv:pu/n4av5QqBrWySir1QbGrQM2GI2Y09ssU3eC9SStW0=,tag:vSgc/MedSuSbOXXlTlLCxg==,type:str]
                        OIDC_CLIENT_ID: ENC[AES256_GCM,data:9k88wqTDoIf6gsjME4tiAz3KBBn2QnOeNwdf8LVNaZ2qhG/e,iv:J6CP/0d6KZ4qVCoIbuGnEbhEAMHpVPJ/VYeAyP7sngY=,tag:dbUxQy8LnKOwGjz6+hSURA==,type:str]
                        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:UTeRV0Ww8u7dD6FmLisNHh6KjXvcWKqP2rYAiGWuW2w=,iv:9AAh/p0+yLNKrXYZQVTFPM9hdYZIUAiSpLxkdKcjaCc=,tag:zuob0CGpEH0ELIlZ5TDgbw==,type:str]
                        OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:xi+VDfJhVtDl,iv:FkRqH1/Qut9PMCja8GsyDhq2YJaM1aR/9khdKHtwMl4=,tag:jwwHQJqd21OWMCXWFBr9/Q==,type:str]
                        OIDC_AUTO_REDIRECT: ENC[AES256_GCM,data:ewQuWw==,iv:CbdEOOUPS6CtPcJdw0ngBVIT+lndLFXFfN7TZCLlvxg=,tag:jXlsCmamI/NfG7Ct8udqdw==,type:str]
                        OIDC_REMEMBER_ME: ENC[AES256_GCM,data:0O4CZQI=,iv:ENj0AgQ402vC5OreUbmzzaySfrQuQacE/G2XupQLri4=,tag:DZnkAKnMvXF7g/NZrSyHVA==,type:str]
                        OPENAI_BASE_URL: ENC[AES256_GCM,data:Wq37BPvT35YA2D2BvAu/2xrXHBH9dvGiw1rd3j/4JrO5suvf4wGdKApIp6zx80Le,iv:VsBYnMWEiUc8IW/O7cCIGYA+k5vywQ/eXG3CihM+rmA=,tag:mh5AIfDZdSI41Eg5V4bQ3g==,type:str]
                        OPENAI_API_KEY: ENC[AES256_GCM,data:Zj6NqKVEw5F9Zfu2kox1MFnIc4/z6p+mYlGVJabdgZ9wSJ9BbUNF,iv:UxDGwf8FfqsuWbFltrRkaHtok4mFviZU6HVLbldErl0=,tag:CbEv82PB03Gc0iVRSsrv/w==,type:str]
                        OPENAI_MODEL: ENC[AES256_GCM,data:tzcuKEgRwTg+yiC5yt7lqA==,iv:VP6v7Ii7HgnV9y2Y0Gz+ySld4xuwMVzX9c6BQUh4PnU=,tag:5uTvX3FTrcHCyti1pEEMIg==,type:str]
        postgres:
            containers:
                main:
                    env:
                        POSTGRES_USER: ENC[AES256_GCM,data:BqQkjR0a,iv:YOXeiGYDIv9vqffEjQ0qTPy8s7XlwETa0rZTqWyUHG4=,tag:+bwl1y4JR3ITNUrOygAo5Q==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:4f36IqmGNZmm1iNaRZj13vZdZ7168ee1WT4MdnWOJ04=,iv:hYJuVtwfxkHuceID8E68teP8yxJF3zOyO3bgdswkbHg=,tag:stvPeXvAd1F5o/Fr77f0IQ==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbEkwNU1lanZBMHlwMThp
            K3BqRHN4K29XL0ZKVExuYjBUczRUSGZuUVJrCklFMHYyeWFNV0FlclBwT0NPbGUr
            UzFIMGNPZnRQNFphd2NkaldmU0JpUWsKLS0tIEIyMDkyZzlEUlJNczJMY0svVU11
            bi84aGtGMlpHV2xYaVNuclNjWG9oRUEKotyUDBqNTgbgXcwX9XDAZJMvw0+jU7DJ
            q9vKj9riqm5SXAEkIFqYmJ/HH5NDvjGUOhAOaCfSkEnLkfmeeKTQEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T01:34:52Z"
    mac: ENC[AES256_GCM,data:yPNLQtpbZOJnsLM5r7sxlgE4/EcA3KzZTzYH/gkrgTas3mB0h4laSsgsKFeZRHD7oRcmoFh/CBRlktH6KaX/pvDihMYSSeeGqccGgkb2AFm9Bbl038sAXZ/O26OFA3WerbdstDLr6vP1nmBTj3w5RBXRG0RdWSy/MjHAcb/LBKA=,iv:Iz08GFM0QAf3ls2hIucR+HK/kNxpRM4pa2omOs0wcxM=,tag:HicKNhkTcroTQrYEPJ+a9g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
