app-template:
    ingress:
        mealie:
            annotations:
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:gJQbFQ98,iv:3KlXxu9Jq/Xjhe9+mDehqQ1TMdlfnBxFmMjSAHMJekA=,tag:iwUBQ+5zcTebQMYpXRelew==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:rA1+v+8quX85srQ97WYMvlNdXvwhOlFqgusSL+rzeZuW,iv:WO+lROPji9hLR3Lvr2MVc6PaPEKwrwY85kVH7JyCgBQ=,tag:2AGPWg0/AgTxRr7vtMFjTQ==,type:str]
                gethomepage.dev/widget.key: ENC[AES256_GCM,data:eGyFZN/b6NbKyBwEs7Wz8qFvUMlhHrlF5HjV/kPOHDRATsVxzXdX0UWOJ5jzUrRPBdgH32aF3xlrt+QU0878A2fUBjDB53igNDuHJ2Ao5pYO14BgwBwTWhPA+IHa8sT76UeQgl2BjFafoioq8/B2qT8dBy3+jHUquqhisfRM4wpXPczqCVuEu2usf0oT9GhdxtucKJVDni9huGL06uUEb3vH6An7cRSBSIAklbD26eBoyVjbxqgw3So1Len+Wdh6JKCJC1UJlR6Bql50nmeEqpnEisHZqy1HqCjRZWSrgStQbdlw+T5zT65IJjMIpjhMFawDqcxvli8=,iv:YsaWbivZmZM9ui4XrI2+P79AczCVSU6alcFoecBCigw=,tag:QIGoltSute7ZrLGPkzNLyw==,type:str]
                gethomepage.dev/widget.version: ENC[AES256_GCM,data:1Q==,iv:lyp5nE/TarJywNfG+jrgBOJdCVyWHltbKoD3uBRb2mw=,tag:QJ4M8j/YviFLf3ladQcXpA==,type:str]
    controllers:
        main:
            containers:
                main:
                    env:
                        DB_ENGINE: ENC[AES256_GCM,data:+ieKoj0Lqqo=,iv:YrPaq64FIJEawUW3p9QLnbihMQkSSQtrwvI/x9Wej44=,tag:Z+3takJngcs8q9OlXovTrw==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:W+8kFZ+v,iv:YyTOcohdo7JfAupei/5O6mpyBtqW9We6+L21d1drw4U=,tag:rlmXbIJQv+FmERWqKG/09Q==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:pl9N4L31zf66Z+OblA5I91Y2ZOJMWtRno46aqhKR1p8=,iv:d+IPHTW9UlM5KUoBlf/GPqGkF6EocFEYfk+v6kag+kQ=,tag:pXdUFw47LmW3cXy1G/cTew==,type:str]
                        POSTGRES_SERVER: ENC[AES256_GCM,data:U4s5Cyiaj9Xw9ffzlQWq,iv:9N4dne7iLI2QpSBr1P1epbfhf1Fx1p82IuzrLZ0Ko8k=,tag:T6h3G43iGcff9Dd52HJ7hg==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:d7lQnRV3,iv:MOZfKQZxd+ukrebRsAnRKo1Ulf4P31TWaymqMM2iBOI=,tag:qpfnXKqEO8xRWnOuJ5+q3Q==,type:str]
                        OIDC_AUTH_ENABLED: ENC[AES256_GCM,data:wrWq2g==,iv:Josq/NRbFf21WjVAQ8OifLN7YZQ0bjj20h/WE4vowUg=,tag:jWodaWCCUSD0yd5n3qsBLw==,type:str]
                        OIDC_SIGNUP_ENABLED: ENC[AES256_GCM,data:UeG826k=,iv:G+cipET2SX+pL96VcGIsvnhN6NBggSaMbo+OywUolqk=,tag:KIxBLz8i0y4rZl9upMPsgA==,type:str]
                        #ENC[AES256_GCM,data:Xnofl9E6KIa8oZamFfeftBKgCjYTL40amBqVIZ+FndLh3YpFhu87sS+OjzUwFrbCRt4As3mOuW/8QfIvTF/V3oeqH7nvdEEtysl7eSmYm0wNWWQg15vBPw==,iv:SH7u31rTdV376PVvU+RbRrFtWfn+pDMeWro3FziHWJc=,tag:L1Q31vcWwuS7KWgt9OoYrg==,type:comment]
                        #ENC[AES256_GCM,data:TYQjuSkj7cMj8c10VqNBQsIG4PycYuPynbYTuVpIoIEcyRae0RGiNLXvLWEvNBWrUb3N,iv:joDS+8EIKb4RlAhk0uTQAbQgdeNA6Bw4HAWM1sdZkeM=,tag:fYoTWVnAExm1aqte5/sBIg==,type:comment]
                        #ENC[AES256_GCM,data:wHO8X6huohoy/wo0MRaAdmeIiSH1uOqZdqnOTrzizG1InZ9NsRYeZE48dLEWV2LQc4CjcuqXobV7tXqubQ2HUc0hZmsLAHM/5dghwSFoV0wckh7TuZVk,iv:tQ/kSpiqnBi3zI0F3JI6CPYkweIfcvO42xCBCz7E9V8=,tag:3cWjaBxEF4f4edxdLhLhTQ==,type:comment]
                        OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:EQLdC1m5ninQ17OUh/CjDvfoSOQyjSHD7rwLtCAx4fUIuOx+sITgIgj20B44vlkC0WNibu5PhvJzeuteRtQ4d/Q7,iv:8L1TZLWh6rr7LAOth+MH0E8qkmEjnHD1hoebqADmLvA=,tag:FsYHNCFmrY1GWy4Ki22lYw==,type:str]
                        OIDC_CLIENT_ID: ENC[AES256_GCM,data:BsVJMqWh5KQtmnR/7YvvXmU0OVXSog5aT7RwKvCyJR7Tnyp/,iv:dalCaWqBDZ8+APLZ0tYFTgXQhm06PQ5CLDrpkc6vzTM=,tag:8MXWuyaBv88gcoLgXxoqHw==,type:str]
                        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:MRu6soGsEdG7IYp4eimvbgtAUfWdzuorepiL5kY0cNA=,iv:fkNPvEDtiKX9uuxoYKObddTdO6i+ZNn8iX5WEVUr3QU=,tag:cnRljasQ+FoQOnaL2oOyeA==,type:str]
                        OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:Nu/UrQR0doPH,iv:eDXA8TYjc2MYeJl6L3MxOn6mrQDgsbQvmN5/ux4gddU=,tag:I7IEB3UO1d+faFdbnngVlw==,type:str]
                        OIDC_AUTO_REDIRECT: ENC[AES256_GCM,data:LJtC0A==,iv:htBm2EWclP5R06hPLIk59qI2tDaxH7oGapHkU1Zhrhc=,tag:PjCkU9Vilhc5BER3LsJbuQ==,type:str]
                        OIDC_REMEMBER_ME: ENC[AES256_GCM,data:pQHhbiE=,iv:C+iiHuRMlVCNqIZvCp3I/wV8hIGqWWYl5vmGRDP1tzA=,tag:oMDSiXWo1ij9iqM1SnZKew==,type:str]
                        OPENAI_BASE_URL: ENC[AES256_GCM,data:WOCTFusVws54Kh7m9RciHAuEARERA0hc1NSACKPHKOhHAVR7bi3HCRdha/7C4rot,iv:iwW0+BnBMuSMrEp/UmUapYYBkwociwK3DAn9YBBrr4s=,tag:XJpapUabM2GeulP1sL3Bnw==,type:str]
                        OPENAI_API_KEY: ENC[AES256_GCM,data:zMN9gZJifzzgDxfhW/STQsc5mHYJtmD3LwRlGZDKjWSO8xZpkmuu,iv:n1V/7wCX59AlQZDJ1OsWQ/dPmfa9F6u6IeCNAJPOD9o=,tag:LQqbgFiyf8209sQv4lPTgQ==,type:str]
                        OPENAI_MODEL: ENC[AES256_GCM,data:Ioahb5+Nde8fv5CUbCLkuQ==,iv:Yxok71FJM3sbC+9N1sUZ/j2Us0VMf500KgDJOnTOPZQ=,tag:AGyIHr518bp/OEt7q2z18Q==,type:str]
        postgres:
            containers:
                main:
                    env:
                        POSTGRES_USER: ENC[AES256_GCM,data:Y5nsMQBM,iv:T82TBvI3VQPyZmJoL3mRbvIcuDIa/zuwc5pnYbnFslk=,tag:zKsa+KeHIZ8QNKOMsb7k3g==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:hCWscQa8gIu7Huq2U1NGvfcSmDVgqB4ErlByBC4nc9M=,iv:pzsd6V0ay7KZh4Rl1SS2VKBIGYD1dcq5oXbFneFLoDU=,tag:5m/XrYD+EJR+GMtt5qM5RQ==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UXNSbkFJbURrNmdGT01P
            bytOUUdGaFU5bGIzcjZrWjZ1dkpXTml4NjBVCmZFVHR2bkx6enRvVXBXOFc1SHFZ
            WEJKRnB3T0o4R2JNaEk4L09FN2t6a0EKLS0tIEI1aXRDT01KNEN6cXg2T1ptYytI
            eGFlbW9lcWxjVlBJaG9YN3d4VkVPMEEKxFokxQKRTwOTeJtEYXPIRwWDN8FDTl4u
            iNqECEiHicat4eFiZLLNtiIeim8xK26C/TBab8mspZzkRde4xFkJzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T01:23:10Z"
    mac: ENC[AES256_GCM,data:h8gMqa9oJzUTN2D+NuGtpv/kApzVXHztnjfQNsSQbGlTm6IUqyqAOphh7m5tF90AraWH3gNP2rgm+OPPMo+nPZXQOQm0qXQt7ym9oEQB2peQrOQ7c+ftWvNX4VZ3Zo3ikwJSIkkJZXfx8QIEqFEzSJiuLdrsWGruO/VEuSHntVE=,iv:SQf94re4++rhg59Dfk5pSStpMu3n05Ur00MrxWi07KY=,tag:4seZT7A6PXPF5uKzubCTFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
