app-template:
    ingress:
        mealie:
            annotations:
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:0DSiXyA4,iv:MZv53C2ZR97nJbL7jO5x4r9PXtOW2lolWeoQsjmy7oI=,tag:8mT9revvBe8V7wOBQ81YIQ==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:5V5zySp5lFHahLG+ShxwQtIgmXN5ivNsX0AQn/pI8WYD,iv:7N0LLo3ffYoltdNTvHmeIYgM5+nQ7AgCtFmcDLvwJgw=,tag:0mSHo41HDq93ZTlWqkdN/w==,type:str]
                gethomepage.dev/widget.key: ENC[AES256_GCM,data:xoEkR+tnMhry9amRHZGyOvgj0usxReJpcc6nPNjW2i/B+vtiv8EDBr7jg+TmWqSchwCrfpxDGdCkLu5Z97QmF9tefZJ2Nv9OW4zmF12c8drixE6/llh7x2tSMqzlKdGDSrtPzeYhFyuNufxZvW6ENVgJBTkJZXqH8Zr8seJPtXcd/1fI2bHat8w9GG5PkJ4DzJp0RNNbsAfF5MYpm31TOlfzHP1O0QTWZvh6ZWpqCST9D2P8I0df+XDSGh2mdaRsYRQ/yl8v/1zhLXqSvIKP/zRyw6PpREmea+MdcosCA6OyzUqu7cvQXs/XKeDtjiBQXNum5ab+ruM=,iv:ISIYQhyjeeqhSnW+YW8RDIaruofarhF2BPqSjVe2dqY=,tag:vQILy/a7a6ygUVn5JL5zVQ==,type:str]
                gethomepage.dev/widget.version: ENC[AES256_GCM,data:Wg==,iv:hrljW4m3mlyncBmwBdzdnvvHgcPoKA7m1HuB/fhRILs=,tag:LGvODPT4mdW0FjjmzZXx6Q==,type:str]
    controllers:
        main:
            containers:
                main:
                    env:
                        DB_ENGINE: ENC[AES256_GCM,data:7dnJjHkZxK0=,iv:ynTNeAe77xiPyC4tskjG3HU2w+oOWsgsD1ycgI7BfAY=,tag:7TwLDpOgZBg5Z50hDSqQWA==,type:str]
                        POSTGRES_USER: ENC[AES256_GCM,data:2M09V2C2,iv:njiXrNgBJ+fyH01LHVUmhUdOqbZVwqg+AtK94fCxqi8=,tag:E5M5H4x2D4X0DGLrp6rJow==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:2QeHlA1GAwV7o61adPhBus1hmRC2tzyuDSHFZtSbdf0=,iv:tuUUYVRJWc6aKdI6ebWPmpvrnm1uPaLr771aHioIOiI=,tag:HlH1rRbx9Mn8S7eW7NUNSA==,type:str]
                        POSTGRES_SERVER: ENC[AES256_GCM,data:LF/zNO3Dlj9vaZ0wa+UC,iv:zBIqWS8q1/89FLzEYUfD4Aqd6Qqn4OVMpA/9WMCljdA=,tag:vLdtdEXGQUvH20Ke9NWHhQ==,type:str]
                        POSTGRES_DB: ENC[AES256_GCM,data:tDB+BUlk,iv:vX8UqBGFZkfgQAQbtWUwh7I2F81ZemQp0jHtHzNrwgY=,tag:1uaJ6rSBhnwCDwjpPygs7A==,type:str]
                        OIDC_AUTH_ENABLED: ENC[AES256_GCM,data:lDM6K+o=,iv:rhZ/0GVp+2guWxx/X7RYZ8/4+tRARENpHODUKCXYegg=,tag:oD9DsUbTQ2XRmTEW6Vu2zQ==,type:str]
                        OIDC_SIGNUP_ENABLED: ENC[AES256_GCM,data:ylgY2nY=,iv:r5ELQNv/LxANl2FcDm3Nb+b8f8ch4ACrLCz8e0ID8bU=,tag:6agDdsEc27nO5taLoKPybA==,type:str]
                        #ENC[AES256_GCM,data:UHtLkdIf5J39nI1P6OPT/3jVqBeLczpULuqPbljAzWlyOcyIfuZuYtgsLDJH7/nwH8r7kUpmdQGAZfw54fOxm9ofp6Bok5s3nTVdiejAjVS7j8nf7yTEUQ==,iv:tHGISiQA6EARab+oXTFNlI6e+/75j7Tw3+TVJ0FpiWM=,tag:epvJWHqGyaAxzwvGGphZKQ==,type:comment]
                        #ENC[AES256_GCM,data:6MC37kHEbCkU5oWdWXpDHNANS3a32aTATUow3MKl/V+Q6UkiBay+MBcigIX6/oDg7rOb,iv:4g7i+70Cv5AX6297KvLcjxUhkepdtukkQwunw6bRXYU=,tag:LegRXXV2++M9+1PB4qY7Dw==,type:comment]
                        #ENC[AES256_GCM,data:m/1AyfluTFE8KwBuJgrP49KJ6Z6kFQJuRHqiXjHAQ+TxIy5JCHCAQfKYgTWsEVzngS4fC5CVeKhGWrl7J0Rlm52A29vzczPpyarC90XCvzqcajjtuVEc,iv:9xqMbo+PxRLQHeebHdpA2S9WSHqywjykceosOttW8YY=,tag:e0xW7dLmEG7TJEy6uvgbug==,type:comment]
                        OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:F2G5T0kLe2dY2j5tcU+RyxwaqpU+LaQgkKbvY4KAf54k2Z0CWR5LV+5U1aWTt9tTIb3WfefqxhfMj1Y2rarRiJ7w,iv:48BT18tj4SMy0PCu2YqSzl0IEFvwcs9gc8nMS9C2fXw=,tag:ciiSi5X7g/h2/+4bsRexnw==,type:str]
                        OIDC_CLIENT_ID: ENC[AES256_GCM,data:Fvow7yrpEsKwbFlp3DpiULbG0TyoxlvWL8dd2BE0dyL6BVOy,iv:8qTPc5RwWAh8UmODy9RpmGfUQH/myIbWBvbtc9UJVO8=,tag:H01Udn/zJzTavetESqpMPg==,type:str]
                        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:BeAaE4U6OLg//ErjF173BdM7ShVhOVYaskDaU3QEh84=,iv:02KeHBfFM0111NR3++y1P+UmDFBve26T/yf2zcRSyUE=,tag:k+4NtTimS8tO3umK0KVLLA==,type:str]
                        OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:oUezHIyoNHDw,iv:k44kpF+eUoRfdQ9JNE+XkFIyQc/Nx0afHwHDwIXNQHI=,tag:QRPnALd9XJzYuUEFUuNWUg==,type:str]
                        OIDC_AUTO_REDIRECT: ENC[AES256_GCM,data:xJMRow==,iv:RurT5jUHyHxYtyoyg2kwfkyY2W1XMulqSiDkWrHfSmE=,tag:28BhW6XabDOiGApe6Lu1Uw==,type:str]
                        OIDC_REMEMBER_ME: ENC[AES256_GCM,data:WN135LY=,iv:an6af1OUfttoWwj9l/zFB9JLQjdKXfK2hi6Bl8piGqU=,tag:J2Xy5wN3kC8y85zV2NJylQ==,type:str]
                        OPENAI_BASE_URL: ENC[AES256_GCM,data:vJCAKEqio0zA8vzeqmRN2UHJLrxmSRJOrl/eA76pmraa/x7Nd4PH9KRMZzjjidJk,iv:8MK7m+fWo7lUdK4qrQ1OrrWrB1RoW7Z5rCMwoxXYY8A=,tag:RHMaKrs6zXEu0xVl4kZDsw==,type:str]
                        OPENAI_API_KEY: ENC[AES256_GCM,data:XRWTQ8HsSuNk0lakLEu+/f7w8QBD0d13XV7yKLFQ9yQLLDeYdvQ2,iv:ch/lWY/o6zrML2VK7urojXoRHJHVw//WM+2fDXTNbuo=,tag:Zsh0nNZi0A4oJtLSZMBVkQ==,type:str]
                        OPENAI_MODEL: ENC[AES256_GCM,data:b1UXpCN30QvTlt4oqGhp8A==,iv:uBOOV7kjp6bquTxfP1/zqmZWdmEgphtwlVRfSrZx6qQ=,tag:jtF6q1wTSI8xK84qvHETsg==,type:str]
        postgres:
            containers:
                main:
                    env:
                        POSTGRES_USER: ENC[AES256_GCM,data:JLl8KZn5,iv:3pIH3J1iyFjfHFy3DfO1VU8p2Sz86CUQQIdMa5a4NB4=,tag:QrB2i+n11LzKiuLoK/YxKg==,type:str]
                        POSTGRES_PASSWORD: ENC[AES256_GCM,data:WTYFHUoLo9FY2kRPEBH1rPj8f5NL8nOu3sZnBA2130o=,iv:7XTrfZiEu6ft31dBzheoVzm1Kk5KJKtraNnXjIwxFlA=,tag:ENz2xU5xYOtwKFRpmaj0RQ==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dmN0ODVMN0daZlByTW1x
            OEs3eGwxM1hMVFBqUkhhZDRnajEzSjUwRHlvCjVzdUM1RnV3U1J6ekpERVMwU0xy
            NkZobjFiSGJMMTFGamR4UlY3NVgvSVUKLS0tIFc5d3VaMFpnYTFoN2o3UHFyeHVG
            RnhLK0tuL3p3M1ZTOVlqaTkyWjJNaFUKGaxWtZeiwdzFfnnTjKw+nDPUdOWIDmCu
            wDPG6fOGiY88uAHCWnN64pjpIGi7NsZlV9eI+XdgL4rcEYJsHkzudg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T01:30:36Z"
    mac: ENC[AES256_GCM,data:yI/raUPpmdq0PAuhUzaosCbrgAhbNHUJ+heqeD5vdcZGp5+o5ObmEPndxxJRbMXNx0xF30T64a9TNWBs1QNPk6A5XizaZ2/aMYtUIqTWzYF1xk1AqCx7itP79pj/SEiiym1d2rQtL7yvpH8NplXNRr3QmGQcU2Ge/lP403RXig8=,iv:OpoxCtQjEHrK4H8LkX3wMdCMxQZwMpqY3wMheBbibLw=,tag:+UezIDQboGEB4icniBlH6Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
