app-template:
    ingress:
        primary:
            enabled: ENC[AES256_GCM,data:N/k31w==,iv:xPclgrLWw/cToXBuXSwxgNgGkvr4Wtm0z6bSFXIfOnc=,tag:/hV+KsQp+vP7vWo6VsgX0A==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:5A3JgKHzEXjYLaiz3oi6zQ==,iv:WSBlvTjOep/ZxH+m1VlVmBIJd2cpA5I9XuLHx5rySn0=,tag:hezBwuoFfvF3oRCMGVs1Xg==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:Rwg3Zut6tiKqZqUo,iv:zGAkg30us9Dk9pTpVQ2hrntKcM/5u/envoSEQPKwU70=,tag:5IH2K5w1ct+FxHPhB99mLg==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:A/4St0UCkksjPL8N2QXormGSSEzuy+XKow==,iv:J6qJbSj6twSnMcObFrQ3lyO19P6ItTvtBi1DSoXIRo8=,tag:4+CljcB1ZT5BAduWTxjKag==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:Us2o4A==,iv:kEEA/Fr9YBCtj8UYl9dLl+JstpcAX1JGiBKsEDGTgzc=,tag:NKmZ+Acv94Z0aHXyW+RNiw==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:wFgYBo3FlyquLFM=,iv:iJWywmrJ1PH0UbCwEnCzytTJhDr/73sZ1wWKjpUcY6c=,tag:bilnP1Ljh0rzxh7o3uxdjg==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:jCvsE7BlloueszkYSnHXiQ==,iv:HKzr0bydmnOSBq5i99EIzdnBUpLOmCjuQXGi+okG2lE=,tag:Gnd36ZsEb3rM9nA1+WFAPQ==,type:str]
                gethomepage.dev/pod-selector: ""
                gethomepage.dev/weight: ENC[AES256_GCM,data:4Q==,iv:J3JyStWg18A3G8ijogG6HuWd5v6PDl1mTD5tWwo5FIA=,tag:y9E0V/B54WimPIgnyL4p8A==,type:str]
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:SHVL4uyO7g==,iv:fueqo0uFoU91jxb26YqatZa1dykXDV8MpO3dVf35cyM=,tag:1I1wD9HHCGiYIdnB9Bqgiw==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:How/4EARyaP6I3/be7n70EXZkMrgeaSiQ7iWULZvhMsy3nT+,iv:yj3RzU6B/qft3GQWrMBl/edavbwjJvJQiq5zsYjP9EQ=,tag:EVsGgHJCvqzBSPw53CpU0A==,type:str]
                gethomepage.dev/widget.username: ENC[AES256_GCM,data:tol5aJ9Kew==,iv:IABwWNnEHLfdP+rS1enS0PB7idjmELsvdJ3rYFwOuUo=,tag:ofu13hP+nAbUcWK/AxeYXw==,type:str]
                gethomepage.dev/widget.password: ENC[AES256_GCM,data:Pi7iPWGN3GNp52997eUAwtQfteyGsu/N3Mw=,iv:W7IiQ8t09hxHYOPAtQJ0GrVR5bjcNZJMInC0xnrb1Ig=,tag:SZLjpCtlFhNCiygDHkcGiQ==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:RJYjacKnFx6wzHKPvPjhQ+ecvcDkBqJoEg==,iv:kiQTDnm0CjpcYbA0S7mkjbsoS1MuThsFmHdEgD2JIiw=,tag:UDM7rn6o2l+SHBUhgtsa2g==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:dA==,iv:btYrwBBHNVdLgBtdGv/dD9l6OEPk72TDFC7e8hg2MF4=,tag:ZzvF6bx5P8lA+5eXQ7Kuow==,type:str]
                      pathType: ENC[AES256_GCM,data:pyEiwMej,iv:rAINfY0pVfDIHyif+riKmX0sYfKMi9v0z58NT4IQ9OY=,tag:Ihao07tpnx4y7Rrt3ujIkA==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:Dw4mIA==,iv:USPBu5tsvAlERoCwb83SugO/txf22gcUEywq0CHvmpE=,tag:qLzQj2DlCFgV7F/jMX81Xg==,type:str]
                        port: ENC[AES256_GCM,data:JaI8aQ==,iv:IX/EJOla8SUs6ZQ4atxeoozU9x/wjHy0GKOTB1nlE/4=,tag:1y7eLucsrmNfkHKQ6rxhYw==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:FL+2IHpIO+tY+fzKcpIfvM307EpcxQS/,iv:wbHQPGVrLp/mNoQ6jFuWr7pKz1nniQQcnQasJYkbXBc=,tag:M6bTxVEYWRTrYsqgtf5XiQ==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:gfimaMUjUoDU4YNdO4Tdd/Ii+Tv15zz8lg==,iv:HxMmf4C5C1LmBBZCL1pf8Ks/MuCLNF3Up844IEoXrbY=,tag:GRAbHmkvaaarQo/J6ZmqDA==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN0t4dW92a3BTMUdSMWxs
            Z1orZFVQMDVxYU05R0p4RGN5STRWZVFwVVNnCm1HZE1BYWNpY3BzOXhDYUM2NnVR
            d2JqTzgyMStVWDFVcDN2QVJGTFUveEUKLS0tIGVJZXJtVEdGUThBNE5FV2N4L284
            ZlRWeTI5V1FXczZ6aGdad3ZVZHFteFkKLGL6thX3nFhIeUQr3n7dWB76jvo9SKoY
            7bP52iCkIbkj+6zdtGcTmTB+UIe6k0LkEf9lZCgTXYXA7suT7VxWGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T02:54:27Z"
    mac: ENC[AES256_GCM,data:TyVvNW4kI+0Cx1qk/p8JR+H8vemqydIbzWdeTPmL24wSF8TQsv6ayHSAoHetceozVkRoqi62W9DOYOgxKCvSjuRLPf5NlrszH3N/MyZ7cxvRIbjIHNeAf+m5m4yGZfGqQbFTskKltXxveUfGLQEghZ/SPbEnsueEpa97MSmnKj0=,iv:QHvbxcdKVT3sS7ROiMMT645A3WfLauPEqnKzEJGbzM4=,tag:DAg0DvEJr1DEki8P0wyGJg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
