app-template:
    ingress:
        primary:
            enabled: ENC[AES256_GCM,data:5BHU3A==,iv:A6HsTLP5uYRsHsVkk9mo6/z5gYHoPKeD43c33yGYYK0=,tag:hjvdLgy9VCz+aRehSY1xvQ==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:1h/qUsegX35Hm4/jGyCgng==,iv:hcOF3a0y5v5YXo/fQOTRjTfuhLAcGpLdkXjw0WJPIng=,tag:RPYDaAurstEw3baimq1h/g==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:vKhzu03QqUQuZQ0n,iv:aPdHCxnmJeCCNd2/H6k8F9krqzMdTNUrPSzUDtwFLC8=,tag:lnf16pAc0dlkc66JWNborw==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:Dy6udzJ+3Qo+rdFi11ZNY8zGrxJgnB8zuA==,iv:PWb5YFcPCtEYnOP635MDpXP9fEQWVdm+aHs0pXMjDR4=,tag:h2bNLwlBRrC8RPqA2s/1zA==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:qb9CuQ==,iv:Y70N2SzdUgdjyHxA/2NML6yjwYPlDwcR8jZ+vPhlxYE=,tag:xrapJvSeb7xHdcoIOZ1Msw==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:2IWfHOcdqBEudAc=,iv:siTi+jSbCmTElFqF8f7RbxBf7hROyMy5aEJVigjz9S4=,tag:dT8lnh361Om4SLDOyKvk/A==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:g/iXvfRe52Q1FR7zAeAhyA==,iv:rs/IYCOCY2yn9iqN173rDQ2xxtMqU2j9K5+RnKWKTDc=,tag:2hmXXhPjeALYb+O/VsjiGQ==,type:str]
                gethomepage.dev/pod-selector: ""
                gethomepage.dev/weight: ENC[AES256_GCM,data:pA==,iv:1BZbCH2nIalO5gGu0DN3bemG9KOvDiXFI8jfaZGcFRQ=,tag:69XaAWMYeSYkGgZpz8P1tQ==,type:str]
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:J6BgpspfyQ==,iv:Pa7zfoW3Rxt3gQ4qUKWaKYUuSIcHMKjkYieYi+ZJxlc=,tag:yVmdMnRr3zVXUb8uInbgNw==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:TGaPfDS5aieX5es30SyiWExU2Aog9tOVr5PKQWE2270JcmZBbSX/RPk=,iv:so/YPyw1IUThncNEpf6e6Ev69ch6qD+Jx87Ex1fBH4M=,tag:3/UNU+alVBsDDhAZRDP6Ag==,type:str]
                gethomepage.dev/widget.username: ENC[AES256_GCM,data:Vid6Hpa5Lw==,iv:r5HO6cgD2xNjijEUlocaMUGIq99kzFRgx3f86owH/CM=,tag:KFMBfXCGFVhrZsuybwHMkA==,type:str]
                gethomepage.dev/widget.password: ENC[AES256_GCM,data:UyBWe/HhCKQgdjtblvGOtvA4Lry68vA+0ag=,iv:mLTNUz9ECHyfnSgTd72XP5ClZR8GY0sEXk1ZZfMOuHI=,tag:IVndqve/xD9O6xZXKn9ymA==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:9nEqxhDQExp25wEkm3pjUaz1x59KBIPr5g==,iv:+PfLxeqBHJqy0o0asWo0R5uLdVZuRBhkIvA5tQgB+1w=,tag:yfWn43hmiWUKOy+j1xz+2w==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:xQ==,iv:kDSoNeIn5eZ2NscOQZaUtFaKWnHLQSVstM3Hc5YVX4U=,tag:mn2Ksgrmtn0zxDSY9X9kUQ==,type:str]
                      pathType: ENC[AES256_GCM,data:6tDyIMlI,iv:nc/lv2F30eiJKLHbORzAqGh3mwJ5OfwC/yY12YXdXsw=,tag:mpWBcUu/w50OPjY5vD9ePw==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:2Cf+vg==,iv:KG675XnYpZQDLBR/Yg28tGcWfZILkJsHxNYpTuCidB4=,tag:t15eQunA6LEXxa52vRkAFQ==,type:str]
                        port: ENC[AES256_GCM,data:sE/mvQ==,iv:VUVNDQ4F3yUrX8HDO9aOtyqFC4LN6+pwIQuPMYxMQ0A=,tag:U9mFP/EocHp8BvQLA3lr0w==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:5ooykuuhr04vpFQRKaeDaq1kz54EmsIm,iv:JbIVXW0Qp0PpmGOJLrgjEceGKMPsXyCyuFA9HccSn00=,tag:0RvdKpVY/GcyY06utSfmJA==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:CIGnHM3jEcCTLbhE8Nc4UlBUeP9qWFmnuw==,iv:Gtu5RV3Yrd6NEHUb6m9QC6EqYgqZYH69soLkEO4hajA=,tag:C74EW5LC5TykxobY3VZLFg==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dE5xc1ZnUFFHL3E1aXVG
            ZWpKdk5USW41cS93WmIrU21qclZTemJ6ZVNBCllFRlZ3TjZhMDFiMFNjMlB0VFdO
            aXd5REhmbzY4cFA0VXFLM0hRM0lycW8KLS0tIHYrNnkwRzhyZUpQZVo4cXEwaXAv
            NXBEMytGNUVGckplUjhEeVhKenBFTUkK1bl0+bXzyQttiwH01HWygcd4FjC55mvS
            ZImpBWrORrBk7F8Vt5DZ98TSTVVF9xOwED6Scjm7vj9n5Y2apCTAzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T02:46:48Z"
    mac: ENC[AES256_GCM,data:+QZYhX11+3Gn0iaTu7So0RRZGLEm1dy6npAs5n+QPTTTHZKdZiKEeMFBsBgkQLq+tGHsERsCy30Nr+pZTxu50TBiexHkmtJSIKvJoM6qNeiOkc1FP02xrsBm47gO6cfYrVrM7bdr4D4MzBhOmzl/K4OJ5gNIq/sx3zLyAfT7tv4=,iv:99bNHKJIH97I4gmXnK0QhszI3uzU33SNTam5KH3VYy8=,tag:ZmNEJzWD2mYfWSs29q4bAA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
