app-template:
    ingress:
        primary:
            enabled: ENC[AES256_GCM,data:uaLV/w==,iv:nI7W5WY/1tlWDt/lpKkMZUp0QfoRVxdcijduvqhpi40=,tag:Dp6IlMmEqEgYdPnin43saw==,type:bool]
            annotations:
                cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:qd1fdePP+SP4TKGOnhh73g==,iv:emi76iHuKOj+sPYV2KH1tBZptSyoOGNpkXe3N9BdLpM=,tag:KvLrRRw3QD9fYqVKObOefQ==,type:str]
                gethomepage.dev/name: ENC[AES256_GCM,data:Qd5kHWCY+AY+vRzJ,iv:JCJq/uSN+vZ9mkTnECabcuH5hvJQFbLyGoGQQNuAG54=,tag:Iwr/QmUIspBZ8pejNCS6WA==,type:str]
                gethomepage.dev/description: ENC[AES256_GCM,data:i9ZSfge7O4ZiKMVHtN7FPhnY37Cm43gmMw==,iv:SiheGg1L17zV7anS1zpHYC6sJqf5qeQ33d36KEPugY4=,tag:UHFnUF6f6U8q+GhXDVzDXA==,type:str]
                gethomepage.dev/enabled: ENC[AES256_GCM,data:2oVLSw==,iv:o43BuvbJ+rb981Qry7lPRYSPEu5LEsmjA36yVkEF6UU=,tag:KGbGpPQy6ohmM6BLYxzmdg==,type:str]
                gethomepage.dev/group: ENC[AES256_GCM,data:o/ik7K9VFkluQys=,iv:c65xUJ8D7XIm02QBEOavh4gCx71nudu1nPTxc8XMytU=,tag:LtNsqY4vBcbHy8xxIJpoHQ==,type:str]
                gethomepage.dev/icon: ENC[AES256_GCM,data:TgumGKKlupe+77rYByHXnA==,iv:dYzhQQkSKDpqd2fzaYCEGBCoGGjzdbJhVkAXFki57/Y=,tag:UNmzF2LeksM9XU0PT9Qoug==,type:str]
                gethomepage.dev/pod-selector: ""
                gethomepage.dev/weight: ENC[AES256_GCM,data:XQ==,iv:dus045ZYbKAqhse8KTxPfCjkfgRJqb35ZRBsPlZ2Qjg=,tag:YAez8xBIYBt3iW2iM9J8yg==,type:str]
                gethomepage.dev/widget.type: ENC[AES256_GCM,data:NiO3HVB0eQ==,iv:laXWm9z6RRkWQ5FlYSuJzzlOGplLxfCTYnMhE4dEv0M=,tag:egoZwOjTpA2q4BjSmKjHMA==,type:str]
                gethomepage.dev/widget.url: ENC[AES256_GCM,data:bYGgOnjb/PJ2hKqAhWSTvIppv3Q2K92ilieOFufeGz4/Cepw+X/+AT4=,iv:1F1hWh0bOWAIugHpLWXqgH99EN3xVu2Peiag7Cgvi94=,tag:GzRYlyg2Nk6EVlhbUnHSIw==,type:str]
                gethomepage.dev/widget.username: ENC[AES256_GCM,data:tl+lNqTEXQ==,iv:B5SBYbLlyzAxauB35HCA3RG1P+J+e2NhF2H+P6wawIc=,tag:ZbKyJu0S3TJdFokaHBFldg==,type:str]
                gethomepage.dev/widget.password: ENC[AES256_GCM,data:T1PdMa/cYRDAEisqAFNel9T3BP7nkKXLC+A=,iv:TdP64SIvII74Kngv7ks/mOs6OuU00e8Ivmu91Oxs6zU=,tag:QQFhalTkGegOaRBw0qFfbw==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:BRzNYex10FwiOP/bymwYA8+gTa8cbOeYzw==,iv:wknHXdvN60NAyz2v/cUP+SlgFQ0B+FnK49bcsvO6EoE=,tag:KtDTUJiHLDV0p2/LsMdXzQ==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:ow==,iv:AaSeUvI+Tc0+hdhH/YtC0ahcYumSoqQ6RiGNYV8u+s8=,tag:L2gz6YzMRg1wh+Figr+JRw==,type:str]
                      pathType: ENC[AES256_GCM,data:27wSDtMP,iv:zkkgi5tUW/nxFA9KHUCY10gRGlhGazyY6+NkLIzESSM=,tag:QE2gzJZFjT3okTMyyzJCPg==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:PfZ5Yw==,iv:vKGcVpLpAI48DUJUqnj1GecXv432zBaTJJ42cdGpxaA=,tag:VUNnttuq/GbXvHol4qbVsw==,type:str]
                        port: ENC[AES256_GCM,data:b/bAbQ==,iv:1HxwFE840SWfQ6lZ63BK+ViPyAArRt0pf7FAP9VG00k=,tag:y3JzsSr82Vnfek1ojJvVpA==,type:str]
            tls:
                - secretName: ENC[AES256_GCM,data:HIS+wy7PMvNjGl1RbIL3nW1a4YLd787H,iv:PC76p+sfrzll5iLMj3q7ZL8wpom9vYwcd+D9qX+wbV4=,tag:39XNX4dwa6WIzzN+zVIqCw==,type:str]
                  hosts:
                    - ENC[AES256_GCM,data:y6yDDl4TQAuVZSZ/dK5/9oNUEmuo5O3x3g==,iv:PS/r2sOpeOi9c4Cp944RGAcY6NQq8jpo963hUyhqLIY=,tag:MNDBnyV8eDI5wL7WRtbkng==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYkpOdUp6ai9JQlNiOFE5
            VW4vbStSU3Z4a2JScE9RNTF6MUhsdnZJVFFnClBSTEsyNFRuQmNseE5DOWpwcnp0
            UkJsUUpKQzhZdm55MlgxcWVWdnA0TmsKLS0tIE9JeGdtdS9PR3lsdVdPYVdjNGlQ
            Y2RoamxySEZSWFlFOENuN0R5NG9hdUEK5iUTRCHFUyhODyZ8gUEfNJ55VQx+i5XO
            ty8jJObPImeOkEaINEgW2HBJ0gGbskKOtDgPy2nrGZIWbZv8afI5eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T02:49:23Z"
    mac: ENC[AES256_GCM,data:+Mwi0vDXn1MVAd7hutI3oIiLaBQWFol3AmK2Wj3Dy22ydEU/nKSIhGhq3NApfwsCUSdcMsAvEgz584ziGj9Aj8pOYGpoqUtcG1WxQBGOjxgxKd1wV5k0Ei4eftQ1n3pSXu8R4uIFNR0kUEGhmHcLpb0ViXupeDGXRQ9ULiUPJIY=,iv:J730bp/u7w0Ne3P3Ku3VqOdxJPVXy6wc6ssrKmSUQDs=,tag:TnRG/90xY+HQlFevoSQr7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
