plex-media-server:
    ingress:
        annotations:
            gethomepage.dev/widget.type: ENC[AES256_GCM,data:Ij1Ayg==,iv:D6O8jKHB/ugxyL1Ur9c+FZf5FEEgt/3P9ULtgqShtVU=,tag:WDRHzb0s6mBmUWfWWgdINA==,type:str]
            gethomepage.dev/widget.url: ENC[AES256_GCM,data:zSFz3L1NhXMcRhh8+s3eXi03Ng==,iv:pc5Qb4u3d0il88/fU70bKcDot5LwFo5UQcL9daO8kl8=,tag:KjH0gNoj7M9fYMLPVUFa5w==,type:str]
            gethomepage.dev/widget.key: ENC[AES256_GCM,data:ZyBS0o7NN8eHGXVjVrZlIae3uCI=,iv:+TcvJHM11iIVGKCX229B6XWzaV2fZEKPThl9aZNh1p8=,tag:KzsHtScal72km4YfeB4GDw==,type:str]
sops:
    age:
        - recipient: age138l4lexlaq544ae590zw3fvkggkqk4lyhgqvxtzegurl7xcm0ejq6xandu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeVhqL2Rtalk2ZGFMbUdo
            MlR4ZjZZWGcxRFVYVEJKK3B1eDMvb3NtQVQ0CmNZUTFaMlpHN2dhckNIRFRTSExJ
            UG55UDZoSDRaSENiYUdHeFVvWCtqR2cKLS0tIDBzSklyaXNQMS9CSnd1MGRIeWNQ
            K0MxUlU0M3A5aEJoZDMrRVh5MjllTDQKW9UkaRgws+rqMeo7zxjrs2NpnWh2bofH
            pWkRs4PqZ0SmJI0LXin3uou7QcsjHgooJcuZs/9YAwgOXW5a8aXKPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T02:43:32Z"
    mac: ENC[AES256_GCM,data:eEPv/fc84vDHBh5MOm0qMqsMsZTdHhd5LmxLL+i9BPtS51HReShjVvuCoX0nwFbTHMkUZ4IiYnBuIYwE77MfNJwk18OAsT7eOPzay7CiHbZFOlG2aXCaPoIcwfdo0w1O1BQsWTeQWuivwQsoG4iGSqo+OytMwAus9TJRk+A/6V0=,iv:7STc9oMu8UvCZnFBqM5WECGXpdHkilsyo53/NsEkO4k=,tag:A9smcrTDraIjYT6JIfmKQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
